// platform_intel_agilex_hps_1_altera_mm_interconnect_1920_igmgffi.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 25.1 129

`timescale 1 ps / 1 ps
module platform_intel_agilex_hps_1_altera_mm_interconnect_1920_igmgffi (
		input  wire [6:0]   fpga_interfaces_h2n_ch0_axi_awid,         //        fpga_interfaces_h2n_ch0_axi.awid
		input  wire [43:0]  fpga_interfaces_h2n_ch0_axi_awaddr,       //                                   .awaddr
		input  wire [7:0]   fpga_interfaces_h2n_ch0_axi_awlen,        //                                   .awlen
		input  wire [2:0]   fpga_interfaces_h2n_ch0_axi_awsize,       //                                   .awsize
		input  wire [1:0]   fpga_interfaces_h2n_ch0_axi_awburst,      //                                   .awburst
		input  wire [0:0]   fpga_interfaces_h2n_ch0_axi_awlock,       //                                   .awlock
		input  wire [2:0]   fpga_interfaces_h2n_ch0_axi_awprot,       //                                   .awprot
		input  wire [3:0]   fpga_interfaces_h2n_ch0_axi_awqos,        //                                   .awqos
		input  wire         fpga_interfaces_h2n_ch0_axi_awvalid,      //                                   .awvalid
		output wire         fpga_interfaces_h2n_ch0_axi_awready,      //                                   .awready
		input  wire [255:0] fpga_interfaces_h2n_ch0_axi_wdata,        //                                   .wdata
		input  wire [31:0]  fpga_interfaces_h2n_ch0_axi_wstrb,        //                                   .wstrb
		input  wire         fpga_interfaces_h2n_ch0_axi_wlast,        //                                   .wlast
		input  wire         fpga_interfaces_h2n_ch0_axi_wvalid,       //                                   .wvalid
		output wire         fpga_interfaces_h2n_ch0_axi_wready,       //                                   .wready
		output wire [6:0]   fpga_interfaces_h2n_ch0_axi_bid,          //                                   .bid
		output wire [1:0]   fpga_interfaces_h2n_ch0_axi_bresp,        //                                   .bresp
		output wire         fpga_interfaces_h2n_ch0_axi_bvalid,       //                                   .bvalid
		input  wire         fpga_interfaces_h2n_ch0_axi_bready,       //                                   .bready
		input  wire [6:0]   fpga_interfaces_h2n_ch0_axi_arid,         //                                   .arid
		input  wire [43:0]  fpga_interfaces_h2n_ch0_axi_araddr,       //                                   .araddr
		input  wire [7:0]   fpga_interfaces_h2n_ch0_axi_arlen,        //                                   .arlen
		input  wire [2:0]   fpga_interfaces_h2n_ch0_axi_arsize,       //                                   .arsize
		input  wire [1:0]   fpga_interfaces_h2n_ch0_axi_arburst,      //                                   .arburst
		input  wire [0:0]   fpga_interfaces_h2n_ch0_axi_arlock,       //                                   .arlock
		input  wire [2:0]   fpga_interfaces_h2n_ch0_axi_arprot,       //                                   .arprot
		input  wire [3:0]   fpga_interfaces_h2n_ch0_axi_arqos,        //                                   .arqos
		input  wire         fpga_interfaces_h2n_ch0_axi_arvalid,      //                                   .arvalid
		output wire         fpga_interfaces_h2n_ch0_axi_arready,      //                                   .arready
		output wire [6:0]   fpga_interfaces_h2n_ch0_axi_rid,          //                                   .rid
		output wire [255:0] fpga_interfaces_h2n_ch0_axi_rdata,        //                                   .rdata
		output wire [1:0]   fpga_interfaces_h2n_ch0_axi_rresp,        //                                   .rresp
		output wire         fpga_interfaces_h2n_ch0_axi_rlast,        //                                   .rlast
		output wire         fpga_interfaces_h2n_ch0_axi_rvalid,       //                                   .rvalid
		input  wire         fpga_interfaces_h2n_ch0_axi_rready,       //                                   .rready
		output wire [6:0]   iniu_0_altera_axi_slave_awid,             //            iniu_0_altera_axi_slave.awid
		output wire [43:0]  iniu_0_altera_axi_slave_awaddr,           //                                   .awaddr
		output wire [7:0]   iniu_0_altera_axi_slave_awlen,            //                                   .awlen
		output wire [2:0]   iniu_0_altera_axi_slave_awsize,           //                                   .awsize
		output wire [1:0]   iniu_0_altera_axi_slave_awburst,          //                                   .awburst
		output wire [0:0]   iniu_0_altera_axi_slave_awlock,           //                                   .awlock
		output wire [2:0]   iniu_0_altera_axi_slave_awprot,           //                                   .awprot
		output wire [10:0]  iniu_0_altera_axi_slave_awuser,           //                                   .awuser
		output wire [3:0]   iniu_0_altera_axi_slave_awqos,            //                                   .awqos
		output wire         iniu_0_altera_axi_slave_awvalid,          //                                   .awvalid
		input  wire         iniu_0_altera_axi_slave_awready,          //                                   .awready
		output wire [255:0] iniu_0_altera_axi_slave_wdata,            //                                   .wdata
		output wire [31:0]  iniu_0_altera_axi_slave_wstrb,            //                                   .wstrb
		output wire         iniu_0_altera_axi_slave_wlast,            //                                   .wlast
		output wire         iniu_0_altera_axi_slave_wvalid,           //                                   .wvalid
		output wire [31:0]  iniu_0_altera_axi_slave_wuser,            //                                   .wuser
		input  wire         iniu_0_altera_axi_slave_wready,           //                                   .wready
		input  wire [6:0]   iniu_0_altera_axi_slave_bid,              //                                   .bid
		input  wire [1:0]   iniu_0_altera_axi_slave_bresp,            //                                   .bresp
		input  wire         iniu_0_altera_axi_slave_bvalid,           //                                   .bvalid
		output wire         iniu_0_altera_axi_slave_bready,           //                                   .bready
		output wire [6:0]   iniu_0_altera_axi_slave_arid,             //                                   .arid
		output wire [43:0]  iniu_0_altera_axi_slave_araddr,           //                                   .araddr
		output wire [7:0]   iniu_0_altera_axi_slave_arlen,            //                                   .arlen
		output wire [2:0]   iniu_0_altera_axi_slave_arsize,           //                                   .arsize
		output wire [1:0]   iniu_0_altera_axi_slave_arburst,          //                                   .arburst
		output wire [0:0]   iniu_0_altera_axi_slave_arlock,           //                                   .arlock
		output wire [2:0]   iniu_0_altera_axi_slave_arprot,           //                                   .arprot
		output wire [10:0]  iniu_0_altera_axi_slave_aruser,           //                                   .aruser
		output wire [3:0]   iniu_0_altera_axi_slave_arqos,            //                                   .arqos
		output wire         iniu_0_altera_axi_slave_arvalid,          //                                   .arvalid
		input  wire         iniu_0_altera_axi_slave_arready,          //                                   .arready
		input  wire [6:0]   iniu_0_altera_axi_slave_rid,              //                                   .rid
		input  wire [255:0] iniu_0_altera_axi_slave_rdata,            //                                   .rdata
		input  wire [1:0]   iniu_0_altera_axi_slave_rresp,            //                                   .rresp
		input  wire         iniu_0_altera_axi_slave_rlast,            //                                   .rlast
		input  wire         iniu_0_altera_axi_slave_rvalid,           //                                   .rvalid
		output wire         iniu_0_altera_axi_slave_rready,           //                                   .rready
		input  wire [31:0]  iniu_0_altera_axi_slave_ruser,            //                                   .ruser
		input  wire         iniu_0_reset_reset_bridge_in_reset_reset, // iniu_0_reset_reset_bridge_in_reset.reset,  Reset Input
		input  wire         fpga_interfaces_h2n_ch0_axi_clk_clk       //    fpga_interfaces_h2n_ch0_axi_clk.clk,    Clock Input
	);

	wire   [31:0] fpga_interfaces_h2n_ch0_axi_translator_m0_ruser;    // iniu_0_altera_axi_slave_translator:s0_ruser -> fpga_interfaces_h2n_ch0_axi_translator:m0_ruser
	wire   [31:0] fpga_interfaces_h2n_ch0_axi_translator_m0_wuser;    // fpga_interfaces_h2n_ch0_axi_translator:m0_wuser -> iniu_0_altera_axi_slave_translator:s0_wuser
	wire    [1:0] fpga_interfaces_h2n_ch0_axi_translator_m0_awburst;  // fpga_interfaces_h2n_ch0_axi_translator:m0_awburst -> iniu_0_altera_axi_slave_translator:s0_awburst
	wire    [3:0] fpga_interfaces_h2n_ch0_axi_translator_m0_arregion; // fpga_interfaces_h2n_ch0_axi_translator:m0_arregion -> iniu_0_altera_axi_slave_translator:s0_arregion
	wire   [10:0] fpga_interfaces_h2n_ch0_axi_translator_m0_awuser;   // fpga_interfaces_h2n_ch0_axi_translator:m0_awuser -> iniu_0_altera_axi_slave_translator:s0_awuser
	wire    [7:0] fpga_interfaces_h2n_ch0_axi_translator_m0_arlen;    // fpga_interfaces_h2n_ch0_axi_translator:m0_arlen -> iniu_0_altera_axi_slave_translator:s0_arlen
	wire    [3:0] fpga_interfaces_h2n_ch0_axi_translator_m0_arqos;    // fpga_interfaces_h2n_ch0_axi_translator:m0_arqos -> iniu_0_altera_axi_slave_translator:s0_arqos
	wire   [31:0] fpga_interfaces_h2n_ch0_axi_translator_m0_wstrb;    // fpga_interfaces_h2n_ch0_axi_translator:m0_wstrb -> iniu_0_altera_axi_slave_translator:s0_wstrb
	wire          fpga_interfaces_h2n_ch0_axi_translator_m0_wready;   // iniu_0_altera_axi_slave_translator:s0_wready -> fpga_interfaces_h2n_ch0_axi_translator:m0_wready
	wire    [6:0] fpga_interfaces_h2n_ch0_axi_translator_m0_rid;      // iniu_0_altera_axi_slave_translator:s0_rid -> fpga_interfaces_h2n_ch0_axi_translator:m0_rid
	wire          fpga_interfaces_h2n_ch0_axi_translator_m0_rready;   // fpga_interfaces_h2n_ch0_axi_translator:m0_rready -> iniu_0_altera_axi_slave_translator:s0_rready
	wire    [7:0] fpga_interfaces_h2n_ch0_axi_translator_m0_awlen;    // fpga_interfaces_h2n_ch0_axi_translator:m0_awlen -> iniu_0_altera_axi_slave_translator:s0_awlen
	wire    [3:0] fpga_interfaces_h2n_ch0_axi_translator_m0_awqos;    // fpga_interfaces_h2n_ch0_axi_translator:m0_awqos -> iniu_0_altera_axi_slave_translator:s0_awqos
	wire    [3:0] fpga_interfaces_h2n_ch0_axi_translator_m0_arcache;  // fpga_interfaces_h2n_ch0_axi_translator:m0_arcache -> iniu_0_altera_axi_slave_translator:s0_arcache
	wire          fpga_interfaces_h2n_ch0_axi_translator_m0_wvalid;   // fpga_interfaces_h2n_ch0_axi_translator:m0_wvalid -> iniu_0_altera_axi_slave_translator:s0_wvalid
	wire   [43:0] fpga_interfaces_h2n_ch0_axi_translator_m0_araddr;   // fpga_interfaces_h2n_ch0_axi_translator:m0_araddr -> iniu_0_altera_axi_slave_translator:s0_araddr
	wire    [2:0] fpga_interfaces_h2n_ch0_axi_translator_m0_arprot;   // fpga_interfaces_h2n_ch0_axi_translator:m0_arprot -> iniu_0_altera_axi_slave_translator:s0_arprot
	wire    [2:0] fpga_interfaces_h2n_ch0_axi_translator_m0_awprot;   // fpga_interfaces_h2n_ch0_axi_translator:m0_awprot -> iniu_0_altera_axi_slave_translator:s0_awprot
	wire  [255:0] fpga_interfaces_h2n_ch0_axi_translator_m0_wdata;    // fpga_interfaces_h2n_ch0_axi_translator:m0_wdata -> iniu_0_altera_axi_slave_translator:s0_wdata
	wire          fpga_interfaces_h2n_ch0_axi_translator_m0_arvalid;  // fpga_interfaces_h2n_ch0_axi_translator:m0_arvalid -> iniu_0_altera_axi_slave_translator:s0_arvalid
	wire    [3:0] fpga_interfaces_h2n_ch0_axi_translator_m0_awcache;  // fpga_interfaces_h2n_ch0_axi_translator:m0_awcache -> iniu_0_altera_axi_slave_translator:s0_awcache
	wire    [6:0] fpga_interfaces_h2n_ch0_axi_translator_m0_arid;     // fpga_interfaces_h2n_ch0_axi_translator:m0_arid -> iniu_0_altera_axi_slave_translator:s0_arid
	wire    [0:0] fpga_interfaces_h2n_ch0_axi_translator_m0_arlock;   // fpga_interfaces_h2n_ch0_axi_translator:m0_arlock -> iniu_0_altera_axi_slave_translator:s0_arlock
	wire    [0:0] fpga_interfaces_h2n_ch0_axi_translator_m0_awlock;   // fpga_interfaces_h2n_ch0_axi_translator:m0_awlock -> iniu_0_altera_axi_slave_translator:s0_awlock
	wire   [43:0] fpga_interfaces_h2n_ch0_axi_translator_m0_awaddr;   // fpga_interfaces_h2n_ch0_axi_translator:m0_awaddr -> iniu_0_altera_axi_slave_translator:s0_awaddr
	wire    [1:0] fpga_interfaces_h2n_ch0_axi_translator_m0_bresp;    // iniu_0_altera_axi_slave_translator:s0_bresp -> fpga_interfaces_h2n_ch0_axi_translator:m0_bresp
	wire          fpga_interfaces_h2n_ch0_axi_translator_m0_arready;  // iniu_0_altera_axi_slave_translator:s0_arready -> fpga_interfaces_h2n_ch0_axi_translator:m0_arready
	wire  [255:0] fpga_interfaces_h2n_ch0_axi_translator_m0_rdata;    // iniu_0_altera_axi_slave_translator:s0_rdata -> fpga_interfaces_h2n_ch0_axi_translator:m0_rdata
	wire          fpga_interfaces_h2n_ch0_axi_translator_m0_awready;  // iniu_0_altera_axi_slave_translator:s0_awready -> fpga_interfaces_h2n_ch0_axi_translator:m0_awready
	wire    [1:0] fpga_interfaces_h2n_ch0_axi_translator_m0_arburst;  // fpga_interfaces_h2n_ch0_axi_translator:m0_arburst -> iniu_0_altera_axi_slave_translator:s0_arburst
	wire    [2:0] fpga_interfaces_h2n_ch0_axi_translator_m0_arsize;   // fpga_interfaces_h2n_ch0_axi_translator:m0_arsize -> iniu_0_altera_axi_slave_translator:s0_arsize
	wire          fpga_interfaces_h2n_ch0_axi_translator_m0_bready;   // fpga_interfaces_h2n_ch0_axi_translator:m0_bready -> iniu_0_altera_axi_slave_translator:s0_bready
	wire          fpga_interfaces_h2n_ch0_axi_translator_m0_rlast;    // iniu_0_altera_axi_slave_translator:s0_rlast -> fpga_interfaces_h2n_ch0_axi_translator:m0_rlast
	wire          fpga_interfaces_h2n_ch0_axi_translator_m0_wlast;    // fpga_interfaces_h2n_ch0_axi_translator:m0_wlast -> iniu_0_altera_axi_slave_translator:s0_wlast
	wire    [3:0] fpga_interfaces_h2n_ch0_axi_translator_m0_awregion; // fpga_interfaces_h2n_ch0_axi_translator:m0_awregion -> iniu_0_altera_axi_slave_translator:s0_awregion
	wire   [31:0] fpga_interfaces_h2n_ch0_axi_translator_m0_buser;    // iniu_0_altera_axi_slave_translator:s0_buser -> fpga_interfaces_h2n_ch0_axi_translator:m0_buser
	wire    [1:0] fpga_interfaces_h2n_ch0_axi_translator_m0_rresp;    // iniu_0_altera_axi_slave_translator:s0_rresp -> fpga_interfaces_h2n_ch0_axi_translator:m0_rresp
	wire    [6:0] fpga_interfaces_h2n_ch0_axi_translator_m0_awid;     // fpga_interfaces_h2n_ch0_axi_translator:m0_awid -> iniu_0_altera_axi_slave_translator:s0_awid
	wire    [6:0] fpga_interfaces_h2n_ch0_axi_translator_m0_bid;      // iniu_0_altera_axi_slave_translator:s0_bid -> fpga_interfaces_h2n_ch0_axi_translator:m0_bid
	wire          fpga_interfaces_h2n_ch0_axi_translator_m0_bvalid;   // iniu_0_altera_axi_slave_translator:s0_bvalid -> fpga_interfaces_h2n_ch0_axi_translator:m0_bvalid
	wire    [2:0] fpga_interfaces_h2n_ch0_axi_translator_m0_awsize;   // fpga_interfaces_h2n_ch0_axi_translator:m0_awsize -> iniu_0_altera_axi_slave_translator:s0_awsize
	wire          fpga_interfaces_h2n_ch0_axi_translator_m0_awvalid;  // fpga_interfaces_h2n_ch0_axi_translator:m0_awvalid -> iniu_0_altera_axi_slave_translator:s0_awvalid
	wire   [10:0] fpga_interfaces_h2n_ch0_axi_translator_m0_aruser;   // fpga_interfaces_h2n_ch0_axi_translator:m0_aruser -> iniu_0_altera_axi_slave_translator:s0_aruser
	wire          fpga_interfaces_h2n_ch0_axi_translator_m0_rvalid;   // iniu_0_altera_axi_slave_translator:s0_rvalid -> fpga_interfaces_h2n_ch0_axi_translator:m0_rvalid

	platform_intel_agilex_hps_1_altera_merlin_axi_translator_1974_xfkiwxi #(
		.USE_S0_AWID                       (1),
		.USE_S0_AWREGION                   (0),
		.USE_M0_AWREGION                   (1),
		.USE_S0_AWLEN                      (1),
		.USE_S0_AWSIZE                     (1),
		.USE_S0_AWBURST                    (1),
		.USE_S0_AWLOCK                     (1),
		.USE_M0_AWLOCK                     (1),
		.USE_S0_AWCACHE                    (0),
		.USE_M0_AWCACHE                    (1),
		.USE_M0_AWPROT                     (1),
		.USE_S0_AWPROT                     (1),
		.USE_S0_AWQOS                      (1),
		.USE_M0_AWQOS                      (1),
		.USE_S0_WSTRB                      (1),
		.USE_M0_WLAST                      (1),
		.USE_S0_WLAST                      (1),
		.USE_S0_BID                        (1),
		.USE_S0_BRESP                      (1),
		.USE_M0_BRESP                      (1),
		.USE_S0_ARID                       (1),
		.USE_S0_ARREGION                   (0),
		.USE_M0_ARREGION                   (1),
		.USE_S0_ARLEN                      (1),
		.USE_S0_ARSIZE                     (1),
		.USE_S0_ARBURST                    (1),
		.USE_S0_ARLOCK                     (1),
		.USE_M0_ARLOCK                     (1),
		.USE_M0_ARCACHE                    (1),
		.USE_M0_ARQOS                      (1),
		.USE_M0_ARPROT                     (1),
		.USE_S0_ARPROT                     (1),
		.USE_S0_ARCACHE                    (0),
		.USE_S0_ARQOS                      (1),
		.USE_S0_RID                        (1),
		.USE_S0_RRESP                      (1),
		.USE_M0_RRESP                      (1),
		.USE_S0_RLAST                      (1),
		.USE_S0_AWUSER                     (0),
		.USE_S0_ARUSER                     (0),
		.USE_S0_WUSER                      (0),
		.USE_S0_RUSER                      (0),
		.USE_S0_BUSER                      (0),
		.USE_M0_AWUSER                     (1),
		.USE_M0_ARUSER                     (1),
		.USE_M0_WUSER                      (1),
		.USE_M0_RUSER                      (1),
		.USE_M0_BUSER                      (1),
		.USE_M0_AWUSER_ADDRCHK             (1),
		.USE_M0_AWUSER_SAI                 (1),
		.USE_M0_ARUSER_ADDRCHK             (1),
		.USE_M0_ARUSER_SAI                 (1),
		.USE_M0_WUSER_DATACHK              (1),
		.USE_M0_WUSER_POISON               (1),
		.USE_M0_RUSER_DATACHK              (1),
		.USE_M0_RUSER_POISON               (1),
		.USE_M0_WUSER_DATA                 (1),
		.USE_M0_RUSER_DATA                 (1),
		.USE_M0_AWAKEUP                    (0),
		.USE_M0_WPOISON                    (0),
		.USE_M0_RPOISON                    (0),
		.USE_M0_AWTRACE                    (0),
		.USE_M0_ARTRACE                    (0),
		.USE_M0_WTRACE                     (0),
		.USE_M0_BTRACE                     (0),
		.USE_M0_RTRACE                     (0),
		.USE_M0_WDATACHK                   (0),
		.USE_M0_RDATACHK                   (0),
		.USE_M0_AWUNIQUE                   (1),
		.USE_S0_AWAKEUP                    (0),
		.USE_S0_WPOISON                    (0),
		.USE_S0_RPOISON                    (0),
		.USE_S0_AWTRACE                    (0),
		.USE_S0_ARTRACE                    (0),
		.USE_S0_WTRACE                     (0),
		.USE_S0_BTRACE                     (0),
		.USE_S0_RTRACE                     (0),
		.USE_S0_WDATACHK                   (0),
		.USE_S0_RDATACHK                   (0),
		.USE_S0_AWUSER_ADDRCHK             (0),
		.USE_S0_AWUSER_SAI                 (0),
		.USE_S0_ARUSER_ADDRCHK             (0),
		.USE_S0_ARUSER_SAI                 (0),
		.USE_S0_WUSER_DATACHK              (0),
		.USE_S0_WUSER_POISON               (0),
		.USE_S0_RUSER_DATACHK              (0),
		.USE_S0_WUSER_DATA                 (0),
		.USE_S0_RUSER_DATA                 (0),
		.USE_S0_RUSER_POISON               (0),
		.USE_S0_AWUNIQUE                   (0),
		.M0_ID_WIDTH                       (7),
		.DATA_WIDTH                        (256),
		.M0_SAI_WIDTH                      (1),
		.S0_SAI_WIDTH                      (1),
		.USER_DATA_WIDTH                   (1),
		.M0_USER_ADDRCHK_WIDTH             (1),
		.S0_USER_ADDRCHK_WIDTH             (1),
		.S0_ID_WIDTH                       (7),
		.M0_ADDR_WIDTH                     (44),
		.S0_WRITE_ADDR_USER_WIDTH          (1),
		.S0_READ_ADDR_USER_WIDTH           (1),
		.M0_WRITE_ADDR_USER_WIDTH          (11),
		.M0_READ_ADDR_USER_WIDTH           (11),
		.S0_WRITE_DATA_USER_WIDTH          (1),
		.S0_WRITE_RESPONSE_DATA_USER_WIDTH (1),
		.S0_READ_DATA_USER_WIDTH           (1),
		.M0_WRITE_DATA_USER_WIDTH          (32),
		.M0_WRITE_RESPONSE_DATA_USER_WIDTH (32),
		.M0_READ_DATA_USER_WIDTH           (32),
		.S0_ADDR_WIDTH                     (44),
		.M0_AXI_VERSION                    ("AXI4"),
		.M0_BURST_LENGTH_WIDTH             (8),
		.S0_BURST_LENGTH_WIDTH             (8),
		.M0_LOCK_WIDTH                     (1),
		.S0_LOCK_WIDTH                     (1),
		.S0_AXI_VERSION                    ("AXI4"),
		.ACE_LITE_SUPPORT                  (0),
		.REGENERATE_ADDRCHK                (0),
		.ROLE_BASED_USER                   (0)
	) fpga_interfaces_h2n_ch0_axi_translator (
		.aclk              (fpga_interfaces_h2n_ch0_axi_clk_clk),                //   input,    width = 1,       clk.clk
		.aresetn           (~iniu_0_reset_reset_bridge_in_reset_reset),          //   input,    width = 1, clk_reset.reset_n
		.m0_awid           (fpga_interfaces_h2n_ch0_axi_translator_m0_awid),     //  output,    width = 7,        m0.awid
		.m0_awaddr         (fpga_interfaces_h2n_ch0_axi_translator_m0_awaddr),   //  output,   width = 44,          .awaddr
		.m0_awlen          (fpga_interfaces_h2n_ch0_axi_translator_m0_awlen),    //  output,    width = 8,          .awlen
		.m0_awsize         (fpga_interfaces_h2n_ch0_axi_translator_m0_awsize),   //  output,    width = 3,          .awsize
		.m0_awburst        (fpga_interfaces_h2n_ch0_axi_translator_m0_awburst),  //  output,    width = 2,          .awburst
		.m0_awlock         (fpga_interfaces_h2n_ch0_axi_translator_m0_awlock),   //  output,    width = 1,          .awlock
		.m0_awcache        (fpga_interfaces_h2n_ch0_axi_translator_m0_awcache),  //  output,    width = 4,          .awcache
		.m0_awprot         (fpga_interfaces_h2n_ch0_axi_translator_m0_awprot),   //  output,    width = 3,          .awprot
		.m0_awuser         (fpga_interfaces_h2n_ch0_axi_translator_m0_awuser),   //  output,   width = 11,          .awuser
		.m0_awqos          (fpga_interfaces_h2n_ch0_axi_translator_m0_awqos),    //  output,    width = 4,          .awqos
		.m0_awregion       (fpga_interfaces_h2n_ch0_axi_translator_m0_awregion), //  output,    width = 4,          .awregion
		.m0_awvalid        (fpga_interfaces_h2n_ch0_axi_translator_m0_awvalid),  //  output,    width = 1,          .awvalid
		.m0_awready        (fpga_interfaces_h2n_ch0_axi_translator_m0_awready),  //   input,    width = 1,          .awready
		.m0_wdata          (fpga_interfaces_h2n_ch0_axi_translator_m0_wdata),    //  output,  width = 256,          .wdata
		.m0_wstrb          (fpga_interfaces_h2n_ch0_axi_translator_m0_wstrb),    //  output,   width = 32,          .wstrb
		.m0_wlast          (fpga_interfaces_h2n_ch0_axi_translator_m0_wlast),    //  output,    width = 1,          .wlast
		.m0_wvalid         (fpga_interfaces_h2n_ch0_axi_translator_m0_wvalid),   //  output,    width = 1,          .wvalid
		.m0_wuser          (fpga_interfaces_h2n_ch0_axi_translator_m0_wuser),    //  output,   width = 32,          .wuser
		.m0_wready         (fpga_interfaces_h2n_ch0_axi_translator_m0_wready),   //   input,    width = 1,          .wready
		.m0_bid            (fpga_interfaces_h2n_ch0_axi_translator_m0_bid),      //   input,    width = 7,          .bid
		.m0_bresp          (fpga_interfaces_h2n_ch0_axi_translator_m0_bresp),    //   input,    width = 2,          .bresp
		.m0_buser          (fpga_interfaces_h2n_ch0_axi_translator_m0_buser),    //   input,   width = 32,          .buser
		.m0_bvalid         (fpga_interfaces_h2n_ch0_axi_translator_m0_bvalid),   //   input,    width = 1,          .bvalid
		.m0_bready         (fpga_interfaces_h2n_ch0_axi_translator_m0_bready),   //  output,    width = 1,          .bready
		.m0_arid           (fpga_interfaces_h2n_ch0_axi_translator_m0_arid),     //  output,    width = 7,          .arid
		.m0_araddr         (fpga_interfaces_h2n_ch0_axi_translator_m0_araddr),   //  output,   width = 44,          .araddr
		.m0_arlen          (fpga_interfaces_h2n_ch0_axi_translator_m0_arlen),    //  output,    width = 8,          .arlen
		.m0_arsize         (fpga_interfaces_h2n_ch0_axi_translator_m0_arsize),   //  output,    width = 3,          .arsize
		.m0_arburst        (fpga_interfaces_h2n_ch0_axi_translator_m0_arburst),  //  output,    width = 2,          .arburst
		.m0_arlock         (fpga_interfaces_h2n_ch0_axi_translator_m0_arlock),   //  output,    width = 1,          .arlock
		.m0_arcache        (fpga_interfaces_h2n_ch0_axi_translator_m0_arcache),  //  output,    width = 4,          .arcache
		.m0_arprot         (fpga_interfaces_h2n_ch0_axi_translator_m0_arprot),   //  output,    width = 3,          .arprot
		.m0_aruser         (fpga_interfaces_h2n_ch0_axi_translator_m0_aruser),   //  output,   width = 11,          .aruser
		.m0_arqos          (fpga_interfaces_h2n_ch0_axi_translator_m0_arqos),    //  output,    width = 4,          .arqos
		.m0_arregion       (fpga_interfaces_h2n_ch0_axi_translator_m0_arregion), //  output,    width = 4,          .arregion
		.m0_arvalid        (fpga_interfaces_h2n_ch0_axi_translator_m0_arvalid),  //  output,    width = 1,          .arvalid
		.m0_arready        (fpga_interfaces_h2n_ch0_axi_translator_m0_arready),  //   input,    width = 1,          .arready
		.m0_rid            (fpga_interfaces_h2n_ch0_axi_translator_m0_rid),      //   input,    width = 7,          .rid
		.m0_rdata          (fpga_interfaces_h2n_ch0_axi_translator_m0_rdata),    //   input,  width = 256,          .rdata
		.m0_rresp          (fpga_interfaces_h2n_ch0_axi_translator_m0_rresp),    //   input,    width = 2,          .rresp
		.m0_rlast          (fpga_interfaces_h2n_ch0_axi_translator_m0_rlast),    //   input,    width = 1,          .rlast
		.m0_rvalid         (fpga_interfaces_h2n_ch0_axi_translator_m0_rvalid),   //   input,    width = 1,          .rvalid
		.m0_rready         (fpga_interfaces_h2n_ch0_axi_translator_m0_rready),   //  output,    width = 1,          .rready
		.m0_ruser          (fpga_interfaces_h2n_ch0_axi_translator_m0_ruser),    //   input,   width = 32,          .ruser
		.s0_awid           (fpga_interfaces_h2n_ch0_axi_awid),                   //   input,    width = 7,        s0.awid
		.s0_awaddr         (fpga_interfaces_h2n_ch0_axi_awaddr),                 //   input,   width = 44,          .awaddr
		.s0_awlen          (fpga_interfaces_h2n_ch0_axi_awlen),                  //   input,    width = 8,          .awlen
		.s0_awsize         (fpga_interfaces_h2n_ch0_axi_awsize),                 //   input,    width = 3,          .awsize
		.s0_awburst        (fpga_interfaces_h2n_ch0_axi_awburst),                //   input,    width = 2,          .awburst
		.s0_awlock         (fpga_interfaces_h2n_ch0_axi_awlock),                 //   input,    width = 1,          .awlock
		.s0_awprot         (fpga_interfaces_h2n_ch0_axi_awprot),                 //   input,    width = 3,          .awprot
		.s0_awqos          (fpga_interfaces_h2n_ch0_axi_awqos),                  //   input,    width = 4,          .awqos
		.s0_awvalid        (fpga_interfaces_h2n_ch0_axi_awvalid),                //   input,    width = 1,          .awvalid
		.s0_awready        (fpga_interfaces_h2n_ch0_axi_awready),                //  output,    width = 1,          .awready
		.s0_wdata          (fpga_interfaces_h2n_ch0_axi_wdata),                  //   input,  width = 256,          .wdata
		.s0_wstrb          (fpga_interfaces_h2n_ch0_axi_wstrb),                  //   input,   width = 32,          .wstrb
		.s0_wlast          (fpga_interfaces_h2n_ch0_axi_wlast),                  //   input,    width = 1,          .wlast
		.s0_wvalid         (fpga_interfaces_h2n_ch0_axi_wvalid),                 //   input,    width = 1,          .wvalid
		.s0_wready         (fpga_interfaces_h2n_ch0_axi_wready),                 //  output,    width = 1,          .wready
		.s0_bid            (fpga_interfaces_h2n_ch0_axi_bid),                    //  output,    width = 7,          .bid
		.s0_bresp          (fpga_interfaces_h2n_ch0_axi_bresp),                  //  output,    width = 2,          .bresp
		.s0_bvalid         (fpga_interfaces_h2n_ch0_axi_bvalid),                 //  output,    width = 1,          .bvalid
		.s0_bready         (fpga_interfaces_h2n_ch0_axi_bready),                 //   input,    width = 1,          .bready
		.s0_arid           (fpga_interfaces_h2n_ch0_axi_arid),                   //   input,    width = 7,          .arid
		.s0_araddr         (fpga_interfaces_h2n_ch0_axi_araddr),                 //   input,   width = 44,          .araddr
		.s0_arlen          (fpga_interfaces_h2n_ch0_axi_arlen),                  //   input,    width = 8,          .arlen
		.s0_arsize         (fpga_interfaces_h2n_ch0_axi_arsize),                 //   input,    width = 3,          .arsize
		.s0_arburst        (fpga_interfaces_h2n_ch0_axi_arburst),                //   input,    width = 2,          .arburst
		.s0_arlock         (fpga_interfaces_h2n_ch0_axi_arlock),                 //   input,    width = 1,          .arlock
		.s0_arprot         (fpga_interfaces_h2n_ch0_axi_arprot),                 //   input,    width = 3,          .arprot
		.s0_arqos          (fpga_interfaces_h2n_ch0_axi_arqos),                  //   input,    width = 4,          .arqos
		.s0_arvalid        (fpga_interfaces_h2n_ch0_axi_arvalid),                //   input,    width = 1,          .arvalid
		.s0_arready        (fpga_interfaces_h2n_ch0_axi_arready),                //  output,    width = 1,          .arready
		.s0_rid            (fpga_interfaces_h2n_ch0_axi_rid),                    //  output,    width = 7,          .rid
		.s0_rdata          (fpga_interfaces_h2n_ch0_axi_rdata),                  //  output,  width = 256,          .rdata
		.s0_rresp          (fpga_interfaces_h2n_ch0_axi_rresp),                  //  output,    width = 2,          .rresp
		.s0_rlast          (fpga_interfaces_h2n_ch0_axi_rlast),                  //  output,    width = 1,          .rlast
		.s0_rvalid         (fpga_interfaces_h2n_ch0_axi_rvalid),                 //  output,    width = 1,          .rvalid
		.s0_rready         (fpga_interfaces_h2n_ch0_axi_rready),                 //   input,    width = 1,          .rready
		.m0_awuser_addrchk (),                                                   // (terminated),                         
		.m0_awuser_sai     (),                                                   // (terminated),                         
		.m0_wuser_datachk  (),                                                   // (terminated),                         
		.m0_wuser_data     (),                                                   // (terminated),                         
		.m0_wuser_poison   (),                                                   // (terminated),                         
		.m0_aruser_addrchk (),                                                   // (terminated),                         
		.m0_aruser_sai     (),                                                   // (terminated),                         
		.m0_ruser_datachk  (32'b00000000000000000000000000000000),               // (terminated),                         
		.m0_ruser_data     (1'b0),                                               // (terminated),                         
		.m0_ruser_poison   (4'b0000),                                            // (terminated),                         
		.s0_awcache        (4'b0000),                                            // (terminated),                         
		.s0_awuser         (1'b0),                                               // (terminated),                         
		.s0_awuser_addrchk (1'b0),                                               // (terminated),                         
		.s0_awuser_sai     (1'b0),                                               // (terminated),                         
		.s0_awregion       (4'b0000),                                            // (terminated),                         
		.s0_wuser          (1'b0),                                               // (terminated),                         
		.s0_wuser_datachk  (32'b00000000000000000000000000000000),               // (terminated),                         
		.s0_wuser_data     (1'b0),                                               // (terminated),                         
		.s0_wuser_poison   (4'b0000),                                            // (terminated),                         
		.s0_buser          (),                                                   // (terminated),                         
		.s0_arcache        (4'b0000),                                            // (terminated),                         
		.s0_aruser         (1'b0),                                               // (terminated),                         
		.s0_aruser_addrchk (1'b0),                                               // (terminated),                         
		.s0_aruser_sai     (1'b0),                                               // (terminated),                         
		.s0_arregion       (4'b0000),                                            // (terminated),                         
		.s0_ruser          (),                                                   // (terminated),                         
		.s0_ruser_datachk  (),                                                   // (terminated),                         
		.s0_ruser_data     (),                                                   // (terminated),                         
		.s0_ruser_poison   (),                                                   // (terminated),                         
		.m0_awakeup        (),                                                   // (terminated),                         
		.m0_awtrace        (),                                                   // (terminated),                         
		.m0_artrace        (),                                                   // (terminated),                         
		.m0_wpoison        (),                                                   // (terminated),                         
		.m0_wdatachk       (),                                                   // (terminated),                         
		.m0_wtrace         (),                                                   // (terminated),                         
		.m0_btrace         (1'b0),                                               // (terminated),                         
		.m0_rpoison        (4'b0000),                                            // (terminated),                         
		.m0_rdatachk       (32'b00000000000000000000000000000000),               // (terminated),                         
		.m0_rtrace         (1'b0),                                               // (terminated),                         
		.m0_wid            (),                                                   // (terminated),                         
		.m0_ardomain       (),                                                   // (terminated),                         
		.m0_arsnoop        (),                                                   // (terminated),                         
		.m0_arbar          (),                                                   // (terminated),                         
		.m0_awdomain       (),                                                   // (terminated),                         
		.m0_awsnoop        (),                                                   // (terminated),                         
		.m0_awbar          (),                                                   // (terminated),                         
		.m0_awunique       (),                                                   // (terminated),                         
		.s0_awakeup        (1'b0),                                               // (terminated),                         
		.s0_awtrace        (1'b0),                                               // (terminated),                         
		.s0_artrace        (1'b0),                                               // (terminated),                         
		.s0_wpoison        (4'b0000),                                            // (terminated),                         
		.s0_wdatachk       (32'b00000000000000000000000000000000),               // (terminated),                         
		.s0_wtrace         (1'b0),                                               // (terminated),                         
		.s0_btrace         (),                                                   // (terminated),                         
		.s0_rpoison        (),                                                   // (terminated),                         
		.s0_rdatachk       (),                                                   // (terminated),                         
		.s0_rtrace         (),                                                   // (terminated),                         
		.s0_wid            (7'b0000000),                                         // (terminated),                         
		.s0_ardomain       (2'b00),                                              // (terminated),                         
		.s0_arsnoop        (4'b0000),                                            // (terminated),                         
		.s0_arbar          (2'b00),                                              // (terminated),                         
		.s0_awdomain       (2'b00),                                              // (terminated),                         
		.s0_awsnoop        (3'b000),                                             // (terminated),                         
		.s0_awbar          (2'b00),                                              // (terminated),                         
		.s0_awunique       (1'b0)                                                // (terminated),                         
	);

	platform_intel_agilex_hps_1_altera_merlin_axi_translator_1974_xfkiwxi #(
		.USE_S0_AWID                       (1),
		.USE_S0_AWREGION                   (1),
		.USE_M0_AWREGION                   (0),
		.USE_S0_AWLEN                      (1),
		.USE_S0_AWSIZE                     (1),
		.USE_S0_AWBURST                    (1),
		.USE_S0_AWLOCK                     (1),
		.USE_M0_AWLOCK                     (1),
		.USE_S0_AWCACHE                    (1),
		.USE_M0_AWCACHE                    (0),
		.USE_M0_AWPROT                     (1),
		.USE_S0_AWPROT                     (1),
		.USE_S0_AWQOS                      (1),
		.USE_M0_AWQOS                      (1),
		.USE_S0_WSTRB                      (1),
		.USE_M0_WLAST                      (1),
		.USE_S0_WLAST                      (1),
		.USE_S0_BID                        (1),
		.USE_S0_BRESP                      (1),
		.USE_M0_BRESP                      (1),
		.USE_S0_ARID                       (1),
		.USE_S0_ARREGION                   (1),
		.USE_M0_ARREGION                   (0),
		.USE_S0_ARLEN                      (1),
		.USE_S0_ARSIZE                     (1),
		.USE_S0_ARBURST                    (1),
		.USE_S0_ARLOCK                     (1),
		.USE_M0_ARLOCK                     (1),
		.USE_M0_ARCACHE                    (0),
		.USE_M0_ARQOS                      (1),
		.USE_M0_ARPROT                     (1),
		.USE_S0_ARPROT                     (1),
		.USE_S0_ARCACHE                    (1),
		.USE_S0_ARQOS                      (1),
		.USE_S0_RID                        (1),
		.USE_S0_RRESP                      (1),
		.USE_M0_RRESP                      (1),
		.USE_S0_RLAST                      (1),
		.USE_S0_AWUSER                     (1),
		.USE_S0_ARUSER                     (1),
		.USE_S0_WUSER                      (1),
		.USE_S0_RUSER                      (1),
		.USE_S0_BUSER                      (1),
		.USE_M0_AWUSER                     (1),
		.USE_M0_ARUSER                     (1),
		.USE_M0_WUSER                      (1),
		.USE_M0_RUSER                      (1),
		.USE_M0_BUSER                      (0),
		.USE_M0_AWUSER_ADDRCHK             (0),
		.USE_M0_AWUSER_SAI                 (0),
		.USE_M0_ARUSER_ADDRCHK             (0),
		.USE_M0_ARUSER_SAI                 (0),
		.USE_M0_WUSER_DATACHK              (0),
		.USE_M0_WUSER_POISON               (0),
		.USE_M0_RUSER_DATACHK              (0),
		.USE_M0_RUSER_POISON               (0),
		.USE_M0_WUSER_DATA                 (0),
		.USE_M0_RUSER_DATA                 (0),
		.USE_M0_AWAKEUP                    (0),
		.USE_M0_WPOISON                    (0),
		.USE_M0_RPOISON                    (0),
		.USE_M0_AWTRACE                    (0),
		.USE_M0_ARTRACE                    (0),
		.USE_M0_WTRACE                     (0),
		.USE_M0_BTRACE                     (0),
		.USE_M0_RTRACE                     (0),
		.USE_M0_WDATACHK                   (0),
		.USE_M0_RDATACHK                   (0),
		.USE_M0_AWUNIQUE                   (0),
		.USE_S0_AWAKEUP                    (0),
		.USE_S0_WPOISON                    (0),
		.USE_S0_RPOISON                    (0),
		.USE_S0_AWTRACE                    (0),
		.USE_S0_ARTRACE                    (0),
		.USE_S0_WTRACE                     (0),
		.USE_S0_BTRACE                     (0),
		.USE_S0_RTRACE                     (0),
		.USE_S0_WDATACHK                   (0),
		.USE_S0_RDATACHK                   (0),
		.USE_S0_AWUSER_ADDRCHK             (1),
		.USE_S0_AWUSER_SAI                 (1),
		.USE_S0_ARUSER_ADDRCHK             (1),
		.USE_S0_ARUSER_SAI                 (1),
		.USE_S0_WUSER_DATACHK              (1),
		.USE_S0_WUSER_POISON               (1),
		.USE_S0_RUSER_DATACHK              (1),
		.USE_S0_WUSER_DATA                 (1),
		.USE_S0_RUSER_DATA                 (1),
		.USE_S0_RUSER_POISON               (1),
		.USE_S0_AWUNIQUE                   (1),
		.M0_ID_WIDTH                       (7),
		.DATA_WIDTH                        (256),
		.M0_SAI_WIDTH                      (1),
		.S0_SAI_WIDTH                      (1),
		.USER_DATA_WIDTH                   (1),
		.M0_USER_ADDRCHK_WIDTH             (1),
		.S0_USER_ADDRCHK_WIDTH             (1),
		.S0_ID_WIDTH                       (7),
		.M0_ADDR_WIDTH                     (44),
		.S0_WRITE_ADDR_USER_WIDTH          (11),
		.S0_READ_ADDR_USER_WIDTH           (11),
		.M0_WRITE_ADDR_USER_WIDTH          (11),
		.M0_READ_ADDR_USER_WIDTH           (11),
		.S0_WRITE_DATA_USER_WIDTH          (32),
		.S0_WRITE_RESPONSE_DATA_USER_WIDTH (32),
		.S0_READ_DATA_USER_WIDTH           (32),
		.M0_WRITE_DATA_USER_WIDTH          (32),
		.M0_WRITE_RESPONSE_DATA_USER_WIDTH (1),
		.M0_READ_DATA_USER_WIDTH           (32),
		.S0_ADDR_WIDTH                     (44),
		.M0_AXI_VERSION                    ("AXI4"),
		.M0_BURST_LENGTH_WIDTH             (8),
		.S0_BURST_LENGTH_WIDTH             (8),
		.M0_LOCK_WIDTH                     (1),
		.S0_LOCK_WIDTH                     (1),
		.S0_AXI_VERSION                    ("AXI4"),
		.ACE_LITE_SUPPORT                  (0),
		.REGENERATE_ADDRCHK                (0),
		.ROLE_BASED_USER                   (0)
	) iniu_0_altera_axi_slave_translator (
		.aclk              (fpga_interfaces_h2n_ch0_axi_clk_clk),                //   input,    width = 1,       clk.clk
		.aresetn           (~iniu_0_reset_reset_bridge_in_reset_reset),          //   input,    width = 1, clk_reset.reset_n
		.m0_awid           (iniu_0_altera_axi_slave_awid),                       //  output,    width = 7,        m0.awid
		.m0_awaddr         (iniu_0_altera_axi_slave_awaddr),                     //  output,   width = 44,          .awaddr
		.m0_awlen          (iniu_0_altera_axi_slave_awlen),                      //  output,    width = 8,          .awlen
		.m0_awsize         (iniu_0_altera_axi_slave_awsize),                     //  output,    width = 3,          .awsize
		.m0_awburst        (iniu_0_altera_axi_slave_awburst),                    //  output,    width = 2,          .awburst
		.m0_awlock         (iniu_0_altera_axi_slave_awlock),                     //  output,    width = 1,          .awlock
		.m0_awprot         (iniu_0_altera_axi_slave_awprot),                     //  output,    width = 3,          .awprot
		.m0_awuser         (iniu_0_altera_axi_slave_awuser),                     //  output,   width = 11,          .awuser
		.m0_awqos          (iniu_0_altera_axi_slave_awqos),                      //  output,    width = 4,          .awqos
		.m0_awvalid        (iniu_0_altera_axi_slave_awvalid),                    //  output,    width = 1,          .awvalid
		.m0_awready        (iniu_0_altera_axi_slave_awready),                    //   input,    width = 1,          .awready
		.m0_wdata          (iniu_0_altera_axi_slave_wdata),                      //  output,  width = 256,          .wdata
		.m0_wstrb          (iniu_0_altera_axi_slave_wstrb),                      //  output,   width = 32,          .wstrb
		.m0_wlast          (iniu_0_altera_axi_slave_wlast),                      //  output,    width = 1,          .wlast
		.m0_wvalid         (iniu_0_altera_axi_slave_wvalid),                     //  output,    width = 1,          .wvalid
		.m0_wuser          (iniu_0_altera_axi_slave_wuser),                      //  output,   width = 32,          .wuser
		.m0_wready         (iniu_0_altera_axi_slave_wready),                     //   input,    width = 1,          .wready
		.m0_bid            (iniu_0_altera_axi_slave_bid),                        //   input,    width = 7,          .bid
		.m0_bresp          (iniu_0_altera_axi_slave_bresp),                      //   input,    width = 2,          .bresp
		.m0_bvalid         (iniu_0_altera_axi_slave_bvalid),                     //   input,    width = 1,          .bvalid
		.m0_bready         (iniu_0_altera_axi_slave_bready),                     //  output,    width = 1,          .bready
		.m0_arid           (iniu_0_altera_axi_slave_arid),                       //  output,    width = 7,          .arid
		.m0_araddr         (iniu_0_altera_axi_slave_araddr),                     //  output,   width = 44,          .araddr
		.m0_arlen          (iniu_0_altera_axi_slave_arlen),                      //  output,    width = 8,          .arlen
		.m0_arsize         (iniu_0_altera_axi_slave_arsize),                     //  output,    width = 3,          .arsize
		.m0_arburst        (iniu_0_altera_axi_slave_arburst),                    //  output,    width = 2,          .arburst
		.m0_arlock         (iniu_0_altera_axi_slave_arlock),                     //  output,    width = 1,          .arlock
		.m0_arprot         (iniu_0_altera_axi_slave_arprot),                     //  output,    width = 3,          .arprot
		.m0_aruser         (iniu_0_altera_axi_slave_aruser),                     //  output,   width = 11,          .aruser
		.m0_arqos          (iniu_0_altera_axi_slave_arqos),                      //  output,    width = 4,          .arqos
		.m0_arvalid        (iniu_0_altera_axi_slave_arvalid),                    //  output,    width = 1,          .arvalid
		.m0_arready        (iniu_0_altera_axi_slave_arready),                    //   input,    width = 1,          .arready
		.m0_rid            (iniu_0_altera_axi_slave_rid),                        //   input,    width = 7,          .rid
		.m0_rdata          (iniu_0_altera_axi_slave_rdata),                      //   input,  width = 256,          .rdata
		.m0_rresp          (iniu_0_altera_axi_slave_rresp),                      //   input,    width = 2,          .rresp
		.m0_rlast          (iniu_0_altera_axi_slave_rlast),                      //   input,    width = 1,          .rlast
		.m0_rvalid         (iniu_0_altera_axi_slave_rvalid),                     //   input,    width = 1,          .rvalid
		.m0_rready         (iniu_0_altera_axi_slave_rready),                     //  output,    width = 1,          .rready
		.m0_ruser          (iniu_0_altera_axi_slave_ruser),                      //   input,   width = 32,          .ruser
		.s0_awid           (fpga_interfaces_h2n_ch0_axi_translator_m0_awid),     //   input,    width = 7,        s0.awid
		.s0_awaddr         (fpga_interfaces_h2n_ch0_axi_translator_m0_awaddr),   //   input,   width = 44,          .awaddr
		.s0_awlen          (fpga_interfaces_h2n_ch0_axi_translator_m0_awlen),    //   input,    width = 8,          .awlen
		.s0_awsize         (fpga_interfaces_h2n_ch0_axi_translator_m0_awsize),   //   input,    width = 3,          .awsize
		.s0_awburst        (fpga_interfaces_h2n_ch0_axi_translator_m0_awburst),  //   input,    width = 2,          .awburst
		.s0_awlock         (fpga_interfaces_h2n_ch0_axi_translator_m0_awlock),   //   input,    width = 1,          .awlock
		.s0_awcache        (fpga_interfaces_h2n_ch0_axi_translator_m0_awcache),  //   input,    width = 4,          .awcache
		.s0_awprot         (fpga_interfaces_h2n_ch0_axi_translator_m0_awprot),   //   input,    width = 3,          .awprot
		.s0_awuser         (fpga_interfaces_h2n_ch0_axi_translator_m0_awuser),   //   input,   width = 11,          .awuser
		.s0_awqos          (fpga_interfaces_h2n_ch0_axi_translator_m0_awqos),    //   input,    width = 4,          .awqos
		.s0_awregion       (fpga_interfaces_h2n_ch0_axi_translator_m0_awregion), //   input,    width = 4,          .awregion
		.s0_awvalid        (fpga_interfaces_h2n_ch0_axi_translator_m0_awvalid),  //   input,    width = 1,          .awvalid
		.s0_awready        (fpga_interfaces_h2n_ch0_axi_translator_m0_awready),  //  output,    width = 1,          .awready
		.s0_wdata          (fpga_interfaces_h2n_ch0_axi_translator_m0_wdata),    //   input,  width = 256,          .wdata
		.s0_wstrb          (fpga_interfaces_h2n_ch0_axi_translator_m0_wstrb),    //   input,   width = 32,          .wstrb
		.s0_wlast          (fpga_interfaces_h2n_ch0_axi_translator_m0_wlast),    //   input,    width = 1,          .wlast
		.s0_wvalid         (fpga_interfaces_h2n_ch0_axi_translator_m0_wvalid),   //   input,    width = 1,          .wvalid
		.s0_wuser          (fpga_interfaces_h2n_ch0_axi_translator_m0_wuser),    //   input,   width = 32,          .wuser
		.s0_wready         (fpga_interfaces_h2n_ch0_axi_translator_m0_wready),   //  output,    width = 1,          .wready
		.s0_bid            (fpga_interfaces_h2n_ch0_axi_translator_m0_bid),      //  output,    width = 7,          .bid
		.s0_bresp          (fpga_interfaces_h2n_ch0_axi_translator_m0_bresp),    //  output,    width = 2,          .bresp
		.s0_buser          (fpga_interfaces_h2n_ch0_axi_translator_m0_buser),    //  output,   width = 32,          .buser
		.s0_bvalid         (fpga_interfaces_h2n_ch0_axi_translator_m0_bvalid),   //  output,    width = 1,          .bvalid
		.s0_bready         (fpga_interfaces_h2n_ch0_axi_translator_m0_bready),   //   input,    width = 1,          .bready
		.s0_arid           (fpga_interfaces_h2n_ch0_axi_translator_m0_arid),     //   input,    width = 7,          .arid
		.s0_araddr         (fpga_interfaces_h2n_ch0_axi_translator_m0_araddr),   //   input,   width = 44,          .araddr
		.s0_arlen          (fpga_interfaces_h2n_ch0_axi_translator_m0_arlen),    //   input,    width = 8,          .arlen
		.s0_arsize         (fpga_interfaces_h2n_ch0_axi_translator_m0_arsize),   //   input,    width = 3,          .arsize
		.s0_arburst        (fpga_interfaces_h2n_ch0_axi_translator_m0_arburst),  //   input,    width = 2,          .arburst
		.s0_arlock         (fpga_interfaces_h2n_ch0_axi_translator_m0_arlock),   //   input,    width = 1,          .arlock
		.s0_arcache        (fpga_interfaces_h2n_ch0_axi_translator_m0_arcache),  //   input,    width = 4,          .arcache
		.s0_arprot         (fpga_interfaces_h2n_ch0_axi_translator_m0_arprot),   //   input,    width = 3,          .arprot
		.s0_aruser         (fpga_interfaces_h2n_ch0_axi_translator_m0_aruser),   //   input,   width = 11,          .aruser
		.s0_arqos          (fpga_interfaces_h2n_ch0_axi_translator_m0_arqos),    //   input,    width = 4,          .arqos
		.s0_arregion       (fpga_interfaces_h2n_ch0_axi_translator_m0_arregion), //   input,    width = 4,          .arregion
		.s0_arvalid        (fpga_interfaces_h2n_ch0_axi_translator_m0_arvalid),  //   input,    width = 1,          .arvalid
		.s0_arready        (fpga_interfaces_h2n_ch0_axi_translator_m0_arready),  //  output,    width = 1,          .arready
		.s0_rid            (fpga_interfaces_h2n_ch0_axi_translator_m0_rid),      //  output,    width = 7,          .rid
		.s0_rdata          (fpga_interfaces_h2n_ch0_axi_translator_m0_rdata),    //  output,  width = 256,          .rdata
		.s0_rresp          (fpga_interfaces_h2n_ch0_axi_translator_m0_rresp),    //  output,    width = 2,          .rresp
		.s0_rlast          (fpga_interfaces_h2n_ch0_axi_translator_m0_rlast),    //  output,    width = 1,          .rlast
		.s0_rvalid         (fpga_interfaces_h2n_ch0_axi_translator_m0_rvalid),   //  output,    width = 1,          .rvalid
		.s0_rready         (fpga_interfaces_h2n_ch0_axi_translator_m0_rready),   //   input,    width = 1,          .rready
		.s0_ruser          (fpga_interfaces_h2n_ch0_axi_translator_m0_ruser),    //  output,   width = 32,          .ruser
		.m0_awcache        (),                                                   // (terminated),                         
		.m0_awuser_addrchk (),                                                   // (terminated),                         
		.m0_awuser_sai     (),                                                   // (terminated),                         
		.m0_awregion       (),                                                   // (terminated),                         
		.m0_wuser_datachk  (),                                                   // (terminated),                         
		.m0_wuser_data     (),                                                   // (terminated),                         
		.m0_wuser_poison   (),                                                   // (terminated),                         
		.m0_buser          (1'b0),                                               // (terminated),                         
		.m0_arcache        (),                                                   // (terminated),                         
		.m0_aruser_addrchk (),                                                   // (terminated),                         
		.m0_aruser_sai     (),                                                   // (terminated),                         
		.m0_arregion       (),                                                   // (terminated),                         
		.m0_ruser_datachk  (32'b00000000000000000000000000000000),               // (terminated),                         
		.m0_ruser_data     (1'b0),                                               // (terminated),                         
		.m0_ruser_poison   (4'b0000),                                            // (terminated),                         
		.s0_awuser_addrchk (1'b0),                                               // (terminated),                         
		.s0_awuser_sai     (1'b0),                                               // (terminated),                         
		.s0_wuser_datachk  (32'b00000000000000000000000000000000),               // (terminated),                         
		.s0_wuser_data     (1'b0),                                               // (terminated),                         
		.s0_wuser_poison   (4'b0000),                                            // (terminated),                         
		.s0_aruser_addrchk (1'b0),                                               // (terminated),                         
		.s0_aruser_sai     (1'b0),                                               // (terminated),                         
		.s0_ruser_datachk  (),                                                   // (terminated),                         
		.s0_ruser_data     (),                                                   // (terminated),                         
		.s0_ruser_poison   (),                                                   // (terminated),                         
		.m0_awakeup        (),                                                   // (terminated),                         
		.m0_awtrace        (),                                                   // (terminated),                         
		.m0_artrace        (),                                                   // (terminated),                         
		.m0_wpoison        (),                                                   // (terminated),                         
		.m0_wdatachk       (),                                                   // (terminated),                         
		.m0_wtrace         (),                                                   // (terminated),                         
		.m0_btrace         (1'b0),                                               // (terminated),                         
		.m0_rpoison        (4'b0000),                                            // (terminated),                         
		.m0_rdatachk       (32'b00000000000000000000000000000000),               // (terminated),                         
		.m0_rtrace         (1'b0),                                               // (terminated),                         
		.m0_wid            (),                                                   // (terminated),                         
		.m0_ardomain       (),                                                   // (terminated),                         
		.m0_arsnoop        (),                                                   // (terminated),                         
		.m0_arbar          (),                                                   // (terminated),                         
		.m0_awdomain       (),                                                   // (terminated),                         
		.m0_awsnoop        (),                                                   // (terminated),                         
		.m0_awbar          (),                                                   // (terminated),                         
		.m0_awunique       (),                                                   // (terminated),                         
		.s0_awakeup        (1'b0),                                               // (terminated),                         
		.s0_awtrace        (1'b0),                                               // (terminated),                         
		.s0_artrace        (1'b0),                                               // (terminated),                         
		.s0_wpoison        (4'b0000),                                            // (terminated),                         
		.s0_wdatachk       (32'b00000000000000000000000000000000),               // (terminated),                         
		.s0_wtrace         (1'b0),                                               // (terminated),                         
		.s0_btrace         (),                                                   // (terminated),                         
		.s0_rpoison        (),                                                   // (terminated),                         
		.s0_rdatachk       (),                                                   // (terminated),                         
		.s0_rtrace         (),                                                   // (terminated),                         
		.s0_wid            (7'b0000000),                                         // (terminated),                         
		.s0_ardomain       (2'b00),                                              // (terminated),                         
		.s0_arsnoop        (4'b0000),                                            // (terminated),                         
		.s0_arbar          (2'b00),                                              // (terminated),                         
		.s0_awdomain       (2'b00),                                              // (terminated),                         
		.s0_awsnoop        (3'b000),                                             // (terminated),                         
		.s0_awbar          (2'b00),                                              // (terminated),                         
		.s0_awunique       (1'b0)                                                // (terminated),                         
	);

endmodule
