// platform_altera_mm_interconnect_1920_zysovyq.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 25.1 129

`timescale 1 ps / 1 ps
module platform_altera_mm_interconnect_1920_zysovyq (
		input  wire [43:0]  address_extender_host2noc_expanded_master_address,                                      //                                        address_extender_host2noc_expanded_master.address
		output wire         address_extender_host2noc_expanded_master_waitrequest,                                  //                                                                                 .waitrequest
		input  wire [0:0]   address_extender_host2noc_expanded_master_burstcount,                                   //                                                                                 .burstcount
		input  wire [15:0]  address_extender_host2noc_expanded_master_byteenable,                                   //                                                                                 .byteenable
		input  wire         address_extender_host2noc_expanded_master_read,                                         //                                                                                 .read
		output wire [127:0] address_extender_host2noc_expanded_master_readdata,                                     //                                                                                 .readdata
		output wire         address_extender_host2noc_expanded_master_readdatavalid,                                //                                                                                 .readdatavalid
		input  wire         address_extender_host2noc_expanded_master_write,                                        //                                                                                 .write
		input  wire [127:0] address_extender_host2noc_expanded_master_writedata,                                    //                                                                                 .writedata
		output wire [43:0]  ccv_hps_to_noc_s0_address,                                                              //                                                                ccv_hps_to_noc_s0.address
		output wire         ccv_hps_to_noc_s0_write,                                                                //                                                                                 .write
		output wire         ccv_hps_to_noc_s0_read,                                                                 //                                                                                 .read
		input  wire [127:0] ccv_hps_to_noc_s0_readdata,                                                             //                                                                                 .readdata
		output wire [127:0] ccv_hps_to_noc_s0_writedata,                                                            //                                                                                 .writedata
		output wire [4:0]   ccv_hps_to_noc_s0_burstcount,                                                           //                                                                                 .burstcount
		output wire [15:0]  ccv_hps_to_noc_s0_byteenable,                                                           //                                                                                 .byteenable
		input  wire         ccv_hps_to_noc_s0_readdatavalid,                                                        //                                                                                 .readdatavalid
		input  wire         ccv_hps_to_noc_s0_waitrequest,                                                          //                                                                                 .waitrequest
		output wire         ccv_hps_to_noc_s0_debugaccess,                                                          //                                                                                 .debugaccess
		input  wire [1:0]   ccv_hps_to_noc_s0_response,                                                             //                                                                                 .response
		input  wire         ccv_hps_to_noc_s0_writeresponsevalid,                                                   //                                                                                 .writeresponsevalid
		input  wire         address_extender_host2noc_reset_reset_bridge_in_reset_reset,                            //                            address_extender_host2noc_reset_reset_bridge_in_reset.reset,             Reset Input
		input  wire         address_extender_host2noc_expanded_master_translator_reset_reset_bridge_in_reset_reset, // address_extender_host2noc_expanded_master_translator_reset_reset_bridge_in_reset.reset,             Reset Input
		input  wire         sysclk_in_out_clk_clk                                                                   //                                                                sysclk_in_out_clk.clk,               Clock Input
	);

	wire          address_extender_host2noc_expanded_master_translator_avalon_universal_master_0_waitrequest;   // address_extender_host2noc_expanded_master_agent:av_waitrequest -> address_extender_host2noc_expanded_master_translator:uav_waitrequest
	wire  [127:0] address_extender_host2noc_expanded_master_translator_avalon_universal_master_0_readdata;      // address_extender_host2noc_expanded_master_agent:av_readdata -> address_extender_host2noc_expanded_master_translator:uav_readdata
	wire          address_extender_host2noc_expanded_master_translator_avalon_universal_master_0_debugaccess;   // address_extender_host2noc_expanded_master_translator:uav_debugaccess -> address_extender_host2noc_expanded_master_agent:av_debugaccess
	wire   [43:0] address_extender_host2noc_expanded_master_translator_avalon_universal_master_0_address;       // address_extender_host2noc_expanded_master_translator:uav_address -> address_extender_host2noc_expanded_master_agent:av_address
	wire          address_extender_host2noc_expanded_master_translator_avalon_universal_master_0_read;          // address_extender_host2noc_expanded_master_translator:uav_read -> address_extender_host2noc_expanded_master_agent:av_read
	wire   [15:0] address_extender_host2noc_expanded_master_translator_avalon_universal_master_0_byteenable;    // address_extender_host2noc_expanded_master_translator:uav_byteenable -> address_extender_host2noc_expanded_master_agent:av_byteenable
	wire          address_extender_host2noc_expanded_master_translator_avalon_universal_master_0_readdatavalid; // address_extender_host2noc_expanded_master_agent:av_readdatavalid -> address_extender_host2noc_expanded_master_translator:uav_readdatavalid
	wire          address_extender_host2noc_expanded_master_translator_avalon_universal_master_0_lock;          // address_extender_host2noc_expanded_master_translator:uav_lock -> address_extender_host2noc_expanded_master_agent:av_lock
	wire          address_extender_host2noc_expanded_master_translator_avalon_universal_master_0_write;         // address_extender_host2noc_expanded_master_translator:uav_write -> address_extender_host2noc_expanded_master_agent:av_write
	wire  [127:0] address_extender_host2noc_expanded_master_translator_avalon_universal_master_0_writedata;     // address_extender_host2noc_expanded_master_translator:uav_writedata -> address_extender_host2noc_expanded_master_agent:av_writedata
	wire    [4:0] address_extender_host2noc_expanded_master_translator_avalon_universal_master_0_burstcount;    // address_extender_host2noc_expanded_master_translator:uav_burstcount -> address_extender_host2noc_expanded_master_agent:av_burstcount
	wire          rsp_mux_src_valid;                                                                            // rsp_mux:src_valid -> address_extender_host2noc_expanded_master_agent:rp_valid
	wire  [254:0] rsp_mux_src_data;                                                                             // rsp_mux:src_data -> address_extender_host2noc_expanded_master_agent:rp_data
	wire          rsp_mux_src_ready;                                                                            // address_extender_host2noc_expanded_master_agent:rp_ready -> rsp_mux:src_ready
	wire    [0:0] rsp_mux_src_channel;                                                                          // rsp_mux:src_channel -> address_extender_host2noc_expanded_master_agent:rp_channel
	wire          rsp_mux_src_startofpacket;                                                                    // rsp_mux:src_startofpacket -> address_extender_host2noc_expanded_master_agent:rp_startofpacket
	wire          rsp_mux_src_endofpacket;                                                                      // rsp_mux:src_endofpacket -> address_extender_host2noc_expanded_master_agent:rp_endofpacket
	wire          ccv_hps_to_noc_s0_agent_m0_debugaccess;                                                       // ccv_hps_to_noc_s0_agent:m0_debugaccess -> ccv_hps_to_noc_s0_translator:uav_debugaccess
	wire   [43:0] ccv_hps_to_noc_s0_agent_m0_address;                                                           // ccv_hps_to_noc_s0_agent:m0_address -> ccv_hps_to_noc_s0_translator:uav_address
	wire   [15:0] ccv_hps_to_noc_s0_agent_m0_byteenable;                                                        // ccv_hps_to_noc_s0_agent:m0_byteenable -> ccv_hps_to_noc_s0_translator:uav_byteenable
	wire          ccv_hps_to_noc_s0_agent_m0_read;                                                              // ccv_hps_to_noc_s0_agent:m0_read -> ccv_hps_to_noc_s0_translator:uav_read
	wire          ccv_hps_to_noc_s0_agent_m0_readdatavalid;                                                     // ccv_hps_to_noc_s0_translator:uav_readdatavalid -> ccv_hps_to_noc_s0_agent:m0_readdatavalid
	wire  [127:0] ccv_hps_to_noc_s0_agent_m0_readdata;                                                          // ccv_hps_to_noc_s0_translator:uav_readdata -> ccv_hps_to_noc_s0_agent:m0_readdata
	wire          ccv_hps_to_noc_s0_agent_m0_waitrequest;                                                       // ccv_hps_to_noc_s0_translator:uav_waitrequest -> ccv_hps_to_noc_s0_agent:m0_waitrequest
	wire    [1:0] ccv_hps_to_noc_s0_agent_m0_response;                                                          // ccv_hps_to_noc_s0_translator:uav_response -> ccv_hps_to_noc_s0_agent:m0_response
	wire          ccv_hps_to_noc_s0_agent_m0_lock;                                                              // ccv_hps_to_noc_s0_agent:m0_lock -> ccv_hps_to_noc_s0_translator:uav_lock
	wire  [127:0] ccv_hps_to_noc_s0_agent_m0_writedata;                                                         // ccv_hps_to_noc_s0_agent:m0_writedata -> ccv_hps_to_noc_s0_translator:uav_writedata
	wire          ccv_hps_to_noc_s0_agent_m0_write;                                                             // ccv_hps_to_noc_s0_agent:m0_write -> ccv_hps_to_noc_s0_translator:uav_write
	wire          ccv_hps_to_noc_s0_agent_m0_writeresponsevalid;                                                // ccv_hps_to_noc_s0_translator:uav_writeresponsevalid -> ccv_hps_to_noc_s0_agent:m0_writeresponsevalid
	wire    [8:0] ccv_hps_to_noc_s0_agent_m0_burstcount;                                                        // ccv_hps_to_noc_s0_agent:m0_burstcount -> ccv_hps_to_noc_s0_translator:uav_burstcount
	wire          ccv_hps_to_noc_s0_agent_rf_source_valid;                                                      // ccv_hps_to_noc_s0_agent:rf_source_valid -> ccv_hps_to_noc_s0_agent_rsp_fifo:in_valid
	wire  [255:0] ccv_hps_to_noc_s0_agent_rf_source_data;                                                       // ccv_hps_to_noc_s0_agent:rf_source_data -> ccv_hps_to_noc_s0_agent_rsp_fifo:in_data
	wire          ccv_hps_to_noc_s0_agent_rf_source_ready;                                                      // ccv_hps_to_noc_s0_agent_rsp_fifo:in_ready -> ccv_hps_to_noc_s0_agent:rf_source_ready
	wire          ccv_hps_to_noc_s0_agent_rf_source_startofpacket;                                              // ccv_hps_to_noc_s0_agent:rf_source_startofpacket -> ccv_hps_to_noc_s0_agent_rsp_fifo:in_startofpacket
	wire          ccv_hps_to_noc_s0_agent_rf_source_endofpacket;                                                // ccv_hps_to_noc_s0_agent:rf_source_endofpacket -> ccv_hps_to_noc_s0_agent_rsp_fifo:in_endofpacket
	wire          ccv_hps_to_noc_s0_agent_rsp_fifo_out_valid;                                                   // ccv_hps_to_noc_s0_agent_rsp_fifo:out_valid -> ccv_hps_to_noc_s0_agent:rf_sink_valid
	wire  [255:0] ccv_hps_to_noc_s0_agent_rsp_fifo_out_data;                                                    // ccv_hps_to_noc_s0_agent_rsp_fifo:out_data -> ccv_hps_to_noc_s0_agent:rf_sink_data
	wire          ccv_hps_to_noc_s0_agent_rsp_fifo_out_ready;                                                   // ccv_hps_to_noc_s0_agent:rf_sink_ready -> ccv_hps_to_noc_s0_agent_rsp_fifo:out_ready
	wire          ccv_hps_to_noc_s0_agent_rsp_fifo_out_startofpacket;                                           // ccv_hps_to_noc_s0_agent_rsp_fifo:out_startofpacket -> ccv_hps_to_noc_s0_agent:rf_sink_startofpacket
	wire          ccv_hps_to_noc_s0_agent_rsp_fifo_out_endofpacket;                                             // ccv_hps_to_noc_s0_agent_rsp_fifo:out_endofpacket -> ccv_hps_to_noc_s0_agent:rf_sink_endofpacket
	wire          ccv_hps_to_noc_s0_agent_rdata_fifo_src_valid;                                                 // ccv_hps_to_noc_s0_agent:rdata_fifo_src_valid -> ccv_hps_to_noc_s0_agent:rdata_fifo_sink_valid
	wire  [129:0] ccv_hps_to_noc_s0_agent_rdata_fifo_src_data;                                                  // ccv_hps_to_noc_s0_agent:rdata_fifo_src_data -> ccv_hps_to_noc_s0_agent:rdata_fifo_sink_data
	wire          ccv_hps_to_noc_s0_agent_rdata_fifo_src_ready;                                                 // ccv_hps_to_noc_s0_agent:rdata_fifo_sink_ready -> ccv_hps_to_noc_s0_agent:rdata_fifo_src_ready
	wire          cmd_mux_src_valid;                                                                            // cmd_mux:src_valid -> ccv_hps_to_noc_s0_agent:cp_valid
	wire  [254:0] cmd_mux_src_data;                                                                             // cmd_mux:src_data -> ccv_hps_to_noc_s0_agent:cp_data
	wire          cmd_mux_src_ready;                                                                            // ccv_hps_to_noc_s0_agent:cp_ready -> cmd_mux:src_ready
	wire    [0:0] cmd_mux_src_channel;                                                                          // cmd_mux:src_channel -> ccv_hps_to_noc_s0_agent:cp_channel
	wire          cmd_mux_src_startofpacket;                                                                    // cmd_mux:src_startofpacket -> ccv_hps_to_noc_s0_agent:cp_startofpacket
	wire          cmd_mux_src_endofpacket;                                                                      // cmd_mux:src_endofpacket -> ccv_hps_to_noc_s0_agent:cp_endofpacket
	wire          address_extender_host2noc_expanded_master_agent_cp_valid;                                     // address_extender_host2noc_expanded_master_agent:cp_valid -> router:sink_valid
	wire  [254:0] address_extender_host2noc_expanded_master_agent_cp_data;                                      // address_extender_host2noc_expanded_master_agent:cp_data -> router:sink_data
	wire          address_extender_host2noc_expanded_master_agent_cp_ready;                                     // router:sink_ready -> address_extender_host2noc_expanded_master_agent:cp_ready
	wire          address_extender_host2noc_expanded_master_agent_cp_startofpacket;                             // address_extender_host2noc_expanded_master_agent:cp_startofpacket -> router:sink_startofpacket
	wire          address_extender_host2noc_expanded_master_agent_cp_endofpacket;                               // address_extender_host2noc_expanded_master_agent:cp_endofpacket -> router:sink_endofpacket
	wire          router_src_valid;                                                                             // router:src_valid -> cmd_demux:sink_valid
	wire  [254:0] router_src_data;                                                                              // router:src_data -> cmd_demux:sink_data
	wire          router_src_ready;                                                                             // cmd_demux:sink_ready -> router:src_ready
	wire    [0:0] router_src_channel;                                                                           // router:src_channel -> cmd_demux:sink_channel
	wire          router_src_startofpacket;                                                                     // router:src_startofpacket -> cmd_demux:sink_startofpacket
	wire          router_src_endofpacket;                                                                       // router:src_endofpacket -> cmd_demux:sink_endofpacket
	wire          ccv_hps_to_noc_s0_agent_rp_valid;                                                             // ccv_hps_to_noc_s0_agent:rp_valid -> router_001:sink_valid
	wire  [254:0] ccv_hps_to_noc_s0_agent_rp_data;                                                              // ccv_hps_to_noc_s0_agent:rp_data -> router_001:sink_data
	wire          ccv_hps_to_noc_s0_agent_rp_ready;                                                             // router_001:sink_ready -> ccv_hps_to_noc_s0_agent:rp_ready
	wire          ccv_hps_to_noc_s0_agent_rp_startofpacket;                                                     // ccv_hps_to_noc_s0_agent:rp_startofpacket -> router_001:sink_startofpacket
	wire          ccv_hps_to_noc_s0_agent_rp_endofpacket;                                                       // ccv_hps_to_noc_s0_agent:rp_endofpacket -> router_001:sink_endofpacket
	wire          router_001_src_valid;                                                                         // router_001:src_valid -> rsp_demux:sink_valid
	wire  [254:0] router_001_src_data;                                                                          // router_001:src_data -> rsp_demux:sink_data
	wire          router_001_src_ready;                                                                         // rsp_demux:sink_ready -> router_001:src_ready
	wire    [0:0] router_001_src_channel;                                                                       // router_001:src_channel -> rsp_demux:sink_channel
	wire          router_001_src_startofpacket;                                                                 // router_001:src_startofpacket -> rsp_demux:sink_startofpacket
	wire          router_001_src_endofpacket;                                                                   // router_001:src_endofpacket -> rsp_demux:sink_endofpacket
	wire          cmd_demux_src0_valid;                                                                         // cmd_demux:src0_valid -> cmd_mux:sink0_valid
	wire  [254:0] cmd_demux_src0_data;                                                                          // cmd_demux:src0_data -> cmd_mux:sink0_data
	wire          cmd_demux_src0_ready;                                                                         // cmd_mux:sink0_ready -> cmd_demux:src0_ready
	wire    [0:0] cmd_demux_src0_channel;                                                                       // cmd_demux:src0_channel -> cmd_mux:sink0_channel
	wire          cmd_demux_src0_startofpacket;                                                                 // cmd_demux:src0_startofpacket -> cmd_mux:sink0_startofpacket
	wire          cmd_demux_src0_endofpacket;                                                                   // cmd_demux:src0_endofpacket -> cmd_mux:sink0_endofpacket
	wire          rsp_demux_src0_valid;                                                                         // rsp_demux:src0_valid -> rsp_mux:sink0_valid
	wire  [254:0] rsp_demux_src0_data;                                                                          // rsp_demux:src0_data -> rsp_mux:sink0_data
	wire          rsp_demux_src0_ready;                                                                         // rsp_mux:sink0_ready -> rsp_demux:src0_ready
	wire    [0:0] rsp_demux_src0_channel;                                                                       // rsp_demux:src0_channel -> rsp_mux:sink0_channel
	wire          rsp_demux_src0_startofpacket;                                                                 // rsp_demux:src0_startofpacket -> rsp_mux:sink0_startofpacket
	wire          rsp_demux_src0_endofpacket;                                                                   // rsp_demux:src0_endofpacket -> rsp_mux:sink0_endofpacket

	platform_altera_merlin_master_translator_193_lgcew2q #(
		.AV_ADDRESS_W                (44),
		.AV_DATA_W                   (128),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (16),
		.UAV_ADDRESS_W               (44),
		.UAV_BURSTCOUNT_W            (5),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (1),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (16),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0),
		.SYNC_RESET                  (1),
		.WAITREQUEST_ALLOWANCE       (0),
		.USE_OUTPUTENABLE            (0)
	) address_extender_host2noc_expanded_master_translator (
		.clk                    (sysclk_in_out_clk_clk),                                                                        //   input,    width = 1,                       clk.clk
		.reset                  (address_extender_host2noc_expanded_master_translator_reset_reset_bridge_in_reset_reset),       //   input,    width = 1,                     reset.reset
		.uav_address            (address_extender_host2noc_expanded_master_translator_avalon_universal_master_0_address),       //  output,   width = 44, avalon_universal_master_0.address
		.uav_burstcount         (address_extender_host2noc_expanded_master_translator_avalon_universal_master_0_burstcount),    //  output,    width = 5,                          .burstcount
		.uav_read               (address_extender_host2noc_expanded_master_translator_avalon_universal_master_0_read),          //  output,    width = 1,                          .read
		.uav_write              (address_extender_host2noc_expanded_master_translator_avalon_universal_master_0_write),         //  output,    width = 1,                          .write
		.uav_waitrequest        (address_extender_host2noc_expanded_master_translator_avalon_universal_master_0_waitrequest),   //   input,    width = 1,                          .waitrequest
		.uav_readdatavalid      (address_extender_host2noc_expanded_master_translator_avalon_universal_master_0_readdatavalid), //   input,    width = 1,                          .readdatavalid
		.uav_byteenable         (address_extender_host2noc_expanded_master_translator_avalon_universal_master_0_byteenable),    //  output,   width = 16,                          .byteenable
		.uav_readdata           (address_extender_host2noc_expanded_master_translator_avalon_universal_master_0_readdata),      //   input,  width = 128,                          .readdata
		.uav_writedata          (address_extender_host2noc_expanded_master_translator_avalon_universal_master_0_writedata),     //  output,  width = 128,                          .writedata
		.uav_lock               (address_extender_host2noc_expanded_master_translator_avalon_universal_master_0_lock),          //  output,    width = 1,                          .lock
		.uav_debugaccess        (address_extender_host2noc_expanded_master_translator_avalon_universal_master_0_debugaccess),   //  output,    width = 1,                          .debugaccess
		.av_address             (address_extender_host2noc_expanded_master_address),                                            //   input,   width = 44,      avalon_anti_master_0.address
		.av_waitrequest         (address_extender_host2noc_expanded_master_waitrequest),                                        //  output,    width = 1,                          .waitrequest
		.av_burstcount          (address_extender_host2noc_expanded_master_burstcount),                                         //   input,    width = 1,                          .burstcount
		.av_byteenable          (address_extender_host2noc_expanded_master_byteenable),                                         //   input,   width = 16,                          .byteenable
		.av_read                (address_extender_host2noc_expanded_master_read),                                               //   input,    width = 1,                          .read
		.av_readdata            (address_extender_host2noc_expanded_master_readdata),                                           //  output,  width = 128,                          .readdata
		.av_readdatavalid       (address_extender_host2noc_expanded_master_readdatavalid),                                      //  output,    width = 1,                          .readdatavalid
		.av_write               (address_extender_host2noc_expanded_master_write),                                              //   input,    width = 1,                          .write
		.av_writedata           (address_extender_host2noc_expanded_master_writedata),                                          //   input,  width = 128,                          .writedata
		.av_beginbursttransfer  (1'b0),                                                                                         // (terminated),                                         
		.av_begintransfer       (1'b0),                                                                                         // (terminated),                                         
		.av_chipselect          (1'b0),                                                                                         // (terminated),                                         
		.av_lock                (1'b0),                                                                                         // (terminated),                                         
		.av_debugaccess         (1'b0),                                                                                         // (terminated),                                         
		.uav_outputenable       (1'b0),                                                                                         // (terminated),                                         
		.uav_clken              (),                                                                                             // (terminated),                                         
		.av_clken               (1'b1),                                                                                         // (terminated),                                         
		.uav_response           (2'b00),                                                                                        // (terminated),                                         
		.av_response            (),                                                                                             // (terminated),                                         
		.uav_writeresponsevalid (1'b0),                                                                                         // (terminated),                                         
		.av_writeresponsevalid  ()                                                                                              // (terminated),                                         
	);

	platform_altera_merlin_slave_translator_191_xg7rzxi #(
		.AV_ADDRESS_W                   (44),
		.AV_DATA_W                      (128),
		.UAV_DATA_W                     (128),
		.AV_BURSTCOUNT_W                (5),
		.AV_BYTEENABLE_W                (16),
		.UAV_BYTEENABLE_W               (16),
		.UAV_ADDRESS_W                  (44),
		.UAV_BURSTCOUNT_W               (9),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (1),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (1),
		.USE_WRITERESPONSE              (1),
		.AV_SYMBOLS_PER_WORD            (16),
		.AV_ADDRESS_SYMBOLS             (1),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0),
		.WAITREQUEST_ALLOWANCE          (0),
		.SYNC_RESET                     (1)
	) ccv_hps_to_noc_s0_translator (
		.clk                    (sysclk_in_out_clk_clk),                                                                  //   input,    width = 1,                      clk.clk
		.reset                  (address_extender_host2noc_expanded_master_translator_reset_reset_bridge_in_reset_reset), //   input,    width = 1,                    reset.reset
		.uav_address            (ccv_hps_to_noc_s0_agent_m0_address),                                                     //   input,   width = 44, avalon_universal_slave_0.address
		.uav_burstcount         (ccv_hps_to_noc_s0_agent_m0_burstcount),                                                  //   input,    width = 9,                         .burstcount
		.uav_read               (ccv_hps_to_noc_s0_agent_m0_read),                                                        //   input,    width = 1,                         .read
		.uav_write              (ccv_hps_to_noc_s0_agent_m0_write),                                                       //   input,    width = 1,                         .write
		.uav_waitrequest        (ccv_hps_to_noc_s0_agent_m0_waitrequest),                                                 //  output,    width = 1,                         .waitrequest
		.uav_readdatavalid      (ccv_hps_to_noc_s0_agent_m0_readdatavalid),                                               //  output,    width = 1,                         .readdatavalid
		.uav_byteenable         (ccv_hps_to_noc_s0_agent_m0_byteenable),                                                  //   input,   width = 16,                         .byteenable
		.uav_readdata           (ccv_hps_to_noc_s0_agent_m0_readdata),                                                    //  output,  width = 128,                         .readdata
		.uav_writedata          (ccv_hps_to_noc_s0_agent_m0_writedata),                                                   //   input,  width = 128,                         .writedata
		.uav_lock               (ccv_hps_to_noc_s0_agent_m0_lock),                                                        //   input,    width = 1,                         .lock
		.uav_debugaccess        (ccv_hps_to_noc_s0_agent_m0_debugaccess),                                                 //   input,    width = 1,                         .debugaccess
		.uav_response           (ccv_hps_to_noc_s0_agent_m0_response),                                                    //  output,    width = 2,                         .response
		.uav_writeresponsevalid (ccv_hps_to_noc_s0_agent_m0_writeresponsevalid),                                          //  output,    width = 1,                         .writeresponsevalid
		.av_address             (ccv_hps_to_noc_s0_address),                                                              //  output,   width = 44,      avalon_anti_slave_0.address
		.av_write               (ccv_hps_to_noc_s0_write),                                                                //  output,    width = 1,                         .write
		.av_read                (ccv_hps_to_noc_s0_read),                                                                 //  output,    width = 1,                         .read
		.av_readdata            (ccv_hps_to_noc_s0_readdata),                                                             //   input,  width = 128,                         .readdata
		.av_writedata           (ccv_hps_to_noc_s0_writedata),                                                            //  output,  width = 128,                         .writedata
		.av_burstcount          (ccv_hps_to_noc_s0_burstcount),                                                           //  output,    width = 5,                         .burstcount
		.av_byteenable          (ccv_hps_to_noc_s0_byteenable),                                                           //  output,   width = 16,                         .byteenable
		.av_readdatavalid       (ccv_hps_to_noc_s0_readdatavalid),                                                        //   input,    width = 1,                         .readdatavalid
		.av_waitrequest         (ccv_hps_to_noc_s0_waitrequest),                                                          //   input,    width = 1,                         .waitrequest
		.av_debugaccess         (ccv_hps_to_noc_s0_debugaccess),                                                          //  output,    width = 1,                         .debugaccess
		.av_response            (ccv_hps_to_noc_s0_response),                                                             //   input,    width = 2,                         .response
		.av_writeresponsevalid  (ccv_hps_to_noc_s0_writeresponsevalid),                                                   //   input,    width = 1,                         .writeresponsevalid
		.av_begintransfer       (),                                                                                       // (terminated),                                        
		.av_beginbursttransfer  (),                                                                                       // (terminated),                                        
		.av_writebyteenable     (),                                                                                       // (terminated),                                        
		.av_lock                (),                                                                                       // (terminated),                                        
		.av_chipselect          (),                                                                                       // (terminated),                                        
		.av_clken               (),                                                                                       // (terminated),                                        
		.uav_clken              (1'b0),                                                                                   // (terminated),                                        
		.av_outputenable        ()                                                                                        // (terminated),                                        
	);

	platform_altera_merlin_master_agent_1931_7uh3r5q #(
		.PKT_WUNIQUE               (236),
		.PKT_DOMAIN_H              (235),
		.PKT_DOMAIN_L              (234),
		.PKT_SNOOP_H               (233),
		.PKT_SNOOP_L               (230),
		.PKT_BARRIER_H             (229),
		.PKT_BARRIER_L             (228),
		.PKT_ORI_BURST_SIZE_H      (227),
		.PKT_ORI_BURST_SIZE_L      (225),
		.PKT_RESPONSE_STATUS_H     (224),
		.PKT_RESPONSE_STATUS_L     (223),
		.PKT_QOS_H                 (212),
		.PKT_QOS_L                 (212),
		.PKT_DATA_SIDEBAND_H       (210),
		.PKT_DATA_SIDEBAND_L       (210),
		.PKT_ADDR_SIDEBAND_H       (209),
		.PKT_ADDR_SIDEBAND_L       (209),
		.PKT_BURST_TYPE_H          (208),
		.PKT_BURST_TYPE_L          (207),
		.PKT_CACHE_H               (222),
		.PKT_CACHE_L               (219),
		.PKT_THREAD_ID_H           (215),
		.PKT_THREAD_ID_L           (215),
		.PKT_BURST_SIZE_H          (206),
		.PKT_BURST_SIZE_L          (204),
		.PKT_TRANS_EXCLUSIVE       (193),
		.PKT_TRANS_LOCK            (192),
		.PKT_BEGIN_BURST           (211),
		.PKT_PROTECTION_H          (218),
		.PKT_PROTECTION_L          (216),
		.PKT_BURSTWRAP_H           (203),
		.PKT_BURSTWRAP_L           (203),
		.PKT_BYTE_CNT_H            (202),
		.PKT_BYTE_CNT_L            (194),
		.PKT_ADDR_H                (187),
		.PKT_ADDR_L                (144),
		.PKT_TRANS_COMPRESSED_READ (188),
		.PKT_TRANS_POSTED          (189),
		.PKT_TRANS_WRITE           (190),
		.PKT_TRANS_READ            (191),
		.PKT_DATA_H                (127),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (143),
		.PKT_BYTEEN_L              (128),
		.PKT_SRC_ID_H              (213),
		.PKT_SRC_ID_L              (213),
		.PKT_DEST_ID_H             (214),
		.PKT_DEST_ID_L             (214),
		.PKT_POISON_H              (237),
		.PKT_POISON_L              (237),
		.PKT_DATACHK_H             (238),
		.PKT_DATACHK_L             (238),
		.PKT_ADDRCHK_H             (241),
		.PKT_ADDRCHK_L             (240),
		.PKT_SAI_H                 (242),
		.PKT_SAI_L                 (242),
		.PKT_USER_DATA_H           (239),
		.PKT_USER_DATA_L           (239),
		.PKT_ATRACE                (252),
		.PKT_TRACE                 (253),
		.PKT_AWAKEUP               (254),
		.ST_DATA_W                 (255),
		.ST_CHANNEL_W              (1),
		.AV_BURSTCOUNT_W           (5),
		.SUPPRESS_0_BYTEEN_RSP     (0),
		.ID                        (0),
		.BURSTWRAP_VALUE           (1),
		.CACHE_VALUE               (0),
		.SECURE_ACCESS_BIT         (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0),
		.DOMAIN_VALUE              (3),
		.BARRIER_VALUE             (0),
		.SNOOP_VALUE               (0),
		.WUNIQUE_VALUE             (0),
		.SYNC_RESET                (1),
		.USE_PKT_DATACHK           (0),
		.USE_PKT_ADDRCHK           (1),
		.ROLE_BASED_USER           (0),
		.ENABLE_AXI5               (0),
		.OPTIMIZED_READS_WITH_BE   (0)
	) address_extender_host2noc_expanded_master_agent (
		.clk                   (sysclk_in_out_clk_clk),                                                                        //   input,    width = 1,       clk.clk
		.reset                 (address_extender_host2noc_expanded_master_translator_reset_reset_bridge_in_reset_reset),       //   input,    width = 1, clk_reset.reset
		.av_address            (address_extender_host2noc_expanded_master_translator_avalon_universal_master_0_address),       //   input,   width = 44,        av.address
		.av_write              (address_extender_host2noc_expanded_master_translator_avalon_universal_master_0_write),         //   input,    width = 1,          .write
		.av_read               (address_extender_host2noc_expanded_master_translator_avalon_universal_master_0_read),          //   input,    width = 1,          .read
		.av_writedata          (address_extender_host2noc_expanded_master_translator_avalon_universal_master_0_writedata),     //   input,  width = 128,          .writedata
		.av_readdata           (address_extender_host2noc_expanded_master_translator_avalon_universal_master_0_readdata),      //  output,  width = 128,          .readdata
		.av_waitrequest        (address_extender_host2noc_expanded_master_translator_avalon_universal_master_0_waitrequest),   //  output,    width = 1,          .waitrequest
		.av_readdatavalid      (address_extender_host2noc_expanded_master_translator_avalon_universal_master_0_readdatavalid), //  output,    width = 1,          .readdatavalid
		.av_byteenable         (address_extender_host2noc_expanded_master_translator_avalon_universal_master_0_byteenable),    //   input,   width = 16,          .byteenable
		.av_burstcount         (address_extender_host2noc_expanded_master_translator_avalon_universal_master_0_burstcount),    //   input,    width = 5,          .burstcount
		.av_debugaccess        (address_extender_host2noc_expanded_master_translator_avalon_universal_master_0_debugaccess),   //   input,    width = 1,          .debugaccess
		.av_lock               (address_extender_host2noc_expanded_master_translator_avalon_universal_master_0_lock),          //   input,    width = 1,          .lock
		.cp_valid              (address_extender_host2noc_expanded_master_agent_cp_valid),                                     //  output,    width = 1,        cp.valid
		.cp_data               (address_extender_host2noc_expanded_master_agent_cp_data),                                      //  output,  width = 255,          .data
		.cp_startofpacket      (address_extender_host2noc_expanded_master_agent_cp_startofpacket),                             //  output,    width = 1,          .startofpacket
		.cp_endofpacket        (address_extender_host2noc_expanded_master_agent_cp_endofpacket),                               //  output,    width = 1,          .endofpacket
		.cp_ready              (address_extender_host2noc_expanded_master_agent_cp_ready),                                     //   input,    width = 1,          .ready
		.rp_valid              (rsp_mux_src_valid),                                                                            //   input,    width = 1,        rp.valid
		.rp_data               (rsp_mux_src_data),                                                                             //   input,  width = 255,          .data
		.rp_channel            (rsp_mux_src_channel),                                                                          //   input,    width = 1,          .channel
		.rp_startofpacket      (rsp_mux_src_startofpacket),                                                                    //   input,    width = 1,          .startofpacket
		.rp_endofpacket        (rsp_mux_src_endofpacket),                                                                      //   input,    width = 1,          .endofpacket
		.rp_ready              (rsp_mux_src_ready),                                                                            //  output,    width = 1,          .ready
		.av_response           (),                                                                                             // (terminated),                         
		.av_writeresponsevalid ()                                                                                              // (terminated),                         
	);

	platform_altera_merlin_slave_agent_1930_jxauz3i #(
		.PKT_ORI_BURST_SIZE_H      (227),
		.PKT_ORI_BURST_SIZE_L      (225),
		.PKT_RESPONSE_STATUS_H     (224),
		.PKT_RESPONSE_STATUS_L     (223),
		.PKT_BURST_SIZE_H          (206),
		.PKT_BURST_SIZE_L          (204),
		.PKT_TRANS_LOCK            (192),
		.PKT_BEGIN_BURST           (211),
		.PKT_PROTECTION_H          (218),
		.PKT_PROTECTION_L          (216),
		.PKT_BURSTWRAP_H           (203),
		.PKT_BURSTWRAP_L           (203),
		.PKT_BYTE_CNT_H            (202),
		.PKT_BYTE_CNT_L            (194),
		.PKT_ADDR_H                (187),
		.PKT_ADDR_L                (144),
		.PKT_TRANS_COMPRESSED_READ (188),
		.PKT_TRANS_POSTED          (189),
		.PKT_TRANS_WRITE           (190),
		.PKT_TRANS_READ            (191),
		.PKT_DATA_H                (127),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (143),
		.PKT_BYTEEN_L              (128),
		.PKT_SRC_ID_H              (213),
		.PKT_SRC_ID_L              (213),
		.PKT_DEST_ID_H             (214),
		.PKT_DEST_ID_L             (214),
		.PKT_POISON_H              (237),
		.PKT_POISON_L              (237),
		.PKT_DATACHK_H             (238),
		.PKT_DATACHK_L             (238),
		.PKT_SAI_H                 (242),
		.PKT_SAI_L                 (242),
		.PKT_ADDRCHK_H             (241),
		.PKT_ADDRCHK_L             (240),
		.PKT_USER_DATA_H           (239),
		.PKT_USER_DATA_L           (239),
		.PKT_ATRACE                (252),
		.PKT_TRACE                 (253),
		.PKT_AWAKEUP               (254),
		.PKT_SYMBOL_W              (8),
		.ST_CHANNEL_W              (1),
		.ST_DATA_W                 (255),
		.AVS_BURSTCOUNT_W          (9),
		.SUPPRESS_0_BYTEEN_CMD     (0),
		.USE_MEMORY_BLOCKS         (0),
		.PREVENT_FIFO_OVERFLOW     (1),
		.USE_READRESPONSE          (1),
		.USE_WRITERESPONSE         (1),
		.ECC_ENABLE                (0),
		.SYNC_RESET                (1),
		.USE_PKT_DATACHK           (0),
		.ROLE_BASED_USER           (0),
		.ENABLE_AXI5               (0)
	) ccv_hps_to_noc_s0_agent (
		.clk                     (sysclk_in_out_clk_clk),                                                                  //   input,    width = 1,             clk.clk
		.reset                   (address_extender_host2noc_expanded_master_translator_reset_reset_bridge_in_reset_reset), //   input,    width = 1,       clk_reset.reset
		.m0_address              (ccv_hps_to_noc_s0_agent_m0_address),                                                     //  output,   width = 44,              m0.address
		.m0_burstcount           (ccv_hps_to_noc_s0_agent_m0_burstcount),                                                  //  output,    width = 9,                .burstcount
		.m0_byteenable           (ccv_hps_to_noc_s0_agent_m0_byteenable),                                                  //  output,   width = 16,                .byteenable
		.m0_debugaccess          (ccv_hps_to_noc_s0_agent_m0_debugaccess),                                                 //  output,    width = 1,                .debugaccess
		.m0_lock                 (ccv_hps_to_noc_s0_agent_m0_lock),                                                        //  output,    width = 1,                .lock
		.m0_readdata             (ccv_hps_to_noc_s0_agent_m0_readdata),                                                    //   input,  width = 128,                .readdata
		.m0_readdatavalid        (ccv_hps_to_noc_s0_agent_m0_readdatavalid),                                               //   input,    width = 1,                .readdatavalid
		.m0_read                 (ccv_hps_to_noc_s0_agent_m0_read),                                                        //  output,    width = 1,                .read
		.m0_waitrequest          (ccv_hps_to_noc_s0_agent_m0_waitrequest),                                                 //   input,    width = 1,                .waitrequest
		.m0_writedata            (ccv_hps_to_noc_s0_agent_m0_writedata),                                                   //  output,  width = 128,                .writedata
		.m0_write                (ccv_hps_to_noc_s0_agent_m0_write),                                                       //  output,    width = 1,                .write
		.m0_response             (ccv_hps_to_noc_s0_agent_m0_response),                                                    //   input,    width = 2,                .response
		.m0_writeresponsevalid   (ccv_hps_to_noc_s0_agent_m0_writeresponsevalid),                                          //   input,    width = 1,                .writeresponsevalid
		.rp_endofpacket          (ccv_hps_to_noc_s0_agent_rp_endofpacket),                                                 //  output,    width = 1,              rp.endofpacket
		.rp_ready                (ccv_hps_to_noc_s0_agent_rp_ready),                                                       //   input,    width = 1,                .ready
		.rp_valid                (ccv_hps_to_noc_s0_agent_rp_valid),                                                       //  output,    width = 1,                .valid
		.rp_data                 (ccv_hps_to_noc_s0_agent_rp_data),                                                        //  output,  width = 255,                .data
		.rp_startofpacket        (ccv_hps_to_noc_s0_agent_rp_startofpacket),                                               //  output,    width = 1,                .startofpacket
		.cp_ready                (cmd_mux_src_ready),                                                                      //  output,    width = 1,              cp.ready
		.cp_valid                (cmd_mux_src_valid),                                                                      //   input,    width = 1,                .valid
		.cp_data                 (cmd_mux_src_data),                                                                       //   input,  width = 255,                .data
		.cp_startofpacket        (cmd_mux_src_startofpacket),                                                              //   input,    width = 1,                .startofpacket
		.cp_endofpacket          (cmd_mux_src_endofpacket),                                                                //   input,    width = 1,                .endofpacket
		.cp_channel              (cmd_mux_src_channel),                                                                    //   input,    width = 1,                .channel
		.rf_sink_ready           (ccv_hps_to_noc_s0_agent_rsp_fifo_out_ready),                                             //  output,    width = 1,         rf_sink.ready
		.rf_sink_valid           (ccv_hps_to_noc_s0_agent_rsp_fifo_out_valid),                                             //   input,    width = 1,                .valid
		.rf_sink_startofpacket   (ccv_hps_to_noc_s0_agent_rsp_fifo_out_startofpacket),                                     //   input,    width = 1,                .startofpacket
		.rf_sink_endofpacket     (ccv_hps_to_noc_s0_agent_rsp_fifo_out_endofpacket),                                       //   input,    width = 1,                .endofpacket
		.rf_sink_data            (ccv_hps_to_noc_s0_agent_rsp_fifo_out_data),                                              //   input,  width = 256,                .data
		.rf_source_ready         (ccv_hps_to_noc_s0_agent_rf_source_ready),                                                //   input,    width = 1,       rf_source.ready
		.rf_source_valid         (ccv_hps_to_noc_s0_agent_rf_source_valid),                                                //  output,    width = 1,                .valid
		.rf_source_startofpacket (ccv_hps_to_noc_s0_agent_rf_source_startofpacket),                                        //  output,    width = 1,                .startofpacket
		.rf_source_endofpacket   (ccv_hps_to_noc_s0_agent_rf_source_endofpacket),                                          //  output,    width = 1,                .endofpacket
		.rf_source_data          (ccv_hps_to_noc_s0_agent_rf_source_data),                                                 //  output,  width = 256,                .data
		.rdata_fifo_sink_ready   (ccv_hps_to_noc_s0_agent_rdata_fifo_src_ready),                                           //  output,    width = 1, rdata_fifo_sink.ready
		.rdata_fifo_sink_valid   (ccv_hps_to_noc_s0_agent_rdata_fifo_src_valid),                                           //   input,    width = 1,                .valid
		.rdata_fifo_sink_data    (ccv_hps_to_noc_s0_agent_rdata_fifo_src_data),                                            //   input,  width = 130,                .data
		.rdata_fifo_src_ready    (ccv_hps_to_noc_s0_agent_rdata_fifo_src_ready),                                           //   input,    width = 1,  rdata_fifo_src.ready
		.rdata_fifo_src_valid    (ccv_hps_to_noc_s0_agent_rdata_fifo_src_valid),                                           //  output,    width = 1,                .valid
		.rdata_fifo_src_data     (ccv_hps_to_noc_s0_agent_rdata_fifo_src_data),                                            //  output,  width = 130,                .data
		.rdata_fifo_sink_error   (1'b0)                                                                                    // (terminated),                               
	);

	platform_altera_avalon_sc_fifo_1932_22gxxgi #(
		.SYMBOLS_PER_BEAT    (1),
		.BITS_PER_SYMBOL     (256),
		.FIFO_DEPTH          (129),
		.CHANNEL_WIDTH       (0),
		.ERROR_WIDTH         (0),
		.USE_PACKETS         (1),
		.USE_FILL_LEVEL      (0),
		.EMPTY_LATENCY       (1),
		.USE_MEMORY_BLOCKS   (0),
		.USE_STORE_FORWARD   (0),
		.USE_ALMOST_FULL_IF  (0),
		.USE_ALMOST_EMPTY_IF (0),
		.EMPTY_WIDTH         (1),
		.MEM_TYPE            ("M20K"),
		.SYNC_RESET          (1)
	) ccv_hps_to_noc_s0_agent_rsp_fifo (
		.clk               (sysclk_in_out_clk_clk),                                       //   input,    width = 1,       clk.clk
		.reset             (address_extender_host2noc_reset_reset_bridge_in_reset_reset), //   input,    width = 1, clk_reset.reset
		.in_data           (ccv_hps_to_noc_s0_agent_rf_source_data),                      //   input,  width = 256,        in.data
		.in_valid          (ccv_hps_to_noc_s0_agent_rf_source_valid),                     //   input,    width = 1,          .valid
		.in_ready          (ccv_hps_to_noc_s0_agent_rf_source_ready),                     //  output,    width = 1,          .ready
		.in_startofpacket  (ccv_hps_to_noc_s0_agent_rf_source_startofpacket),             //   input,    width = 1,          .startofpacket
		.in_endofpacket    (ccv_hps_to_noc_s0_agent_rf_source_endofpacket),               //   input,    width = 1,          .endofpacket
		.out_data          (ccv_hps_to_noc_s0_agent_rsp_fifo_out_data),                   //  output,  width = 256,       out.data
		.out_valid         (ccv_hps_to_noc_s0_agent_rsp_fifo_out_valid),                  //  output,    width = 1,          .valid
		.out_ready         (ccv_hps_to_noc_s0_agent_rsp_fifo_out_ready),                  //   input,    width = 1,          .ready
		.out_startofpacket (ccv_hps_to_noc_s0_agent_rsp_fifo_out_startofpacket),          //  output,    width = 1,          .startofpacket
		.out_endofpacket   (ccv_hps_to_noc_s0_agent_rsp_fifo_out_endofpacket),            //  output,    width = 1,          .endofpacket
		.csr_address       (2'b00),                                                       // (terminated),                         
		.csr_read          (1'b0),                                                        // (terminated),                         
		.csr_write         (1'b0),                                                        // (terminated),                         
		.csr_readdata      (),                                                            // (terminated),                         
		.csr_writedata     (32'b00000000000000000000000000000000),                        // (terminated),                         
		.almost_full_data  (),                                                            // (terminated),                         
		.almost_empty_data (),                                                            // (terminated),                         
		.in_empty          (1'b0),                                                        // (terminated),                         
		.out_empty         (),                                                            // (terminated),                         
		.in_error          (1'b0),                                                        // (terminated),                         
		.out_error         (),                                                            // (terminated),                         
		.in_channel        (1'b0),                                                        // (terminated),                         
		.out_channel       ()                                                             // (terminated),                         
	);

	platform_altera_merlin_router_1921_vgn7xay router (
		.sink_ready         (address_extender_host2noc_expanded_master_agent_cp_ready),                               //  output,    width = 1,      sink.ready
		.sink_valid         (address_extender_host2noc_expanded_master_agent_cp_valid),                               //   input,    width = 1,          .valid
		.sink_data          (address_extender_host2noc_expanded_master_agent_cp_data),                                //   input,  width = 255,          .data
		.sink_startofpacket (address_extender_host2noc_expanded_master_agent_cp_startofpacket),                       //   input,    width = 1,          .startofpacket
		.sink_endofpacket   (address_extender_host2noc_expanded_master_agent_cp_endofpacket),                         //   input,    width = 1,          .endofpacket
		.clk                (sysclk_in_out_clk_clk),                                                                  //   input,    width = 1,       clk.clk
		.reset              (address_extender_host2noc_expanded_master_translator_reset_reset_bridge_in_reset_reset), //   input,    width = 1, clk_reset.reset
		.src_ready          (router_src_ready),                                                                       //   input,    width = 1,       src.ready
		.src_valid          (router_src_valid),                                                                       //  output,    width = 1,          .valid
		.src_data           (router_src_data),                                                                        //  output,  width = 255,          .data
		.src_channel        (router_src_channel),                                                                     //  output,    width = 1,          .channel
		.src_startofpacket  (router_src_startofpacket),                                                               //  output,    width = 1,          .startofpacket
		.src_endofpacket    (router_src_endofpacket)                                                                  //  output,    width = 1,          .endofpacket
	);

	platform_altera_merlin_router_1921_iuxfu4i router_001 (
		.sink_ready         (ccv_hps_to_noc_s0_agent_rp_ready),                                                       //  output,    width = 1,      sink.ready
		.sink_valid         (ccv_hps_to_noc_s0_agent_rp_valid),                                                       //   input,    width = 1,          .valid
		.sink_data          (ccv_hps_to_noc_s0_agent_rp_data),                                                        //   input,  width = 255,          .data
		.sink_startofpacket (ccv_hps_to_noc_s0_agent_rp_startofpacket),                                               //   input,    width = 1,          .startofpacket
		.sink_endofpacket   (ccv_hps_to_noc_s0_agent_rp_endofpacket),                                                 //   input,    width = 1,          .endofpacket
		.clk                (sysclk_in_out_clk_clk),                                                                  //   input,    width = 1,       clk.clk
		.reset              (address_extender_host2noc_expanded_master_translator_reset_reset_bridge_in_reset_reset), //   input,    width = 1, clk_reset.reset
		.src_ready          (router_001_src_ready),                                                                   //   input,    width = 1,       src.ready
		.src_valid          (router_001_src_valid),                                                                   //  output,    width = 1,          .valid
		.src_data           (router_001_src_data),                                                                    //  output,  width = 255,          .data
		.src_channel        (router_001_src_channel),                                                                 //  output,    width = 1,          .channel
		.src_startofpacket  (router_001_src_startofpacket),                                                           //  output,    width = 1,          .startofpacket
		.src_endofpacket    (router_001_src_endofpacket)                                                              //  output,    width = 1,          .endofpacket
	);

	platform_altera_merlin_demultiplexer_1921_2c4zovi cmd_demux (
		.clk                (sysclk_in_out_clk_clk),                                                                  //   input,    width = 1,       clk.clk
		.reset              (address_extender_host2noc_expanded_master_translator_reset_reset_bridge_in_reset_reset), //   input,    width = 1, clk_reset.reset
		.sink_ready         (router_src_ready),                                                                       //  output,    width = 1,      sink.ready
		.sink_channel       (router_src_channel),                                                                     //   input,    width = 1,          .channel
		.sink_data          (router_src_data),                                                                        //   input,  width = 255,          .data
		.sink_startofpacket (router_src_startofpacket),                                                               //   input,    width = 1,          .startofpacket
		.sink_endofpacket   (router_src_endofpacket),                                                                 //   input,    width = 1,          .endofpacket
		.sink_valid         (router_src_valid),                                                                       //   input,    width = 1,          .valid
		.src0_ready         (cmd_demux_src0_ready),                                                                   //   input,    width = 1,      src0.ready
		.src0_valid         (cmd_demux_src0_valid),                                                                   //  output,    width = 1,          .valid
		.src0_data          (cmd_demux_src0_data),                                                                    //  output,  width = 255,          .data
		.src0_channel       (cmd_demux_src0_channel),                                                                 //  output,    width = 1,          .channel
		.src0_startofpacket (cmd_demux_src0_startofpacket),                                                           //  output,    width = 1,          .startofpacket
		.src0_endofpacket   (cmd_demux_src0_endofpacket)                                                              //  output,    width = 1,          .endofpacket
	);

	platform_altera_merlin_multiplexer_1922_ulae7ni cmd_mux (
		.clk                 (sysclk_in_out_clk_clk),                                                                  //   input,    width = 1,       clk.clk
		.reset               (address_extender_host2noc_expanded_master_translator_reset_reset_bridge_in_reset_reset), //   input,    width = 1, clk_reset.reset
		.src_ready           (cmd_mux_src_ready),                                                                      //   input,    width = 1,       src.ready
		.src_valid           (cmd_mux_src_valid),                                                                      //  output,    width = 1,          .valid
		.src_data            (cmd_mux_src_data),                                                                       //  output,  width = 255,          .data
		.src_channel         (cmd_mux_src_channel),                                                                    //  output,    width = 1,          .channel
		.src_startofpacket   (cmd_mux_src_startofpacket),                                                              //  output,    width = 1,          .startofpacket
		.src_endofpacket     (cmd_mux_src_endofpacket),                                                                //  output,    width = 1,          .endofpacket
		.sink0_ready         (cmd_demux_src0_ready),                                                                   //  output,    width = 1,     sink0.ready
		.sink0_valid         (cmd_demux_src0_valid),                                                                   //   input,    width = 1,          .valid
		.sink0_channel       (cmd_demux_src0_channel),                                                                 //   input,    width = 1,          .channel
		.sink0_data          (cmd_demux_src0_data),                                                                    //   input,  width = 255,          .data
		.sink0_startofpacket (cmd_demux_src0_startofpacket),                                                           //   input,    width = 1,          .startofpacket
		.sink0_endofpacket   (cmd_demux_src0_endofpacket)                                                              //   input,    width = 1,          .endofpacket
	);

	platform_altera_merlin_demultiplexer_1921_2c4zovi rsp_demux (
		.clk                (sysclk_in_out_clk_clk),                                                                  //   input,    width = 1,       clk.clk
		.reset              (address_extender_host2noc_expanded_master_translator_reset_reset_bridge_in_reset_reset), //   input,    width = 1, clk_reset.reset
		.sink_ready         (router_001_src_ready),                                                                   //  output,    width = 1,      sink.ready
		.sink_channel       (router_001_src_channel),                                                                 //   input,    width = 1,          .channel
		.sink_data          (router_001_src_data),                                                                    //   input,  width = 255,          .data
		.sink_startofpacket (router_001_src_startofpacket),                                                           //   input,    width = 1,          .startofpacket
		.sink_endofpacket   (router_001_src_endofpacket),                                                             //   input,    width = 1,          .endofpacket
		.sink_valid         (router_001_src_valid),                                                                   //   input,    width = 1,          .valid
		.src0_ready         (rsp_demux_src0_ready),                                                                   //   input,    width = 1,      src0.ready
		.src0_valid         (rsp_demux_src0_valid),                                                                   //  output,    width = 1,          .valid
		.src0_data          (rsp_demux_src0_data),                                                                    //  output,  width = 255,          .data
		.src0_channel       (rsp_demux_src0_channel),                                                                 //  output,    width = 1,          .channel
		.src0_startofpacket (rsp_demux_src0_startofpacket),                                                           //  output,    width = 1,          .startofpacket
		.src0_endofpacket   (rsp_demux_src0_endofpacket)                                                              //  output,    width = 1,          .endofpacket
	);

	platform_altera_merlin_multiplexer_1922_hqrloyi rsp_mux (
		.clk                 (sysclk_in_out_clk_clk),                                                                  //   input,    width = 1,       clk.clk
		.reset               (address_extender_host2noc_expanded_master_translator_reset_reset_bridge_in_reset_reset), //   input,    width = 1, clk_reset.reset
		.src_ready           (rsp_mux_src_ready),                                                                      //   input,    width = 1,       src.ready
		.src_valid           (rsp_mux_src_valid),                                                                      //  output,    width = 1,          .valid
		.src_data            (rsp_mux_src_data),                                                                       //  output,  width = 255,          .data
		.src_channel         (rsp_mux_src_channel),                                                                    //  output,    width = 1,          .channel
		.src_startofpacket   (rsp_mux_src_startofpacket),                                                              //  output,    width = 1,          .startofpacket
		.src_endofpacket     (rsp_mux_src_endofpacket),                                                                //  output,    width = 1,          .endofpacket
		.sink0_ready         (rsp_demux_src0_ready),                                                                   //  output,    width = 1,     sink0.ready
		.sink0_valid         (rsp_demux_src0_valid),                                                                   //   input,    width = 1,          .valid
		.sink0_channel       (rsp_demux_src0_channel),                                                                 //   input,    width = 1,          .channel
		.sink0_data          (rsp_demux_src0_data),                                                                    //   input,  width = 255,          .data
		.sink0_startofpacket (rsp_demux_src0_startofpacket),                                                           //   input,    width = 1,          .startofpacket
		.sink0_endofpacket   (rsp_demux_src0_endofpacket)                                                              //   input,    width = 1,          .endofpacket
	);

endmodule
