// platform_emif_io96b_hps_0_emif_io96b_hps_300_2mmae3q_emif_0_ddr4comp_emif_io96b_cal_intel_noc_target_210_7v5e3qy.v

// Generated using ACDS version 25.1 129

`timescale 1 ps / 1 ps
module platform_emif_io96b_hps_0_emif_io96b_hps_300_2mmae3q_emif_0_ddr4comp_emif_io96b_cal_intel_noc_target_210_7v5e3qy #(
		parameter       CHOOSE_AXI                          = "AXI4lite",
		parameter       AXI_DATA_WIDTH                      = 32,
		parameter       NOC_TARGET_DFD_EN                   = "NOC_TARGET_DFD_EN_DISABLE",
		parameter       NOC_EMIF_ADDR_MASK                  = "NOC_EMIF_ADDR_MASK_4_GB",
		parameter       NOC_TARGET_SIZE                     = "128_MB",
		parameter       NOC_NON_USER_NIU                    = "ENABLE",
		parameter       NOC_ISOLATION_GROUP                 = "DEFAULT",
		parameter       NOC_TARGET_ECC_EN                   = "NOC_TARGET_ECC_EN_DISABLE",
		parameter       NOC_SECURE_FILTER_ENA               = "NOC_SECURE_FILTER_ENA_DISABLE",
		parameter       AXI_ADDR_WIDTH                      = 27,
		parameter       AXI_AUSER_WIDTH                     = 14,
		parameter       AXI_USER_WIDTH                      = 32,
		parameter       AXI_ID_WIDTH                        = 7,
		parameter       AXI_WSTRB_WIDTH                     = 4,
		parameter[31:0] POWERMODE_FREQ_HZ_NOC_TNIU_CLK      = 32'b00000000000000000000000000000000,
		parameter       NOC_SECURE_RANGE0_VALID             = "NOC_SECURE_RANGE0_VALID_INVALID",
		parameter[63:0] NOC_SECURE_RANGE0_BASE              = 64'b0000000000000000000000000000000000000000000000000000000000000000,
		parameter       NOC_SECURE_RANGE0_SPAN              = "NOC_SECURE_RANGE0_MASK_128_MB",
		parameter[63:0] NOC_SECURE_RANGE0_WRITE_ACCESS_PRIV = 64'b0000000000000000000000000000000000000000000000000000000000000000,
		parameter[63:0] NOC_SECURE_RANGE0_READ_ACCESS_PRIV  = 64'b0000000000000000000000000000000000000000000000000000000000000000,
		parameter       NOC_SECURE_RANGE1_VALID             = "NOC_SECURE_RANGE1_VALID_INVALID",
		parameter[63:0] NOC_SECURE_RANGE1_BASE              = 64'b0000000000000000000000000000000000000000000000000000000000000000,
		parameter       NOC_SECURE_RANGE1_SPAN              = "NOC_SECURE_RANGE1_MASK_128_MB",
		parameter[63:0] NOC_SECURE_RANGE1_WRITE_ACCESS_PRIV = 64'b0000000000000000000000000000000000000000000000000000000000000000,
		parameter[63:0] NOC_SECURE_RANGE1_READ_ACCESS_PRIV  = 64'b0000000000000000000000000000000000000000000000000000000000000000,
		parameter       NOC_SECURE_RANGE2_VALID             = "NOC_SECURE_RANGE2_VALID_INVALID",
		parameter[63:0] NOC_SECURE_RANGE2_BASE              = 64'b0000000000000000000000000000000000000000000000000000000000000000,
		parameter       NOC_SECURE_RANGE2_SPAN              = "NOC_SECURE_RANGE2_MASK_128_MB",
		parameter[63:0] NOC_SECURE_RANGE2_WRITE_ACCESS_PRIV = 64'b0000000000000000000000000000000000000000000000000000000000000000,
		parameter[63:0] NOC_SECURE_RANGE2_READ_ACCESS_PRIV  = 64'b0000000000000000000000000000000000000000000000000000000000000000,
		parameter       NOC_SECURE_RANGE3_VALID             = "NOC_SECURE_RANGE3_VALID_INVALID",
		parameter[63:0] NOC_SECURE_RANGE3_BASE              = 64'b0000000000000000000000000000000000000000000000000000000000000000,
		parameter       NOC_SECURE_RANGE3_SPAN              = "NOC_SECURE_RANGE3_MASK_128_MB",
		parameter[63:0] NOC_SECURE_RANGE3_WRITE_ACCESS_PRIV = 64'b0000000000000000000000000000000000000000000000000000000000000000,
		parameter[63:0] NOC_SECURE_RANGE3_READ_ACCESS_PRIV  = 64'b0000000000000000000000000000000000000000000000000000000000000000,
		parameter       NOC_SECURE_RANGE4_VALID             = "NOC_SECURE_RANGE4_VALID_INVALID",
		parameter[63:0] NOC_SECURE_RANGE4_BASE              = 64'b0000000000000000000000000000000000000000000000000000000000000000,
		parameter       NOC_SECURE_RANGE4_SPAN              = "NOC_SECURE_RANGE4_MASK_128_MB",
		parameter[63:0] NOC_SECURE_RANGE4_WRITE_ACCESS_PRIV = 64'b0000000000000000000000000000000000000000000000000000000000000000,
		parameter[63:0] NOC_SECURE_RANGE4_READ_ACCESS_PRIV  = 64'b0000000000000000000000000000000000000000000000000000000000000000,
		parameter       NOC_SECURE_RANGE5_VALID             = "NOC_SECURE_RANGE5_VALID_INVALID",
		parameter[63:0] NOC_SECURE_RANGE5_BASE              = 64'b0000000000000000000000000000000000000000000000000000000000000000,
		parameter       NOC_SECURE_RANGE5_SPAN              = "NOC_SECURE_RANGE5_MASK_128_MB",
		parameter[63:0] NOC_SECURE_RANGE5_WRITE_ACCESS_PRIV = 64'b0000000000000000000000000000000000000000000000000000000000000000,
		parameter[63:0] NOC_SECURE_RANGE5_READ_ACCESS_PRIV  = 64'b0000000000000000000000000000000000000000000000000000000000000000,
		parameter       NOC_SECURE_RANGE6_VALID             = "NOC_SECURE_RANGE6_VALID_INVALID",
		parameter[63:0] NOC_SECURE_RANGE6_BASE              = 64'b0000000000000000000000000000000000000000000000000000000000000000,
		parameter       NOC_SECURE_RANGE6_SPAN              = "NOC_SECURE_RANGE6_MASK_128_MB",
		parameter[63:0] NOC_SECURE_RANGE6_WRITE_ACCESS_PRIV = 64'b0000000000000000000000000000000000000000000000000000000000000000,
		parameter[63:0] NOC_SECURE_RANGE6_READ_ACCESS_PRIV  = 64'b0000000000000000000000000000000000000000000000000000000000000000,
		parameter       NOC_SECURE_RANGE7_VALID             = "NOC_SECURE_RANGE7_VALID_INVALID",
		parameter[63:0] NOC_SECURE_RANGE7_BASE              = 64'b0000000000000000000000000000000000000000000000000000000000000000,
		parameter       NOC_SECURE_RANGE7_SPAN              = "NOC_SECURE_RANGE7_MASK_128_MB",
		parameter[63:0] NOC_SECURE_RANGE7_WRITE_ACCESS_PRIV = 64'b0000000000000000000000000000000000000000000000000000000000000000,
		parameter[63:0] NOC_SECURE_RANGE7_READ_ACCESS_PRIV  = 64'b0000000000000000000000000000000000000000000000000000000000000000
	) (
		input  wire        clk,              //               clk.clk
		input  wire        reset,            //             reset.reset
		output wire [26:0] response_awaddr,  // altera_axi_master.awaddr
		output wire [2:0]  response_awprot,  //                  .awprot
		output wire        response_awvalid, //                  .awvalid
		input  wire        response_awready, //                  .awready
		output wire [31:0] response_wdata,   //                  .wdata
		input  wire        response_wready,  //                  .wready
		output wire [3:0]  response_wstrb,   //                  .wstrb
		output wire        response_wvalid,  //                  .wvalid
		input  wire [1:0]  response_bresp,   //                  .bresp
		input  wire        response_bvalid,  //                  .bvalid
		output wire        response_bready,  //                  .bready
		output wire [26:0] response_araddr,  //                  .araddr
		output wire [2:0]  response_arprot,  //                  .arprot
		output wire        response_arvalid, //                  .arvalid
		input  wire        response_arready, //                  .arready
		input  wire [31:0] response_rdata,   //                  .rdata
		input  wire [1:0]  response_rresp,   //                  .rresp
		input  wire        response_rvalid,  //                  .rvalid
		output wire        response_rready   //                  .rready
	);

	generate
		// If any of the display statements (or deliberately broken
		// instantiations) within this generate block triggers then this module
		// has been instantiated this module with a set of parameters different
		// from those it was generated for.  This will usually result in a
		// non-functioning system.
		if (CHOOSE_AXI != "AXI4lite")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					choose_axi_check ( .error(1'b1) );
		end
		if (AXI_DATA_WIDTH != 32)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					axi_data_width_check ( .error(1'b1) );
		end
		if (NOC_TARGET_DFD_EN != "NOC_TARGET_DFD_EN_DISABLE")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_target_dfd_en_check ( .error(1'b1) );
		end
		if (NOC_EMIF_ADDR_MASK != "NOC_EMIF_ADDR_MASK_4_GB")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_emif_addr_mask_check ( .error(1'b1) );
		end
		if (NOC_TARGET_SIZE != "128_MB")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_target_size_check ( .error(1'b1) );
		end
		if (NOC_NON_USER_NIU != "ENABLE")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_non_user_niu_check ( .error(1'b1) );
		end
		if (NOC_ISOLATION_GROUP != "DEFAULT")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_isolation_group_check ( .error(1'b1) );
		end
		if (NOC_TARGET_ECC_EN != "NOC_TARGET_ECC_EN_DISABLE")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_target_ecc_en_check ( .error(1'b1) );
		end
		if (NOC_SECURE_FILTER_ENA != "NOC_SECURE_FILTER_ENA_DISABLE")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_filter_ena_check ( .error(1'b1) );
		end
		if (AXI_ADDR_WIDTH != 27)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					axi_addr_width_check ( .error(1'b1) );
		end
		if (AXI_AUSER_WIDTH != 14)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					axi_auser_width_check ( .error(1'b1) );
		end
		if (AXI_USER_WIDTH != 32)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					axi_user_width_check ( .error(1'b1) );
		end
		if (AXI_ID_WIDTH != 7)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					axi_id_width_check ( .error(1'b1) );
		end
		if (AXI_WSTRB_WIDTH != 4)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					axi_wstrb_width_check ( .error(1'b1) );
		end
		if (POWERMODE_FREQ_HZ_NOC_TNIU_CLK != 32'b00000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					powermode_freq_hz_noc_tniu_clk_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE0_VALID != "NOC_SECURE_RANGE0_VALID_INVALID")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range0_valid_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE0_BASE != 64'b0000000000000000000000000000000000000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range0_base_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE0_SPAN != "NOC_SECURE_RANGE0_MASK_128_MB")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range0_span_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE0_WRITE_ACCESS_PRIV != 64'b0000000000000000000000000000000000000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range0_write_access_priv_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE0_READ_ACCESS_PRIV != 64'b0000000000000000000000000000000000000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range0_read_access_priv_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE1_VALID != "NOC_SECURE_RANGE1_VALID_INVALID")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range1_valid_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE1_BASE != 64'b0000000000000000000000000000000000000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range1_base_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE1_SPAN != "NOC_SECURE_RANGE1_MASK_128_MB")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range1_span_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE1_WRITE_ACCESS_PRIV != 64'b0000000000000000000000000000000000000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range1_write_access_priv_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE1_READ_ACCESS_PRIV != 64'b0000000000000000000000000000000000000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range1_read_access_priv_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE2_VALID != "NOC_SECURE_RANGE2_VALID_INVALID")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range2_valid_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE2_BASE != 64'b0000000000000000000000000000000000000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range2_base_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE2_SPAN != "NOC_SECURE_RANGE2_MASK_128_MB")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range2_span_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE2_WRITE_ACCESS_PRIV != 64'b0000000000000000000000000000000000000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range2_write_access_priv_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE2_READ_ACCESS_PRIV != 64'b0000000000000000000000000000000000000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range2_read_access_priv_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE3_VALID != "NOC_SECURE_RANGE3_VALID_INVALID")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range3_valid_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE3_BASE != 64'b0000000000000000000000000000000000000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range3_base_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE3_SPAN != "NOC_SECURE_RANGE3_MASK_128_MB")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range3_span_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE3_WRITE_ACCESS_PRIV != 64'b0000000000000000000000000000000000000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range3_write_access_priv_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE3_READ_ACCESS_PRIV != 64'b0000000000000000000000000000000000000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range3_read_access_priv_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE4_VALID != "NOC_SECURE_RANGE4_VALID_INVALID")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range4_valid_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE4_BASE != 64'b0000000000000000000000000000000000000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range4_base_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE4_SPAN != "NOC_SECURE_RANGE4_MASK_128_MB")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range4_span_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE4_WRITE_ACCESS_PRIV != 64'b0000000000000000000000000000000000000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range4_write_access_priv_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE4_READ_ACCESS_PRIV != 64'b0000000000000000000000000000000000000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range4_read_access_priv_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE5_VALID != "NOC_SECURE_RANGE5_VALID_INVALID")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range5_valid_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE5_BASE != 64'b0000000000000000000000000000000000000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range5_base_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE5_SPAN != "NOC_SECURE_RANGE5_MASK_128_MB")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range5_span_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE5_WRITE_ACCESS_PRIV != 64'b0000000000000000000000000000000000000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range5_write_access_priv_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE5_READ_ACCESS_PRIV != 64'b0000000000000000000000000000000000000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range5_read_access_priv_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE6_VALID != "NOC_SECURE_RANGE6_VALID_INVALID")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range6_valid_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE6_BASE != 64'b0000000000000000000000000000000000000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range6_base_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE6_SPAN != "NOC_SECURE_RANGE6_MASK_128_MB")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range6_span_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE6_WRITE_ACCESS_PRIV != 64'b0000000000000000000000000000000000000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range6_write_access_priv_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE6_READ_ACCESS_PRIV != 64'b0000000000000000000000000000000000000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range6_read_access_priv_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE7_VALID != "NOC_SECURE_RANGE7_VALID_INVALID")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range7_valid_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE7_BASE != 64'b0000000000000000000000000000000000000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range7_base_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE7_SPAN != "NOC_SECURE_RANGE7_MASK_128_MB")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range7_span_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE7_WRITE_ACCESS_PRIV != 64'b0000000000000000000000000000000000000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range7_write_access_priv_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE7_READ_ACCESS_PRIV != 64'b0000000000000000000000000000000000000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range7_read_access_priv_check ( .error(1'b1) );
		end
	endgenerate

	platform_emif_io96b_hps_0_emif_io96b_hps_300_2mmae3q_emif_0_ddr4comp_intel_noc_target_210_dahi33y #(
		.CHOOSE_AXI                          ("AXI4lite"),
		.AXI_DATA_WIDTH                      (32),
		.NOC_TARGET_DFD_EN                   ("NOC_TARGET_DFD_EN_DISABLE"),
		.NOC_EMIF_ADDR_MASK                  ("NOC_EMIF_ADDR_MASK_4_GB"),
		.NOC_TARGET_SIZE                     ("128_MB"),
		.NOC_NON_USER_NIU                    ("ENABLE"),
		.NOC_ISOLATION_GROUP                 ("DEFAULT"),
		.NOC_TARGET_ECC_EN                   ("NOC_TARGET_ECC_EN_DISABLE"),
		.NOC_SECURE_FILTER_ENA               ("NOC_SECURE_FILTER_ENA_DISABLE"),
		.AXI_ADDR_WIDTH                      (27),
		.AXI_AUSER_WIDTH                     (14),
		.AXI_USER_WIDTH                      (32),
		.AXI_ID_WIDTH                        (7),
		.AXI_WSTRB_WIDTH                     (4),
		.POWERMODE_FREQ_HZ_NOC_TNIU_CLK      (32'b00000000000000000000000000000000),
		.NOC_SECURE_RANGE0_VALID             ("NOC_SECURE_RANGE0_VALID_INVALID"),
		.NOC_SECURE_RANGE0_BASE              (64'b0000000000000000000000000000000000000000000000000000000000000000),
		.NOC_SECURE_RANGE0_SPAN              ("NOC_SECURE_RANGE0_MASK_128_MB"),
		.NOC_SECURE_RANGE0_WRITE_ACCESS_PRIV (64'b0000000000000000000000000000000000000000000000000000000000000000),
		.NOC_SECURE_RANGE0_READ_ACCESS_PRIV  (64'b0000000000000000000000000000000000000000000000000000000000000000),
		.NOC_SECURE_RANGE1_VALID             ("NOC_SECURE_RANGE1_VALID_INVALID"),
		.NOC_SECURE_RANGE1_BASE              (64'b0000000000000000000000000000000000000000000000000000000000000000),
		.NOC_SECURE_RANGE1_SPAN              ("NOC_SECURE_RANGE1_MASK_128_MB"),
		.NOC_SECURE_RANGE1_WRITE_ACCESS_PRIV (64'b0000000000000000000000000000000000000000000000000000000000000000),
		.NOC_SECURE_RANGE1_READ_ACCESS_PRIV  (64'b0000000000000000000000000000000000000000000000000000000000000000),
		.NOC_SECURE_RANGE2_VALID             ("NOC_SECURE_RANGE2_VALID_INVALID"),
		.NOC_SECURE_RANGE2_BASE              (64'b0000000000000000000000000000000000000000000000000000000000000000),
		.NOC_SECURE_RANGE2_SPAN              ("NOC_SECURE_RANGE2_MASK_128_MB"),
		.NOC_SECURE_RANGE2_WRITE_ACCESS_PRIV (64'b0000000000000000000000000000000000000000000000000000000000000000),
		.NOC_SECURE_RANGE2_READ_ACCESS_PRIV  (64'b0000000000000000000000000000000000000000000000000000000000000000),
		.NOC_SECURE_RANGE3_VALID             ("NOC_SECURE_RANGE3_VALID_INVALID"),
		.NOC_SECURE_RANGE3_BASE              (64'b0000000000000000000000000000000000000000000000000000000000000000),
		.NOC_SECURE_RANGE3_SPAN              ("NOC_SECURE_RANGE3_MASK_128_MB"),
		.NOC_SECURE_RANGE3_WRITE_ACCESS_PRIV (64'b0000000000000000000000000000000000000000000000000000000000000000),
		.NOC_SECURE_RANGE3_READ_ACCESS_PRIV  (64'b0000000000000000000000000000000000000000000000000000000000000000),
		.NOC_SECURE_RANGE4_VALID             ("NOC_SECURE_RANGE4_VALID_INVALID"),
		.NOC_SECURE_RANGE4_BASE              (64'b0000000000000000000000000000000000000000000000000000000000000000),
		.NOC_SECURE_RANGE4_SPAN              ("NOC_SECURE_RANGE4_MASK_128_MB"),
		.NOC_SECURE_RANGE4_WRITE_ACCESS_PRIV (64'b0000000000000000000000000000000000000000000000000000000000000000),
		.NOC_SECURE_RANGE4_READ_ACCESS_PRIV  (64'b0000000000000000000000000000000000000000000000000000000000000000),
		.NOC_SECURE_RANGE5_VALID             ("NOC_SECURE_RANGE5_VALID_INVALID"),
		.NOC_SECURE_RANGE5_BASE              (64'b0000000000000000000000000000000000000000000000000000000000000000),
		.NOC_SECURE_RANGE5_SPAN              ("NOC_SECURE_RANGE5_MASK_128_MB"),
		.NOC_SECURE_RANGE5_WRITE_ACCESS_PRIV (64'b0000000000000000000000000000000000000000000000000000000000000000),
		.NOC_SECURE_RANGE5_READ_ACCESS_PRIV  (64'b0000000000000000000000000000000000000000000000000000000000000000),
		.NOC_SECURE_RANGE6_VALID             ("NOC_SECURE_RANGE6_VALID_INVALID"),
		.NOC_SECURE_RANGE6_BASE              (64'b0000000000000000000000000000000000000000000000000000000000000000),
		.NOC_SECURE_RANGE6_SPAN              ("NOC_SECURE_RANGE6_MASK_128_MB"),
		.NOC_SECURE_RANGE6_WRITE_ACCESS_PRIV (64'b0000000000000000000000000000000000000000000000000000000000000000),
		.NOC_SECURE_RANGE6_READ_ACCESS_PRIV  (64'b0000000000000000000000000000000000000000000000000000000000000000),
		.NOC_SECURE_RANGE7_VALID             ("NOC_SECURE_RANGE7_VALID_INVALID"),
		.NOC_SECURE_RANGE7_BASE              (64'b0000000000000000000000000000000000000000000000000000000000000000),
		.NOC_SECURE_RANGE7_SPAN              ("NOC_SECURE_RANGE7_MASK_128_MB"),
		.NOC_SECURE_RANGE7_WRITE_ACCESS_PRIV (64'b0000000000000000000000000000000000000000000000000000000000000000),
		.NOC_SECURE_RANGE7_READ_ACCESS_PRIV  (64'b0000000000000000000000000000000000000000000000000000000000000000)
	) tniu (
		.clk              (clk),                                  //   input,   width = 1,               clk.clk
		.reset            (reset),                                //   input,   width = 1,             reset.reset
		.response_awaddr  (response_awaddr),                      //  output,  width = 27, altera_axi_master.awaddr
		.response_awprot  (response_awprot),                      //  output,   width = 3,                  .awprot
		.response_awvalid (response_awvalid),                     //  output,   width = 1,                  .awvalid
		.response_awready (response_awready),                     //   input,   width = 1,                  .awready
		.response_wdata   (response_wdata),                       //  output,  width = 32,                  .wdata
		.response_wready  (response_wready),                      //   input,   width = 1,                  .wready
		.response_wstrb   (response_wstrb),                       //  output,   width = 4,                  .wstrb
		.response_wvalid  (response_wvalid),                      //  output,   width = 1,                  .wvalid
		.response_bresp   (response_bresp),                       //   input,   width = 2,                  .bresp
		.response_bvalid  (response_bvalid),                      //   input,   width = 1,                  .bvalid
		.response_bready  (response_bready),                      //  output,   width = 1,                  .bready
		.response_araddr  (response_araddr),                      //  output,  width = 27,                  .araddr
		.response_arprot  (response_arprot),                      //  output,   width = 3,                  .arprot
		.response_arvalid (response_arvalid),                     //  output,   width = 1,                  .arvalid
		.response_arready (response_arready),                     //   input,   width = 1,                  .arready
		.response_rdata   (response_rdata),                       //   input,  width = 32,                  .rdata
		.response_rresp   (response_rresp),                       //   input,   width = 2,                  .rresp
		.response_rvalid  (response_rvalid),                      //   input,   width = 1,                  .rvalid
		.response_rready  (response_rready),                      //  output,   width = 1,                  .rready
		.response_awid    (),                                     // (terminated),                                
		.response_awuser  (),                                     // (terminated),                                
		.response_arid    (),                                     // (terminated),                                
		.response_aruser  (),                                     // (terminated),                                
		.response_wuser   (),                                     // (terminated),                                
		.response_ruser   (32'b00000000000000000000000000000000), // (terminated),                                
		.response_rlast   (1'b0),                                 // (terminated),                                
		.response_rid     (7'b0000000),                           // (terminated),                                
		.response_bid     (7'b0000000)                            // (terminated),                                
	);

endmodule
