// platform_hbm_fp_0.v

// Generated using ACDS version 25.1 129

`timescale 1 ps / 1 ps
module platform_hbm_fp_0 (
		output wire       ch0_u0_wmc_intr,   //      ch0_u0_wmc_intr.conduit
		output wire       ch0_u1_wmc_intr,   //      ch0_u1_wmc_intr.conduit
		input  wire       fabric_clk,        //           fabric_clk.clk
		input  wire       hbm_reset_n,       //          hbm_reset_n.reset_n
		output wire       hbm_reset_in_prog, //    hbm_reset_in_prog.hbm_reset_in_prog
		output wire       hbm_cattrip,       //              cattrip.hbm_cattrip
		input  wire       hbm_cattrip_i,     //            cattrip_i.conduit
		output wire [2:0] hbm_temp,          //                 temp.hbm_temp
		input  wire [2:0] hbm_temp_i,        //               temp_i.conduit
		output wire       local_cal_success, //    local_cal_success.local_cal_success
		output wire       local_cal_fail,    //       local_cal_fail.local_cal_fail
		input  wire       uibpll_refclk      //        uibpll_refclk.clk
	);

	platform_hbm_fp_0_hbm_fp_800_c2vgg2y hbm (
		.ch0_u0_wmc_intr   (ch0_u0_wmc_intr),   //  output,  width = 1,   ch0_u0_wmc_intr.conduit
		.ch0_u1_wmc_intr   (ch0_u1_wmc_intr),   //  output,  width = 1,   ch0_u1_wmc_intr.conduit
		.fabric_clk        (fabric_clk),        //   input,  width = 1,        fabric_clk.clk
		.hbm_reset_n       (hbm_reset_n),       //   input,  width = 1,       hbm_reset_n.reset_n
		.hbm_reset_in_prog (hbm_reset_in_prog), //  output,  width = 1, hbm_reset_in_prog.hbm_reset_in_prog
		.hbm_cattrip       (hbm_cattrip),       //  output,  width = 1,           cattrip.hbm_cattrip
		.hbm_cattrip_i     (hbm_cattrip_i),     //   input,  width = 1,         cattrip_i.conduit
		.hbm_temp          (hbm_temp),          //  output,  width = 3,              temp.hbm_temp
		.hbm_temp_i        (hbm_temp_i),        //   input,  width = 3,            temp_i.conduit
		.local_cal_success (local_cal_success), //  output,  width = 1, local_cal_success.local_cal_success
		.local_cal_fail    (local_cal_fail),    //  output,  width = 1,    local_cal_fail.local_cal_fail
		.uibpll_refclk     (uibpll_refclk)      //   input,  width = 1,     uibpll_refclk.clk
	);

endmodule
