// platform_emif_io96b_hps_0_emif_io96b_hps_300_2mmae3q_emif_0_ddr4comp_emif_io96b_ddr4comp_intel_noc_target_300_rnk7l6i.v

// Generated using ACDS version 25.1 129

`timescale 1 ps / 1 ps
module platform_emif_io96b_hps_0_emif_io96b_hps_300_2mmae3q_emif_0_ddr4comp_emif_io96b_ddr4comp_intel_noc_target_300_rnk7l6i #(
		parameter       CHOOSE_AXI                          = "AXI4",
		parameter       AXI_DATA_WIDTH                      = 256,
		parameter       NOC_TARGET_DFD_EN                   = "NOC_TARGET_DFD_EN_DISABLE",
		parameter       NOC_EMIF_ADDR_MASK                  = "NOC_EMIF_ADDR_MASK_8_GB",
		parameter       NOC_TARGET_SIZE                     = "8_GB",
		parameter       NOC_NON_USER_NIU                    = "DISABLE",
		parameter       NOC_ISOLATION_GROUP                 = "HPS_NOC_ISOLATION_GROUP",
		parameter       NOC_TARGET_ECC_EN                   = "NOC_TARGET_ECC_EN_DISABLE",
		parameter       NOC_SECURE_FILTER_ENA               = "NOC_SECURE_FILTER_ENA_DISABLE",
		parameter       AXI_ADDR_WIDTH                      = 40,
		parameter       AXI_AUSER_WIDTH                     = 14,
		parameter       AXI_USER_WIDTH                      = 32,
		parameter       AXI_ID_WIDTH                        = 7,
		parameter       AXI_WSTRB_WIDTH                     = 32,
		parameter[31:0] POWERMODE_FREQ_HZ_NOC_TNIU_CLK      = 32'b00100111101111001000011000000100,
		parameter       NOC_SECURE_RANGE0_VALID             = "NOC_SECURE_RANGE0_VALID_INVALID",
		parameter[63:0] NOC_SECURE_RANGE0_BASE              = 64'b0000000000000000000000000000000000000000000000000000000000000000,
		parameter       NOC_SECURE_RANGE0_SPAN              = "NOC_SECURE_RANGE0_MASK_128_MB",
		parameter[63:0] NOC_SECURE_RANGE0_WRITE_ACCESS_PRIV = 64'b0000000000000000000000000000000000000000000000000000000000000000,
		parameter[63:0] NOC_SECURE_RANGE0_READ_ACCESS_PRIV  = 64'b0000000000000000000000000000000000000000000000000000000000000000,
		parameter       NOC_SECURE_RANGE1_VALID             = "NOC_SECURE_RANGE1_VALID_INVALID",
		parameter[63:0] NOC_SECURE_RANGE1_BASE              = 64'b0000000000000000000000000000000000000000000000000000000000000000,
		parameter       NOC_SECURE_RANGE1_SPAN              = "NOC_SECURE_RANGE1_MASK_128_MB",
		parameter[63:0] NOC_SECURE_RANGE1_WRITE_ACCESS_PRIV = 64'b0000000000000000000000000000000000000000000000000000000000000000,
		parameter[63:0] NOC_SECURE_RANGE1_READ_ACCESS_PRIV  = 64'b0000000000000000000000000000000000000000000000000000000000000000,
		parameter       NOC_SECURE_RANGE2_VALID             = "NOC_SECURE_RANGE2_VALID_INVALID",
		parameter[63:0] NOC_SECURE_RANGE2_BASE              = 64'b0000000000000000000000000000000000000000000000000000000000000000,
		parameter       NOC_SECURE_RANGE2_SPAN              = "NOC_SECURE_RANGE2_MASK_128_MB",
		parameter[63:0] NOC_SECURE_RANGE2_WRITE_ACCESS_PRIV = 64'b0000000000000000000000000000000000000000000000000000000000000000,
		parameter[63:0] NOC_SECURE_RANGE2_READ_ACCESS_PRIV  = 64'b0000000000000000000000000000000000000000000000000000000000000000,
		parameter       NOC_SECURE_RANGE3_VALID             = "NOC_SECURE_RANGE3_VALID_INVALID",
		parameter[63:0] NOC_SECURE_RANGE3_BASE              = 64'b0000000000000000000000000000000000000000000000000000000000000000,
		parameter       NOC_SECURE_RANGE3_SPAN              = "NOC_SECURE_RANGE3_MASK_128_MB",
		parameter[63:0] NOC_SECURE_RANGE3_WRITE_ACCESS_PRIV = 64'b0000000000000000000000000000000000000000000000000000000000000000,
		parameter[63:0] NOC_SECURE_RANGE3_READ_ACCESS_PRIV  = 64'b0000000000000000000000000000000000000000000000000000000000000000,
		parameter       NOC_SECURE_RANGE4_VALID             = "NOC_SECURE_RANGE4_VALID_INVALID",
		parameter[63:0] NOC_SECURE_RANGE4_BASE              = 64'b0000000000000000000000000000000000000000000000000000000000000000,
		parameter       NOC_SECURE_RANGE4_SPAN              = "NOC_SECURE_RANGE4_MASK_128_MB",
		parameter[63:0] NOC_SECURE_RANGE4_WRITE_ACCESS_PRIV = 64'b0000000000000000000000000000000000000000000000000000000000000000,
		parameter[63:0] NOC_SECURE_RANGE4_READ_ACCESS_PRIV  = 64'b0000000000000000000000000000000000000000000000000000000000000000,
		parameter       NOC_SECURE_RANGE5_VALID             = "NOC_SECURE_RANGE5_VALID_INVALID",
		parameter[63:0] NOC_SECURE_RANGE5_BASE              = 64'b0000000000000000000000000000000000000000000000000000000000000000,
		parameter       NOC_SECURE_RANGE5_SPAN              = "NOC_SECURE_RANGE5_MASK_128_MB",
		parameter[63:0] NOC_SECURE_RANGE5_WRITE_ACCESS_PRIV = 64'b0000000000000000000000000000000000000000000000000000000000000000,
		parameter[63:0] NOC_SECURE_RANGE5_READ_ACCESS_PRIV  = 64'b0000000000000000000000000000000000000000000000000000000000000000,
		parameter       NOC_SECURE_RANGE6_VALID             = "NOC_SECURE_RANGE6_VALID_INVALID",
		parameter[63:0] NOC_SECURE_RANGE6_BASE              = 64'b0000000000000000000000000000000000000000000000000000000000000000,
		parameter       NOC_SECURE_RANGE6_SPAN              = "NOC_SECURE_RANGE6_MASK_128_MB",
		parameter[63:0] NOC_SECURE_RANGE6_WRITE_ACCESS_PRIV = 64'b0000000000000000000000000000000000000000000000000000000000000000,
		parameter[63:0] NOC_SECURE_RANGE6_READ_ACCESS_PRIV  = 64'b0000000000000000000000000000000000000000000000000000000000000000,
		parameter       NOC_SECURE_RANGE7_VALID             = "NOC_SECURE_RANGE7_VALID_INVALID",
		parameter[63:0] NOC_SECURE_RANGE7_BASE              = 64'b0000000000000000000000000000000000000000000000000000000000000000,
		parameter       NOC_SECURE_RANGE7_SPAN              = "NOC_SECURE_RANGE7_MASK_128_MB",
		parameter[63:0] NOC_SECURE_RANGE7_WRITE_ACCESS_PRIV = 64'b0000000000000000000000000000000000000000000000000000000000000000,
		parameter[63:0] NOC_SECURE_RANGE7_READ_ACCESS_PRIV  = 64'b0000000000000000000000000000000000000000000000000000000000000000
	) (
		input  wire         clk,              //               clk.clk
		input  wire         reset,            //             reset.reset
		output wire [6:0]   response_awid,    // altera_axi_master.awid
		output wire [39:0]  response_awaddr,  //                  .awaddr
		output wire [7:0]   response_awlen,   //                  .awlen
		output wire [2:0]   response_awsize,  //                  .awsize
		output wire [1:0]   response_awburst, //                  .awburst
		output wire         response_awlock,  //                  .awlock
		output wire [2:0]   response_awprot,  //                  .awprot
		output wire [13:0]  response_awuser,  //                  .awuser
		output wire         response_awvalid, //                  .awvalid
		input  wire         response_awready, //                  .awready
		output wire [3:0]   response_awqos,   //                  .awqos
		output wire [255:0] response_wdata,   //                  .wdata
		output wire [31:0]  response_wstrb,   //                  .wstrb
		output wire         response_wlast,   //                  .wlast
		output wire         response_wvalid,  //                  .wvalid
		input  wire         response_wready,  //                  .wready
		output wire [31:0]  response_wuser,   //                  .wuser
		input  wire [6:0]   response_bid,     //                  .bid
		input  wire [1:0]   response_bresp,   //                  .bresp
		input  wire         response_bvalid,  //                  .bvalid
		output wire         response_bready,  //                  .bready
		output wire [6:0]   response_arid,    //                  .arid
		output wire [39:0]  response_araddr,  //                  .araddr
		output wire [7:0]   response_arlen,   //                  .arlen
		output wire [2:0]   response_arsize,  //                  .arsize
		output wire [1:0]   response_arburst, //                  .arburst
		output wire         response_arlock,  //                  .arlock
		output wire [2:0]   response_arprot,  //                  .arprot
		output wire [13:0]  response_aruser,  //                  .aruser
		output wire         response_arvalid, //                  .arvalid
		input  wire         response_arready, //                  .arready
		output wire [3:0]   response_arqos,   //                  .arqos
		input  wire [6:0]   response_rid,     //                  .rid
		input  wire [255:0] response_rdata,   //                  .rdata
		input  wire [1:0]   response_rresp,   //                  .rresp
		input  wire         response_rlast,   //                  .rlast
		input  wire         response_rvalid,  //                  .rvalid
		output wire         response_rready,  //                  .rready
		input  wire [31:0]  response_ruser    //                  .ruser
	);

	generate
		// If any of the display statements (or deliberately broken
		// instantiations) within this generate block triggers then this module
		// has been instantiated this module with a set of parameters different
		// from those it was generated for.  This will usually result in a
		// non-functioning system.
		if (CHOOSE_AXI != "AXI4")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					choose_axi_check ( .error(1'b1) );
		end
		if (AXI_DATA_WIDTH != 256)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					axi_data_width_check ( .error(1'b1) );
		end
		if (NOC_TARGET_DFD_EN != "NOC_TARGET_DFD_EN_DISABLE")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_target_dfd_en_check ( .error(1'b1) );
		end
		if (NOC_EMIF_ADDR_MASK != "NOC_EMIF_ADDR_MASK_8_GB")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_emif_addr_mask_check ( .error(1'b1) );
		end
		if (NOC_TARGET_SIZE != "8_GB")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_target_size_check ( .error(1'b1) );
		end
		if (NOC_NON_USER_NIU != "DISABLE")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_non_user_niu_check ( .error(1'b1) );
		end
		if (NOC_ISOLATION_GROUP != "HPS_NOC_ISOLATION_GROUP")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_isolation_group_check ( .error(1'b1) );
		end
		if (NOC_TARGET_ECC_EN != "NOC_TARGET_ECC_EN_DISABLE")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_target_ecc_en_check ( .error(1'b1) );
		end
		if (NOC_SECURE_FILTER_ENA != "NOC_SECURE_FILTER_ENA_DISABLE")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_filter_ena_check ( .error(1'b1) );
		end
		if (AXI_ADDR_WIDTH != 40)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					axi_addr_width_check ( .error(1'b1) );
		end
		if (AXI_AUSER_WIDTH != 14)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					axi_auser_width_check ( .error(1'b1) );
		end
		if (AXI_USER_WIDTH != 32)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					axi_user_width_check ( .error(1'b1) );
		end
		if (AXI_ID_WIDTH != 7)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					axi_id_width_check ( .error(1'b1) );
		end
		if (AXI_WSTRB_WIDTH != 32)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					axi_wstrb_width_check ( .error(1'b1) );
		end
		if (POWERMODE_FREQ_HZ_NOC_TNIU_CLK != 32'b00100111101111001000011000000100)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					powermode_freq_hz_noc_tniu_clk_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE0_VALID != "NOC_SECURE_RANGE0_VALID_INVALID")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range0_valid_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE0_BASE != 64'b0000000000000000000000000000000000000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range0_base_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE0_SPAN != "NOC_SECURE_RANGE0_MASK_128_MB")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range0_span_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE0_WRITE_ACCESS_PRIV != 64'b0000000000000000000000000000000000000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range0_write_access_priv_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE0_READ_ACCESS_PRIV != 64'b0000000000000000000000000000000000000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range0_read_access_priv_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE1_VALID != "NOC_SECURE_RANGE1_VALID_INVALID")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range1_valid_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE1_BASE != 64'b0000000000000000000000000000000000000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range1_base_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE1_SPAN != "NOC_SECURE_RANGE1_MASK_128_MB")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range1_span_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE1_WRITE_ACCESS_PRIV != 64'b0000000000000000000000000000000000000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range1_write_access_priv_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE1_READ_ACCESS_PRIV != 64'b0000000000000000000000000000000000000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range1_read_access_priv_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE2_VALID != "NOC_SECURE_RANGE2_VALID_INVALID")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range2_valid_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE2_BASE != 64'b0000000000000000000000000000000000000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range2_base_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE2_SPAN != "NOC_SECURE_RANGE2_MASK_128_MB")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range2_span_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE2_WRITE_ACCESS_PRIV != 64'b0000000000000000000000000000000000000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range2_write_access_priv_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE2_READ_ACCESS_PRIV != 64'b0000000000000000000000000000000000000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range2_read_access_priv_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE3_VALID != "NOC_SECURE_RANGE3_VALID_INVALID")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range3_valid_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE3_BASE != 64'b0000000000000000000000000000000000000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range3_base_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE3_SPAN != "NOC_SECURE_RANGE3_MASK_128_MB")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range3_span_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE3_WRITE_ACCESS_PRIV != 64'b0000000000000000000000000000000000000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range3_write_access_priv_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE3_READ_ACCESS_PRIV != 64'b0000000000000000000000000000000000000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range3_read_access_priv_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE4_VALID != "NOC_SECURE_RANGE4_VALID_INVALID")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range4_valid_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE4_BASE != 64'b0000000000000000000000000000000000000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range4_base_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE4_SPAN != "NOC_SECURE_RANGE4_MASK_128_MB")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range4_span_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE4_WRITE_ACCESS_PRIV != 64'b0000000000000000000000000000000000000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range4_write_access_priv_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE4_READ_ACCESS_PRIV != 64'b0000000000000000000000000000000000000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range4_read_access_priv_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE5_VALID != "NOC_SECURE_RANGE5_VALID_INVALID")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range5_valid_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE5_BASE != 64'b0000000000000000000000000000000000000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range5_base_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE5_SPAN != "NOC_SECURE_RANGE5_MASK_128_MB")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range5_span_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE5_WRITE_ACCESS_PRIV != 64'b0000000000000000000000000000000000000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range5_write_access_priv_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE5_READ_ACCESS_PRIV != 64'b0000000000000000000000000000000000000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range5_read_access_priv_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE6_VALID != "NOC_SECURE_RANGE6_VALID_INVALID")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range6_valid_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE6_BASE != 64'b0000000000000000000000000000000000000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range6_base_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE6_SPAN != "NOC_SECURE_RANGE6_MASK_128_MB")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range6_span_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE6_WRITE_ACCESS_PRIV != 64'b0000000000000000000000000000000000000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range6_write_access_priv_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE6_READ_ACCESS_PRIV != 64'b0000000000000000000000000000000000000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range6_read_access_priv_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE7_VALID != "NOC_SECURE_RANGE7_VALID_INVALID")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range7_valid_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE7_BASE != 64'b0000000000000000000000000000000000000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range7_base_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE7_SPAN != "NOC_SECURE_RANGE7_MASK_128_MB")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range7_span_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE7_WRITE_ACCESS_PRIV != 64'b0000000000000000000000000000000000000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range7_write_access_priv_check ( .error(1'b1) );
		end
		if (NOC_SECURE_RANGE7_READ_ACCESS_PRIV != 64'b0000000000000000000000000000000000000000000000000000000000000000)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					noc_secure_range7_read_access_priv_check ( .error(1'b1) );
		end
	endgenerate

	platform_emif_io96b_hps_0_emif_io96b_hps_300_2mmae3q_emif_0_ddr4comp_intel_noc_target_210_hubzqoq #(
		.CHOOSE_AXI                          ("AXI4"),
		.AXI_DATA_WIDTH                      (256),
		.NOC_TARGET_DFD_EN                   ("NOC_TARGET_DFD_EN_DISABLE"),
		.NOC_EMIF_ADDR_MASK                  ("NOC_EMIF_ADDR_MASK_8_GB"),
		.NOC_TARGET_SIZE                     ("8_GB"),
		.NOC_NON_USER_NIU                    ("DISABLE"),
		.NOC_ISOLATION_GROUP                 ("HPS_NOC_ISOLATION_GROUP"),
		.NOC_TARGET_ECC_EN                   ("NOC_TARGET_ECC_EN_DISABLE"),
		.NOC_SECURE_FILTER_ENA               ("NOC_SECURE_FILTER_ENA_DISABLE"),
		.AXI_ADDR_WIDTH                      (40),
		.AXI_AUSER_WIDTH                     (14),
		.AXI_USER_WIDTH                      (32),
		.AXI_ID_WIDTH                        (7),
		.AXI_WSTRB_WIDTH                     (32),
		.POWERMODE_FREQ_HZ_NOC_TNIU_CLK      (32'b00100111101111001000011000000100),
		.NOC_SECURE_RANGE0_VALID             ("NOC_SECURE_RANGE0_VALID_INVALID"),
		.NOC_SECURE_RANGE0_BASE              (64'b0000000000000000000000000000000000000000000000000000000000000000),
		.NOC_SECURE_RANGE0_SPAN              ("NOC_SECURE_RANGE0_MASK_128_MB"),
		.NOC_SECURE_RANGE0_WRITE_ACCESS_PRIV (64'b0000000000000000000000000000000000000000000000000000000000000000),
		.NOC_SECURE_RANGE0_READ_ACCESS_PRIV  (64'b0000000000000000000000000000000000000000000000000000000000000000),
		.NOC_SECURE_RANGE1_VALID             ("NOC_SECURE_RANGE1_VALID_INVALID"),
		.NOC_SECURE_RANGE1_BASE              (64'b0000000000000000000000000000000000000000000000000000000000000000),
		.NOC_SECURE_RANGE1_SPAN              ("NOC_SECURE_RANGE1_MASK_128_MB"),
		.NOC_SECURE_RANGE1_WRITE_ACCESS_PRIV (64'b0000000000000000000000000000000000000000000000000000000000000000),
		.NOC_SECURE_RANGE1_READ_ACCESS_PRIV  (64'b0000000000000000000000000000000000000000000000000000000000000000),
		.NOC_SECURE_RANGE2_VALID             ("NOC_SECURE_RANGE2_VALID_INVALID"),
		.NOC_SECURE_RANGE2_BASE              (64'b0000000000000000000000000000000000000000000000000000000000000000),
		.NOC_SECURE_RANGE2_SPAN              ("NOC_SECURE_RANGE2_MASK_128_MB"),
		.NOC_SECURE_RANGE2_WRITE_ACCESS_PRIV (64'b0000000000000000000000000000000000000000000000000000000000000000),
		.NOC_SECURE_RANGE2_READ_ACCESS_PRIV  (64'b0000000000000000000000000000000000000000000000000000000000000000),
		.NOC_SECURE_RANGE3_VALID             ("NOC_SECURE_RANGE3_VALID_INVALID"),
		.NOC_SECURE_RANGE3_BASE              (64'b0000000000000000000000000000000000000000000000000000000000000000),
		.NOC_SECURE_RANGE3_SPAN              ("NOC_SECURE_RANGE3_MASK_128_MB"),
		.NOC_SECURE_RANGE3_WRITE_ACCESS_PRIV (64'b0000000000000000000000000000000000000000000000000000000000000000),
		.NOC_SECURE_RANGE3_READ_ACCESS_PRIV  (64'b0000000000000000000000000000000000000000000000000000000000000000),
		.NOC_SECURE_RANGE4_VALID             ("NOC_SECURE_RANGE4_VALID_INVALID"),
		.NOC_SECURE_RANGE4_BASE              (64'b0000000000000000000000000000000000000000000000000000000000000000),
		.NOC_SECURE_RANGE4_SPAN              ("NOC_SECURE_RANGE4_MASK_128_MB"),
		.NOC_SECURE_RANGE4_WRITE_ACCESS_PRIV (64'b0000000000000000000000000000000000000000000000000000000000000000),
		.NOC_SECURE_RANGE4_READ_ACCESS_PRIV  (64'b0000000000000000000000000000000000000000000000000000000000000000),
		.NOC_SECURE_RANGE5_VALID             ("NOC_SECURE_RANGE5_VALID_INVALID"),
		.NOC_SECURE_RANGE5_BASE              (64'b0000000000000000000000000000000000000000000000000000000000000000),
		.NOC_SECURE_RANGE5_SPAN              ("NOC_SECURE_RANGE5_MASK_128_MB"),
		.NOC_SECURE_RANGE5_WRITE_ACCESS_PRIV (64'b0000000000000000000000000000000000000000000000000000000000000000),
		.NOC_SECURE_RANGE5_READ_ACCESS_PRIV  (64'b0000000000000000000000000000000000000000000000000000000000000000),
		.NOC_SECURE_RANGE6_VALID             ("NOC_SECURE_RANGE6_VALID_INVALID"),
		.NOC_SECURE_RANGE6_BASE              (64'b0000000000000000000000000000000000000000000000000000000000000000),
		.NOC_SECURE_RANGE6_SPAN              ("NOC_SECURE_RANGE6_MASK_128_MB"),
		.NOC_SECURE_RANGE6_WRITE_ACCESS_PRIV (64'b0000000000000000000000000000000000000000000000000000000000000000),
		.NOC_SECURE_RANGE6_READ_ACCESS_PRIV  (64'b0000000000000000000000000000000000000000000000000000000000000000),
		.NOC_SECURE_RANGE7_VALID             ("NOC_SECURE_RANGE7_VALID_INVALID"),
		.NOC_SECURE_RANGE7_BASE              (64'b0000000000000000000000000000000000000000000000000000000000000000),
		.NOC_SECURE_RANGE7_SPAN              ("NOC_SECURE_RANGE7_MASK_128_MB"),
		.NOC_SECURE_RANGE7_WRITE_ACCESS_PRIV (64'b0000000000000000000000000000000000000000000000000000000000000000),
		.NOC_SECURE_RANGE7_READ_ACCESS_PRIV  (64'b0000000000000000000000000000000000000000000000000000000000000000)
	) tniu_0 (
		.clk              (clk),              //   input,    width = 1,               clk.clk
		.reset            (reset),            //   input,    width = 1,             reset.reset
		.response_awid    (response_awid),    //  output,    width = 7, altera_axi_master.awid
		.response_awaddr  (response_awaddr),  //  output,   width = 40,                  .awaddr
		.response_awlen   (response_awlen),   //  output,    width = 8,                  .awlen
		.response_awsize  (response_awsize),  //  output,    width = 3,                  .awsize
		.response_awburst (response_awburst), //  output,    width = 2,                  .awburst
		.response_awlock  (response_awlock),  //  output,    width = 1,                  .awlock
		.response_awprot  (response_awprot),  //  output,    width = 3,                  .awprot
		.response_awuser  (response_awuser),  //  output,   width = 14,                  .awuser
		.response_awvalid (response_awvalid), //  output,    width = 1,                  .awvalid
		.response_awready (response_awready), //   input,    width = 1,                  .awready
		.response_awqos   (response_awqos),   //  output,    width = 4,                  .awqos
		.response_wdata   (response_wdata),   //  output,  width = 256,                  .wdata
		.response_wstrb   (response_wstrb),   //  output,   width = 32,                  .wstrb
		.response_wlast   (response_wlast),   //  output,    width = 1,                  .wlast
		.response_wvalid  (response_wvalid),  //  output,    width = 1,                  .wvalid
		.response_wready  (response_wready),  //   input,    width = 1,                  .wready
		.response_wuser   (response_wuser),   //  output,   width = 32,                  .wuser
		.response_bid     (response_bid),     //   input,    width = 7,                  .bid
		.response_bresp   (response_bresp),   //   input,    width = 2,                  .bresp
		.response_bvalid  (response_bvalid),  //   input,    width = 1,                  .bvalid
		.response_bready  (response_bready),  //  output,    width = 1,                  .bready
		.response_arid    (response_arid),    //  output,    width = 7,                  .arid
		.response_araddr  (response_araddr),  //  output,   width = 40,                  .araddr
		.response_arlen   (response_arlen),   //  output,    width = 8,                  .arlen
		.response_arsize  (response_arsize),  //  output,    width = 3,                  .arsize
		.response_arburst (response_arburst), //  output,    width = 2,                  .arburst
		.response_arlock  (response_arlock),  //  output,    width = 1,                  .arlock
		.response_arprot  (response_arprot),  //  output,    width = 3,                  .arprot
		.response_aruser  (response_aruser),  //  output,   width = 14,                  .aruser
		.response_arvalid (response_arvalid), //  output,    width = 1,                  .arvalid
		.response_arready (response_arready), //   input,    width = 1,                  .arready
		.response_arqos   (response_arqos),   //  output,    width = 4,                  .arqos
		.response_rid     (response_rid),     //   input,    width = 7,                  .rid
		.response_rdata   (response_rdata),   //   input,  width = 256,                  .rdata
		.response_rresp   (response_rresp),   //   input,    width = 2,                  .rresp
		.response_rlast   (response_rlast),   //   input,    width = 1,                  .rlast
		.response_rvalid  (response_rvalid),  //   input,    width = 1,                  .rvalid
		.response_rready  (response_rready),  //  output,    width = 1,                  .rready
		.response_ruser   (response_ruser)    //   input,   width = 32,                  .ruser
	);

endmodule
