// platform_intel_agilex_hps_1.v

// Generated using ACDS version 25.1 129

`timescale 1 ps / 1 ps
module platform_intel_agilex_hps_1 (
		output wire         h2f_rst,       //           h2f_reset.reset
		input  wire         h2f_axi_clk,   //       h2f_axi_clock.clk
		input  wire         h2f_axi_rst_n, //       h2f_axi_reset.reset_n
		output wire [3:0]   h2f_AWID,      //      h2f_axi_master.awid
		output wire [31:0]  h2f_AWADDR,    //                    .awaddr
		output wire [7:0]   h2f_AWLEN,     //                    .awlen
		output wire [2:0]   h2f_AWSIZE,    //                    .awsize
		output wire [1:0]   h2f_AWBURST,   //                    .awburst
		output wire         h2f_AWLOCK,    //                    .awlock
		output wire [3:0]   h2f_AWCACHE,   //                    .awcache
		output wire [2:0]   h2f_AWPROT,    //                    .awprot
		output wire         h2f_AWVALID,   //                    .awvalid
		input  wire         h2f_AWREADY,   //                    .awready
		output wire [127:0] h2f_WDATA,     //                    .wdata
		output wire [15:0]  h2f_WSTRB,     //                    .wstrb
		output wire         h2f_WLAST,     //                    .wlast
		output wire         h2f_WVALID,    //                    .wvalid
		input  wire         h2f_WREADY,    //                    .wready
		input  wire [3:0]   h2f_BID,       //                    .bid
		input  wire [1:0]   h2f_BRESP,     //                    .bresp
		input  wire         h2f_BVALID,    //                    .bvalid
		output wire         h2f_BREADY,    //                    .bready
		output wire [3:0]   h2f_ARID,      //                    .arid
		output wire [31:0]  h2f_ARADDR,    //                    .araddr
		output wire [7:0]   h2f_ARLEN,     //                    .arlen
		output wire [2:0]   h2f_ARSIZE,    //                    .arsize
		output wire [1:0]   h2f_ARBURST,   //                    .arburst
		output wire         h2f_ARLOCK,    //                    .arlock
		output wire [3:0]   h2f_ARCACHE,   //                    .arcache
		output wire [2:0]   h2f_ARPROT,    //                    .arprot
		output wire         h2f_ARVALID,   //                    .arvalid
		input  wire         h2f_ARREADY,   //                    .arready
		input  wire [3:0]   h2f_RID,       //                    .rid
		input  wire [127:0] h2f_RDATA,     //                    .rdata
		input  wire [1:0]   h2f_RRESP,     //                    .rresp
		input  wire         h2f_RLAST,     //                    .rlast
		input  wire         h2f_RVALID,    //                    .rvalid
		output wire         h2f_RREADY,    //                    .rready
		output wire         NAND_ALE,      //              hps_io.NAND_ALE
		output wire         NAND_CE_N,     //                    .NAND_CE_N
		output wire         NAND_CLE,      //                    .NAND_CLE
		output wire         NAND_RE_N,     //                    .NAND_RE_N
		input  wire         NAND_RB,       //                    .NAND_RB
		inout  wire         NAND_ADQ0,     //                    .NAND_ADQ0
		inout  wire         NAND_ADQ1,     //                    .NAND_ADQ1
		inout  wire         NAND_ADQ2,     //                    .NAND_ADQ2
		inout  wire         NAND_ADQ3,     //                    .NAND_ADQ3
		inout  wire         NAND_ADQ4,     //                    .NAND_ADQ4
		inout  wire         NAND_ADQ5,     //                    .NAND_ADQ5
		inout  wire         NAND_ADQ6,     //                    .NAND_ADQ6
		inout  wire         NAND_ADQ7,     //                    .NAND_ADQ7
		output wire         NAND_WP_N,     //                    .NAND_WP_N
		output wire         NAND_WE_N,     //                    .NAND_WE_N
		input  wire         UART0_RX,      //                    .UART0_RX
		output wire         UART0_TX,      //                    .UART0_TX
		input  wire         hps_osc_clk    //                    .hps_osc_clk
	);

	platform_intel_agilex_hps_1_intel_agilex_hps_2400_tvjph2i hps (
		.h2f_rst       (h2f_rst),       //  output,    width = 1,      h2f_reset.reset
		.h2f_axi_clk   (h2f_axi_clk),   //   input,    width = 1,  h2f_axi_clock.clk
		.h2f_axi_rst_n (h2f_axi_rst_n), //   input,    width = 1,  h2f_axi_reset.reset_n
		.h2f_AWID      (h2f_AWID),      //  output,    width = 4, h2f_axi_master.awid
		.h2f_AWADDR    (h2f_AWADDR),    //  output,   width = 32,               .awaddr
		.h2f_AWLEN     (h2f_AWLEN),     //  output,    width = 8,               .awlen
		.h2f_AWSIZE    (h2f_AWSIZE),    //  output,    width = 3,               .awsize
		.h2f_AWBURST   (h2f_AWBURST),   //  output,    width = 2,               .awburst
		.h2f_AWLOCK    (h2f_AWLOCK),    //  output,    width = 1,               .awlock
		.h2f_AWCACHE   (h2f_AWCACHE),   //  output,    width = 4,               .awcache
		.h2f_AWPROT    (h2f_AWPROT),    //  output,    width = 3,               .awprot
		.h2f_AWVALID   (h2f_AWVALID),   //  output,    width = 1,               .awvalid
		.h2f_AWREADY   (h2f_AWREADY),   //   input,    width = 1,               .awready
		.h2f_WDATA     (h2f_WDATA),     //  output,  width = 128,               .wdata
		.h2f_WSTRB     (h2f_WSTRB),     //  output,   width = 16,               .wstrb
		.h2f_WLAST     (h2f_WLAST),     //  output,    width = 1,               .wlast
		.h2f_WVALID    (h2f_WVALID),    //  output,    width = 1,               .wvalid
		.h2f_WREADY    (h2f_WREADY),    //   input,    width = 1,               .wready
		.h2f_BID       (h2f_BID),       //   input,    width = 4,               .bid
		.h2f_BRESP     (h2f_BRESP),     //   input,    width = 2,               .bresp
		.h2f_BVALID    (h2f_BVALID),    //   input,    width = 1,               .bvalid
		.h2f_BREADY    (h2f_BREADY),    //  output,    width = 1,               .bready
		.h2f_ARID      (h2f_ARID),      //  output,    width = 4,               .arid
		.h2f_ARADDR    (h2f_ARADDR),    //  output,   width = 32,               .araddr
		.h2f_ARLEN     (h2f_ARLEN),     //  output,    width = 8,               .arlen
		.h2f_ARSIZE    (h2f_ARSIZE),    //  output,    width = 3,               .arsize
		.h2f_ARBURST   (h2f_ARBURST),   //  output,    width = 2,               .arburst
		.h2f_ARLOCK    (h2f_ARLOCK),    //  output,    width = 1,               .arlock
		.h2f_ARCACHE   (h2f_ARCACHE),   //  output,    width = 4,               .arcache
		.h2f_ARPROT    (h2f_ARPROT),    //  output,    width = 3,               .arprot
		.h2f_ARVALID   (h2f_ARVALID),   //  output,    width = 1,               .arvalid
		.h2f_ARREADY   (h2f_ARREADY),   //   input,    width = 1,               .arready
		.h2f_RID       (h2f_RID),       //   input,    width = 4,               .rid
		.h2f_RDATA     (h2f_RDATA),     //   input,  width = 128,               .rdata
		.h2f_RRESP     (h2f_RRESP),     //   input,    width = 2,               .rresp
		.h2f_RLAST     (h2f_RLAST),     //   input,    width = 1,               .rlast
		.h2f_RVALID    (h2f_RVALID),    //   input,    width = 1,               .rvalid
		.h2f_RREADY    (h2f_RREADY),    //  output,    width = 1,               .rready
		.NAND_ALE      (NAND_ALE),      //  output,    width = 1,         hps_io.NAND_ALE
		.NAND_CE_N     (NAND_CE_N),     //  output,    width = 1,               .NAND_CE_N
		.NAND_CLE      (NAND_CLE),      //  output,    width = 1,               .NAND_CLE
		.NAND_RE_N     (NAND_RE_N),     //  output,    width = 1,               .NAND_RE_N
		.NAND_RB       (NAND_RB),       //   input,    width = 1,               .NAND_RB
		.NAND_ADQ0     (NAND_ADQ0),     //   inout,    width = 1,               .NAND_ADQ0
		.NAND_ADQ1     (NAND_ADQ1),     //   inout,    width = 1,               .NAND_ADQ1
		.NAND_ADQ2     (NAND_ADQ2),     //   inout,    width = 1,               .NAND_ADQ2
		.NAND_ADQ3     (NAND_ADQ3),     //   inout,    width = 1,               .NAND_ADQ3
		.NAND_ADQ4     (NAND_ADQ4),     //   inout,    width = 1,               .NAND_ADQ4
		.NAND_ADQ5     (NAND_ADQ5),     //   inout,    width = 1,               .NAND_ADQ5
		.NAND_ADQ6     (NAND_ADQ6),     //   inout,    width = 1,               .NAND_ADQ6
		.NAND_ADQ7     (NAND_ADQ7),     //   inout,    width = 1,               .NAND_ADQ7
		.NAND_WP_N     (NAND_WP_N),     //  output,    width = 1,               .NAND_WP_N
		.NAND_WE_N     (NAND_WE_N),     //  output,    width = 1,               .NAND_WE_N
		.UART0_RX      (UART0_RX),      //   input,    width = 1,               .UART0_RX
		.UART0_TX      (UART0_TX),      //  output,    width = 1,               .UART0_TX
		.hps_osc_clk   (hps_osc_clk)    //   input,    width = 1,               .hps_osc_clk
	);

endmodule
