// platform_reset_bridge_1.v

// Generated using ACDS version 25.1 129

`timescale 1 ps / 1 ps
module platform_reset_bridge_1 (
		input  wire  clk,       //       clk.clk,   Clock Input
		input  wire  in_reset,  //  in_reset.reset, Reset Input
		output wire  out_reset  // out_reset.reset, Reset Output
	);

	assign out_reset = in_reset;

endmodule
