
namespace eval platform_intel_rtile_pcie_ast_0 {
  proc get_design_libraries {} {
    set libraries [dict create]
    dict set libraries altera_s10_configuration_clock_1916 1
    dict set libraries intel_rtile_pcie_ast_1160           1
    dict set libraries platform_intel_rtile_pcie_ast_0     1
    return $libraries
  }
  
  proc get_memory_files {QSYS_SIMDIR QUARTUS_INSTALL_DIR} {
    set memory_files [list]
    return $memory_files
  }
  
  proc get_common_design_files {QSYS_SIMDIR} {
    set design_files [dict create]
    return $design_files
  }
  
  proc get_design_files {QSYS_SIMDIR QUARTUS_INSTALL_DIR} {
    set design_files [list]
    lappend design_files "-makelib altera_s10_configuration_clock_1916 \"[normalize_path "$QSYS_SIMDIR/../altera_s10_configuration_clock_1916/sim/altera_s10_configuration_clock.v"]\"   -end"                                                                                                                         
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/s10_configuration_clock_0.v"]\"   -end"                                                                                                                                                  
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/rnr_pcie_csbb_gasket.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                               
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/rnr_pcie_soft_rx_wrapper.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                           
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/rnr_pcie_data_skew_sim.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                             
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/rnr_pcie_soft_tx_wrapper.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                           
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/rnr_pcie_tx_dsk_m_gen_24_chnl.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                      
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/rnr_pcie_tx_dsk_m_gen.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                              
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/rnr_pcie_rx_aib_deskew_datapipe.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                    
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/rnr_pcie_rx_aib_deskew_sm.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                          
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/rnr_pcie_rx_aib_deskew.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                             
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/rnr_pcie_ptm_deser.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                                 
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/rnr_pcie_reset_ctrl.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                                
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/rnr_pcie_reset_tree.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                                
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/gf_clkmux.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                                          
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/rnr_pcie_ehp_wrapper.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                           
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/rnr_pcie_ehp_tx_deallocate_ctr.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                 
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/pack/rnr_pcie_ehp_tx_empty_x16.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                 
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/pack/rnr_pcie_ehp_tx_empty_x8.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                  
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/pack/rnr_pcie_ehp_tx_empty_x8sw.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/pack/rnr_pcie_ehp_pack_lut.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                     
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/pack/rnr_pcie_ehp_pack_lut_16sw.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/pack/rnr_pcie_ehp_pack_lut_x8.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                  
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/pack/rnr_pcie_ehp_pack_lut_x8sw.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/pack/rnr_pcie_ehp_pack_lut_x4.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                  
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/pack/rnr_pcie_ehp_pack_lut_x4sw.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/unpack/rnr_pcie_ehp_unpack_data_segment_mux.v"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                     
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/unpack/rnr_pcie_ehp_unpack_data_segment.v"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                         
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/unpack/rnr_pcie_ehp_unpack_data_valids.v"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                          
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/unpack/rnr_pcie_ehp_unpack_eop_2_handling.v"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                       
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/unpack/rnr_pcie_ehp_unpack_eop_dwpos.v"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                            
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/unpack/rnr_pcie_ehp_unpack_frame_aligner.v"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                        
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/unpack/rnr_pcie_ehp_unpack_header_eop.v"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                           
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/unpack/rnr_pcie_ehp_unpack_header_segment.v"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                       
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/unpack/rnr_pcie_ehp_unpack_header_sidebands.v"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                     
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/unpack/rnr_pcie_ehp_unpack_header_valid.v"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                         
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/unpack/rnr_pcie_ehp_unpack_segment_decoding.v"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                     
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/unpack/rnr_pcie_ehp_unpack_wrapper.v"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                              
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/unpack/rnr_pcie_ehp_unpack_wrapper_x8.v"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                           
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/unpack/rnr_pcie_ehp_unpack_shift_segment.v"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                        
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/unpack/rnr_pcie_ehp_unpack_mux_out.v"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                              
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/unpack/rnr_pcie_ehp_unpack_wrapper_x4.v"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                           
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/unpack/rnr_pcie_ehp_unpack_mux_out_x4.v"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                           
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/unpack/rnr_pcie_ehp_unpack_wrapper_x16_sw.v"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                       
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/unpack/rnr_pcie_ehp_unpack_wrapper_x8_sw.v"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                        
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/unpack/rnr_pcie_ehp_unpack_wrapper_x4_sw.v"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                        
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/direct/rnr_rate_change_control.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                     
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/direct/rnr_avmm_reconfig.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                           
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/direct/rnr_pipe_direct_rate_change_control.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                         
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/csb/rnr_pcie_cii_ari_decode.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                        
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/csb/rnr_pcie_cii_workaround.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                        
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/csb/rnr_pcie_qhip_req_ovr.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                          
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/altera_std_synchronizer_nocut.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                  
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/rnr_simple_fifo.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                                
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lutlen0.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                                        
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lutlen1.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                                        
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lutlen2.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                                        
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lutlen3.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                                        
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lutlen4.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                                        
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lutlen5.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                                        
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lutlen6.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                                        
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lutlen7.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                                        
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lutlen0_x8.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                                     
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lutlen1_x8.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                                     
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lutlen2_x8.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                                     
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lutlen3_x8.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                                     
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lutlen0_x4.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                                     
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lutlen1_x4.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                                     
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lutlen0_16sw.v"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                                    
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lutlen1_16sw.v"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                                    
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lutlen2_16sw.v"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                                    
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lutlen3_16sw.v"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                                    
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lutlen0_x8sw.v"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                                    
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lutlen1_x8sw.v"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                                    
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lut0_lut.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                                       
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lut1_lut.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                                       
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lut2_lut.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                                       
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lut3_lut.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                                       
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lut4_lut.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                                       
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lut5_lut.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                                       
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lut6_lut.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                                       
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lut7_lut.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                                       
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lut0_x8_lut.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                                    
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lut1_x8_lut.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                                    
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lut2_x8_lut.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                                    
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lut3_x8_lut.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                                    
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lut0_x4_lut.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                                    
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lut1_x4_lut.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                                    
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lut0_lut_sw.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                                    
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lut1_lut_sw.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                                    
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lut2_lut_sw.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                                    
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lut3_lut_sw.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                                    
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lut0_x8_lut_sw.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                                 
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lut1_x8_lut_sw.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                                 
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_pcie_sts_clr_workaround.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_com_mcsb.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                       
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_com_tcsb.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                       
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_csb_pkg.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                                
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_apperr2csb.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                     
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_avmm2csb.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                       
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_csb2cii.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                        
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_csb2cplto.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                      
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_csb2pcicfg.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                     
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_pcie_csb2serr.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                  
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_pcie_csb2vferr.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                 
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_csb_adaptor.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                    
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_csbcgcgu.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                       
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_csbcism.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                        
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_csbcport.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                       
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_csbebase.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                       
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_csbendpoint.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                    
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_csbep_wrapper.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                  
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_flr2csb.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                        
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_pcie_int2csb.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                   
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_pcie_pm2csb.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                    
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_pcie_prs2csb.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                   
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_user_avmm_adapter.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                              
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_pulsesync.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                      
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_pcie_vw2csb.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                    
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_csb_common_module.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                      
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_mux2.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                                   
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_com_syncfifo.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                           
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_csbcasyncclkreq.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                        
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_csbcasyncfifo_egr.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                      
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_csbcasyncfifo_ing.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                      
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_csbcasyncfifo.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                          
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_csbccomp.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                               
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_csbcegress.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                             
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_csb_cfgif.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                              
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_csbcfifo.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                               
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_csbcingress.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                            
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_csbcinqueue.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                            
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_csbcusync_clk1.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                         
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_csbcusync_clk2.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                         
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_csbebulkrdwr.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                           
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_csbebulkrdwrwrapper.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                    
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_csbebytecount.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                          
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_csbedoserrmstr.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                         
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_csbehierinsert.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                         
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_csbemstrreg.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                            
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_csbemstr.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                               
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_csbetregsplitter.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                       
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_csbetrgtreg.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                            
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_csbetrgt.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                               
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_cxl_csb2aermsg.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                 
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_cxl_csb2cfgupdate.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                              
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_cxl_pm2csb.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                     
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_cxl_csb2hiperr.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                 
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_divclk.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                                 
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/virtio/rnr_pcie_virtio_rdwr_ctrl.v"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                    
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/virtio/rnr_pcie_virtio_cfg_access_cap.v"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                               
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/virtio/rnr_pcie_virtio_dataflow.v"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                     
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/virtio/rnr_pcie_virtio_cfgmnt.v"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                       
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/virtio/rnr_pcie_virtio_addrdc.v"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                       
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/virtio/rnr_pcie_virtio_top.v"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                          
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/virtio/rnr_pcie_virtio_cap_pfvfreg.v"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                                                  
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/platform_intel_rtile_pcie_ast_0_intel_rtile_pcie_ast_1160_tmhwjla.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"                            
    lappend design_files "-makelib intel_rtile_pcie_ast_1160 \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/rnr_pcie_soft_rx_tx_wrapper_platform_intel_rtile_pcie_ast_0_intel_rtile_pcie_ast_1160_tmhwjla.sv"]\" \"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"  -end"
    lappend design_files "-makelib platform_intel_rtile_pcie_ast_0 \"[normalize_path "$QSYS_SIMDIR/platform_intel_rtile_pcie_ast_0.v"]\"   -end"                                                                                                                                                                       
    return $design_files
  }
  
  proc get_non_duplicate_elab_option {ELAB_OPTIONS NEW_ELAB_OPTION} {
    set IS_DUPLICATE [string first $NEW_ELAB_OPTION $ELAB_OPTIONS]
    if {$IS_DUPLICATE == -1} {
      return $NEW_ELAB_OPTION
    } else {
      return ""
    }
  }
  
  
  proc get_elab_options {SIMULATOR_TOOL_BITNESS} {
    set ELAB_OPTIONS ""
    if ![ string match "bit_64" $SIMULATOR_TOOL_BITNESS ] {
    } else {
      append ELAB_OPTIONS {  -voptargs=-noprotectopt -suppress 7063\,7061\,3009\,3053\,12003\,8630\,12023\,8604\,3839\,7033 -nocvg}
    }
    return $ELAB_OPTIONS
  }
  
  
  proc get_sim_options {SIMULATOR_TOOL_BITNESS} {
    set SIM_OPTIONS ""
    if ![ string match "bit_64" $SIMULATOR_TOOL_BITNESS ] {
    } else {
    }
    return $SIM_OPTIONS
  }
  
  
  proc get_env_variables {SIMULATOR_TOOL_BITNESS} {
    set ENV_VARIABLES [dict create]
    set LD_LIBRARY_PATH [dict create]
    dict set ENV_VARIABLES "LD_LIBRARY_PATH" $LD_LIBRARY_PATH
    if ![ string match "bit_64" $SIMULATOR_TOOL_BITNESS ] {
    } else {
    }
    return $ENV_VARIABLES
  }
  
  
  proc normalize_path {FILEPATH} {
      if {[catch { package require fileutil } err]} { 
          return $FILEPATH 
      } 
      set path [fileutil::lexnormalize [file join [pwd] $FILEPATH]]  
      if {[file pathtype $FILEPATH] eq "relative"} { 
          set path [fileutil::relative [pwd] $path] 
      } 
      return $path 
  } 
  proc get_dpi_libraries {QSYS_SIMDIR} {
    set libraries [dict create]
    
    return $libraries
  }
  
}
