
namespace eval platform_intel_rtile_pcie_ast_0 {
  proc get_design_libraries {} {
    set libraries [dict create]
    dict set libraries altera_s10_configuration_clock_1916 1
    dict set libraries intel_rtile_pcie_ast_1160           1
    dict set libraries platform_intel_rtile_pcie_ast_0     1
    return $libraries
  }
  
  proc get_memory_files {QSYS_SIMDIR QUARTUS_INSTALL_DIR} {
    set memory_files [list]
    return $memory_files
  }
  
  proc get_common_design_files {USER_DEFINED_COMPILE_OPTIONS USER_DEFINED_VERILOG_COMPILE_OPTIONS USER_DEFINED_VHDL_COMPILE_OPTIONS QSYS_SIMDIR} {
    set design_files [dict create]
    return $design_files
  }
  
  proc get_design_files {USER_DEFINED_COMPILE_OPTIONS USER_DEFINED_VERILOG_COMPILE_OPTIONS USER_DEFINED_VHDL_COMPILE_OPTIONS QSYS_SIMDIR QUARTUS_INSTALL_DIR} {
    set design_files [list]
    lappend design_files "vlog -v2k5 $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../altera_s10_configuration_clock_1916/sim/altera_s10_configuration_clock.v"]\"  -work altera_s10_configuration_clock_1916"                                                                                                                      
    lappend design_files "vlog -v2k5 $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/s10_configuration_clock_0.v"]\"  -work intel_rtile_pcie_ast_1160"                                                                                                                                               
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/rnr_pcie_csbb_gasket.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                               
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/rnr_pcie_soft_rx_wrapper.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                           
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/rnr_pcie_data_skew_sim.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                             
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/rnr_pcie_soft_tx_wrapper.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                           
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/rnr_pcie_tx_dsk_m_gen_24_chnl.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                      
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/rnr_pcie_tx_dsk_m_gen.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                              
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/rnr_pcie_rx_aib_deskew_datapipe.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                    
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/rnr_pcie_rx_aib_deskew_sm.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                          
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/rnr_pcie_rx_aib_deskew.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                             
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/rnr_pcie_ptm_deser.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                                 
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/rnr_pcie_reset_ctrl.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                                
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/rnr_pcie_reset_tree.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                                
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/gf_clkmux.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                                          
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/rnr_pcie_ehp_wrapper.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                           
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/rnr_pcie_ehp_tx_deallocate_ctr.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                 
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/pack/rnr_pcie_ehp_tx_empty_x16.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                 
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/pack/rnr_pcie_ehp_tx_empty_x8.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                  
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/pack/rnr_pcie_ehp_tx_empty_x8sw.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/pack/rnr_pcie_ehp_pack_lut.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                     
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/pack/rnr_pcie_ehp_pack_lut_16sw.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/pack/rnr_pcie_ehp_pack_lut_x8.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                  
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/pack/rnr_pcie_ehp_pack_lut_x8sw.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/pack/rnr_pcie_ehp_pack_lut_x4.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                  
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/pack/rnr_pcie_ehp_pack_lut_x4sw.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/unpack/rnr_pcie_ehp_unpack_data_segment_mux.v"]\"  -work intel_rtile_pcie_ast_1160"                                     
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/unpack/rnr_pcie_ehp_unpack_data_segment.v"]\"  -work intel_rtile_pcie_ast_1160"                                         
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/unpack/rnr_pcie_ehp_unpack_data_valids.v"]\"  -work intel_rtile_pcie_ast_1160"                                          
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/unpack/rnr_pcie_ehp_unpack_eop_2_handling.v"]\"  -work intel_rtile_pcie_ast_1160"                                       
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/unpack/rnr_pcie_ehp_unpack_eop_dwpos.v"]\"  -work intel_rtile_pcie_ast_1160"                                            
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/unpack/rnr_pcie_ehp_unpack_frame_aligner.v"]\"  -work intel_rtile_pcie_ast_1160"                                        
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/unpack/rnr_pcie_ehp_unpack_header_eop.v"]\"  -work intel_rtile_pcie_ast_1160"                                           
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/unpack/rnr_pcie_ehp_unpack_header_segment.v"]\"  -work intel_rtile_pcie_ast_1160"                                       
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/unpack/rnr_pcie_ehp_unpack_header_sidebands.v"]\"  -work intel_rtile_pcie_ast_1160"                                     
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/unpack/rnr_pcie_ehp_unpack_header_valid.v"]\"  -work intel_rtile_pcie_ast_1160"                                         
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/unpack/rnr_pcie_ehp_unpack_segment_decoding.v"]\"  -work intel_rtile_pcie_ast_1160"                                     
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/unpack/rnr_pcie_ehp_unpack_wrapper.v"]\"  -work intel_rtile_pcie_ast_1160"                                              
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/unpack/rnr_pcie_ehp_unpack_wrapper_x8.v"]\"  -work intel_rtile_pcie_ast_1160"                                           
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/unpack/rnr_pcie_ehp_unpack_shift_segment.v"]\"  -work intel_rtile_pcie_ast_1160"                                        
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/unpack/rnr_pcie_ehp_unpack_mux_out.v"]\"  -work intel_rtile_pcie_ast_1160"                                              
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/unpack/rnr_pcie_ehp_unpack_wrapper_x4.v"]\"  -work intel_rtile_pcie_ast_1160"                                           
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/unpack/rnr_pcie_ehp_unpack_mux_out_x4.v"]\"  -work intel_rtile_pcie_ast_1160"                                           
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/unpack/rnr_pcie_ehp_unpack_wrapper_x16_sw.v"]\"  -work intel_rtile_pcie_ast_1160"                                       
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/unpack/rnr_pcie_ehp_unpack_wrapper_x8_sw.v"]\"  -work intel_rtile_pcie_ast_1160"                                        
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/ehp/unpack/rnr_pcie_ehp_unpack_wrapper_x4_sw.v"]\"  -work intel_rtile_pcie_ast_1160"                                        
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/direct/rnr_rate_change_control.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                     
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/direct/rnr_avmm_reconfig.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                           
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/direct/rnr_pipe_direct_rate_change_control.sv"]\"  -work intel_rtile_pcie_ast_1160"                                         
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/csb/rnr_pcie_cii_ari_decode.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                        
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/csb/rnr_pcie_cii_workaround.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                        
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/csb/rnr_pcie_qhip_req_ovr.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                          
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/altera_std_synchronizer_nocut.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                  
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/rnr_simple_fifo.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                                
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lutlen0.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                                        
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lutlen1.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                                        
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lutlen2.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                                        
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lutlen3.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                                        
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lutlen4.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                                        
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lutlen5.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                                        
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lutlen6.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                                        
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lutlen7.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                                        
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lutlen0_x8.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                                     
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lutlen1_x8.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                                     
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lutlen2_x8.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                                     
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lutlen3_x8.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                                     
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lutlen0_x4.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                                     
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lutlen1_x4.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                                     
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lutlen0_16sw.v"]\"  -work intel_rtile_pcie_ast_1160"                                                                    
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lutlen1_16sw.v"]\"  -work intel_rtile_pcie_ast_1160"                                                                    
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lutlen2_16sw.v"]\"  -work intel_rtile_pcie_ast_1160"                                                                    
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lutlen3_16sw.v"]\"  -work intel_rtile_pcie_ast_1160"                                                                    
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lutlen0_x8sw.v"]\"  -work intel_rtile_pcie_ast_1160"                                                                    
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lutlen1_x8sw.v"]\"  -work intel_rtile_pcie_ast_1160"                                                                    
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lut0_lut.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                                       
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lut1_lut.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                                       
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lut2_lut.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                                       
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lut3_lut.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                                       
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lut4_lut.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                                       
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lut5_lut.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                                       
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lut6_lut.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                                       
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lut7_lut.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                                       
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lut0_x8_lut.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                                    
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lut1_x8_lut.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                                    
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lut2_x8_lut.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                                    
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lut3_x8_lut.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                                    
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lut0_x4_lut.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                                    
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lut1_x4_lut.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                                    
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lut0_lut_sw.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                                    
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lut1_lut_sw.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                                    
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lut2_lut_sw.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                                    
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lut3_lut_sw.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                                    
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lut0_x8_lut_sw.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                                 
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/lut1_x8_lut_sw.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                                 
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_pcie_sts_clr_workaround.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_com_mcsb.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                       
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_com_tcsb.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                       
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_csb_pkg.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                                
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_apperr2csb.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                     
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_avmm2csb.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                       
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_csb2cii.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                        
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_csb2cplto.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                      
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_csb2pcicfg.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                     
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_pcie_csb2serr.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                  
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_pcie_csb2vferr.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                 
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_csb_adaptor.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                    
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_csbcgcgu.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                       
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_csbcism.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                        
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_csbcport.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                       
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_csbebase.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                       
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_csbendpoint.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                    
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_csbep_wrapper.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                  
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_flr2csb.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                        
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_pcie_int2csb.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                   
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_pcie_pm2csb.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                    
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_pcie_prs2csb.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                   
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_user_avmm_adapter.sv"]\"  -work intel_rtile_pcie_ast_1160"                                              
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_pulsesync.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                      
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_pcie_vw2csb.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                    
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_csb_common_module.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                      
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_mux2.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                                   
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_com_syncfifo.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                           
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_csbcasyncclkreq.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                        
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_csbcasyncfifo_egr.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                      
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_csbcasyncfifo_ing.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                      
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_csbcasyncfifo.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                          
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_csbccomp.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                               
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_csbcegress.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                             
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_csb_cfgif.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                              
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_csbcfifo.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                               
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_csbcingress.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                            
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_csbcinqueue.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                            
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_csbcusync_clk1.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                         
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_csbcusync_clk2.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                         
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_csbebulkrdwr.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                           
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_csbebulkrdwrwrapper.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                    
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_csbebytecount.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                          
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_csbedoserrmstr.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                         
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_csbehierinsert.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                         
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_csbemstrreg.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                            
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_csbemstr.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                               
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_csbetregsplitter.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                       
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_csbetrgtreg.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                            
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_csbetrgt.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                               
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_cxl_csb2aermsg.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                 
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_cxl_csb2cfgupdate.sv"]\"  -work intel_rtile_pcie_ast_1160"                                              
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_cxl_pm2csb.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                     
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/intel_rtile_cxl_csb2hiperr.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                 
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/cmn/csb/rnr_divclk.sv"]\"  -work intel_rtile_pcie_ast_1160"                                                                 
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/virtio/rnr_pcie_virtio_rdwr_ctrl.v"]\"  -work intel_rtile_pcie_ast_1160"                                                    
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/virtio/rnr_pcie_virtio_cfg_access_cap.v"]\"  -work intel_rtile_pcie_ast_1160"                                               
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/virtio/rnr_pcie_virtio_dataflow.v"]\"  -work intel_rtile_pcie_ast_1160"                                                     
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/virtio/rnr_pcie_virtio_cfgmnt.v"]\"  -work intel_rtile_pcie_ast_1160"                                                       
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/virtio/rnr_pcie_virtio_addrdc.v"]\"  -work intel_rtile_pcie_ast_1160"                                                       
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/virtio/rnr_pcie_virtio_top.v"]\"  -work intel_rtile_pcie_ast_1160"                                                          
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/intelfpga/virtio/rnr_pcie_virtio_cap_pfvfreg.v"]\"  -work intel_rtile_pcie_ast_1160"                                                  
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/platform_intel_rtile_pcie_ast_0_intel_rtile_pcie_ast_1160_tmhwjla.sv"]\"  -work intel_rtile_pcie_ast_1160"                            
    lappend design_files "vlog  $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS {\"+incdir+[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/"]\"} \"[normalize_path "$QSYS_SIMDIR/../intel_rtile_pcie_ast_1160/sim/rnr_pcie_soft_rx_tx_wrapper_platform_intel_rtile_pcie_ast_0_intel_rtile_pcie_ast_1160_tmhwjla.sv"]\"  -work intel_rtile_pcie_ast_1160"
    lappend design_files "vlog -v2k5 $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/platform_intel_rtile_pcie_ast_0.v"]\"  -work platform_intel_rtile_pcie_ast_0"                                                                                                                                                                    
    return $design_files
  }
  
  proc get_non_duplicate_elab_option {ELAB_OPTIONS NEW_ELAB_OPTION} {
    set IS_DUPLICATE [string first $NEW_ELAB_OPTION $ELAB_OPTIONS]
    if {$IS_DUPLICATE == -1} {
      return $NEW_ELAB_OPTION
    } else {
      return ""
    }
  }
  
  
  proc get_elab_options {SIMULATOR_TOOL_BITNESS} {
    set ELAB_OPTIONS ""
    if ![ string match "bit_64" $SIMULATOR_TOOL_BITNESS ] {
    } else {
    }
    return $ELAB_OPTIONS
  }
  
  
  proc get_sim_options {SIMULATOR_TOOL_BITNESS} {
    set SIM_OPTIONS ""
    if ![ string match "bit_64" $SIMULATOR_TOOL_BITNESS ] {
    } else {
    }
    return $SIM_OPTIONS
  }
  
  
  proc get_env_variables {SIMULATOR_TOOL_BITNESS} {
    set ENV_VARIABLES [dict create]
    set LD_LIBRARY_PATH [dict create]
    dict set ENV_VARIABLES "LD_LIBRARY_PATH" $LD_LIBRARY_PATH
    if ![ string match "bit_64" $SIMULATOR_TOOL_BITNESS ] {
    } else {
    }
    return $ENV_VARIABLES
  }
  
  
  proc normalize_path {FILEPATH} {
      if {[catch { package require fileutil } err]} { 
          return $FILEPATH 
      } 
      set path [fileutil::lexnormalize [file join [pwd] $FILEPATH]]  
      if {[file pathtype $FILEPATH] eq "relative"} { 
          set path [fileutil::relative [pwd] $path] 
      } 
      return $path 
  } 
  proc get_dpi_libraries {QSYS_SIMDIR} {
    set libraries [dict create]
    
    return $libraries
  }
  
}
