// platform_emif_io96b_hps_0.v

// Generated using ACDS version 25.1 129

`timescale 1 ps / 1 ps
module platform_emif_io96b_hps_0 (
		output wire [0:0]  mem_0_cke,     //              mem_0.mem_cke
		output wire [0:0]  mem_0_odt,     //                   .mem_odt
		output wire [0:0]  mem_0_cs_n,    //                   .mem_cs_n
		output wire [16:0] mem_0_a,       //                   .mem_a
		output wire [1:0]  mem_0_ba,      //                   .mem_ba
		output wire [0:0]  mem_0_bg,      //                   .mem_bg
		output wire        mem_0_act_n,   //                   .mem_act_n
		output wire        mem_0_par,     //                   .mem_par
		inout  wire [39:0] mem_0_dq,      //                   .mem_dq
		inout  wire [4:0]  mem_0_dqs_t,   //                   .mem_dqs_t
		inout  wire [4:0]  mem_0_dqs_c,   //                   .mem_dqs_c
		input  wire        mem_0_alert_n, //                   .mem_alert_n
		inout  wire [4:0]  mem_0_dbi_n,   //                   .mem_dbi_n
		output wire [0:0]  mem_0_ck_t,    //           mem_ck_0.mem_ck_t
		output wire [0:0]  mem_0_ck_c,    //                   .mem_ck_c
		output wire        mem_0_reset_n, //        mem_reset_n.mem_reset_n
		input  wire        oct_rzqin_0,   //              oct_0.oct_rzqin
		input  wire        ref_clk        //            ref_clk.clk
	);

	platform_emif_io96b_hps_0_emif_io96b_hps_300_2mmae3q emif_io96b_hps_0 (
		.mem_0_cke     (mem_0_cke),     //  output,   width = 1,       mem_0.mem_cke
		.mem_0_odt     (mem_0_odt),     //  output,   width = 1,            .mem_odt
		.mem_0_cs_n    (mem_0_cs_n),    //  output,   width = 1,            .mem_cs_n
		.mem_0_a       (mem_0_a),       //  output,  width = 17,            .mem_a
		.mem_0_ba      (mem_0_ba),      //  output,   width = 2,            .mem_ba
		.mem_0_bg      (mem_0_bg),      //  output,   width = 1,            .mem_bg
		.mem_0_act_n   (mem_0_act_n),   //  output,   width = 1,            .mem_act_n
		.mem_0_par     (mem_0_par),     //  output,   width = 1,            .mem_par
		.mem_0_dq      (mem_0_dq),      //   inout,  width = 40,            .mem_dq
		.mem_0_dqs_t   (mem_0_dqs_t),   //   inout,   width = 5,            .mem_dqs_t
		.mem_0_dqs_c   (mem_0_dqs_c),   //   inout,   width = 5,            .mem_dqs_c
		.mem_0_alert_n (mem_0_alert_n), //   input,   width = 1,            .mem_alert_n
		.mem_0_dbi_n   (mem_0_dbi_n),   //   inout,   width = 5,            .mem_dbi_n
		.mem_0_ck_t    (mem_0_ck_t),    //  output,   width = 1,    mem_ck_0.mem_ck_t
		.mem_0_ck_c    (mem_0_ck_c),    //  output,   width = 1,            .mem_ck_c
		.mem_0_reset_n (mem_0_reset_n), //  output,   width = 1, mem_reset_n.mem_reset_n
		.oct_rzqin_0   (oct_rzqin_0),   //   input,   width = 1,       oct_0.oct_rzqin
		.ref_clk       (ref_clk)        //   input,   width = 1,     ref_clk.clk
	);

endmodule
