// platform_intel_noc_clock_ctrl_1.v

// Generated using ACDS version 25.1 129

`timescale 1 ps / 1 ps
module platform_intel_noc_clock_ctrl_1 (
		input  wire  refclk,     //        refclk.clk
		output wire  pll_lock_o  //    pll_lock_o.pll_lock_o
	);

	intel_noc_clock_ctrl #(
		.REFCLK_FREQ ("NOC_PLL_REFCLK_FREQ_100_MHZ"),
		.NOC_BIN     ("NOC_BIN_BIN2")
	) intel_noc_clock_ctrl_1 (
		.refclk     (refclk),     //   input,  width = 1,     refclk.clk
		.pll_lock_o (pll_lock_o)  //  output,  width = 1, pll_lock_o.pll_lock_o
	);

endmodule
