// intel_pcie_io_pll.v

// Generated using ACDS version 25.1 129

`timescale 1 ps / 1 ps
module intel_pcie_io_pll (
		input  wire  refclk,     //     refclk.clk
		output wire  locked,     //     locked.export
		input  wire  rst,        //      reset.reset
		input  wire  permit_cal, // permit_cal.export
		output wire  outclk_0    //    outclk0.clk
	);

	platform_intel_pcie_rtile_mcdma_0_altera_iopll_2000_ukmylei intel_pcie_io_pll (
		.refclk     (refclk),     //   input,  width = 1,     refclk.clk
		.locked     (locked),     //  output,  width = 1,     locked.export
		.rst        (rst),        //   input,  width = 1,      reset.reset
		.permit_cal (permit_cal), //   input,  width = 1, permit_cal.export
		.outclk_0   (outclk_0)    //  output,  width = 1,    outclk0.clk
	);

endmodule
